/* Training Grounds curriculum, taught by Rock Lee. Eight jutsu (data structures):
   hash maps & sets, linked lists, stacks, queues, heaps, trees, graphs & grids, dynamic programming.
     D  Hand Seals            — learn each structure's everyday operations in Python
     C  Shape Transformation  — small problems, one structure each
     B  Nature Transformation — LeetCode-easy problems, one structure each
     A  Combat Practice       — NeetCode-easy problems that mix structures
   Same problem format as lessons.js. `prelude` is code that runs before the student's (and is shown to them). */
(function () {
  var LIST = "class ListNode:\n    def __init__(self, val, next=None):\n        self.val = val\n        self.next = next\n\ndef build_list(values):\n    head = None\n    for v in reversed(values):\n        head = ListNode(v, head)\n    return head\n\ndef to_list(head):\n    out = []\n    while head:\n        out.append(head.val)\n        head = head.next\n    return out\n";
  var TREE = "class TreeNode:\n    def __init__(self, val, left=None, right=None):\n        self.val = val\n        self.left = left\n        self.right = right\n\ndef build_tree(values):\n    # level order, None for a missing child, e.g. [1, 2, 3, None, 4]\n    if not values or values[0] is None:\n        return None\n    nodes = [TreeNode(v) if v is not None else None for v in values]\n    kids = nodes[1:][::-1]\n    for node in nodes:\n        if node:\n            if kids: node.left = kids.pop()\n            if kids: node.right = kids.pop()\n    return nodes[0]\n";

  window.JUTSU = [
  /* ============================ D-RANK ============================ */
  { id: "D", rank: "D", title: "Hand Seals", short: "Seals", kanji: "印",
    intro: "Every jutsu begins with hand seals! Here you learn the basic signs for each structure — the handful of Python moves you'll use every single day. Drill them until your fingers know them without thinking.",
    topics: [
      { id: "jd-hash", title: "Hash maps & sets", kanji: "辞", intro: "A dictionary is the village registry: look up a key, get its value, instantly. A set is a bag of unique keys with no values.", problems: [
        { id: "jd1", title: "The Hokage's registry",
          say: "Every shinobi is on record. A dictionary finds any name instantly, no matter how thick the book.",
          task: "Make a dictionary called `ranks` where `'Naruto'` maps to `'Genin'`, `'Kakashi'` to `'Jonin'` and `'Tsunade'` to `'Kage'`. Print Kakashi's rank. Then add `'Sakura'` with rank `'Genin'` and print how many shinobi are on record.",
          examples: ["It should print:\nJonin\n4"],
          check: "assert 'ranks' in dir() and isinstance(ranks, dict), 'Make a dictionary called ranks.'\nassert ranks.get('Kakashi') == 'Jonin', 'ranks[\"Kakashi\"] should be Jonin.'\nassert ranks.get('Sakura') == 'Genin', 'Add Sakura with ranks[\"Sakura\"] = \"Genin\".'\nassert len(ranks) == 4\nlines = [l.strip() for l in _out.strip().splitlines()]\nassert lines == ['Jonin', '4'], f'Got {lines}'",
          solution: "ranks = {'Naruto': 'Genin', 'Kakashi': 'Jonin', 'Tsunade': 'Kage'}\nprint(ranks['Kakashi'])\nranks['Sakura'] = 'Genin'\nprint(len(ranks))" },
        { id: "jd2", title: "Weapons inventory",
          say: "The most common dictionary move: counting. .get(key, 0) hands you 0 the first time you see a weapon, instead of an error.",
          task: "Count how many of each weapon is in the pouch, storing the counts in a dictionary called `count`. Then print how many kunai there are.",
          starter: "pouch = ['kunai', 'shuriken', 'kunai', 'scroll', 'kunai', 'shuriken']\n",
          examples: ["It should print:\n3", "count ends up as {'kunai': 3, 'shuriken': 2, 'scroll': 1}"],
          hint: "count[w] = count.get(w, 0) + 1 inside a loop.",
          check: "assert 'count' in dir() and isinstance(count, dict), 'Make a dictionary called count.'\nassert count == {'kunai': 3, 'shuriken': 2, 'scroll': 1}, f'count is {count}'\nassert _out.strip() == '3'",
          solution: "pouch = ['kunai', 'shuriken', 'kunai', 'scroll', 'kunai', 'shuriken']\ncount = {}\nfor w in pouch:\n    count[w] = count.get(w, 0) + 1\nprint(count['kunai'])" },
        { id: "jd3", title: "Mission payroll",
          say: "You can walk a dictionary three ways: its keys, its values, or both at once with .items().",
          task: "Loop over `pay` with `.items()` and print each line as `<name>: <ryo>`. Then print the total ryō paid out.",
          starter: "pay = {'Naruto': 5000, 'Sakura': 7000, 'Sai': 3000}\n",
          examples: ["It should print:\nNaruto: 5000\nSakura: 7000\nSai: 3000\n15000"],
          check: "assert '.items()' in _src, 'Loop with for name, ryo in pay.items().'\nlines = [l.strip() for l in _out.strip().splitlines()]\nassert lines == ['Naruto: 5000', 'Sakura: 7000', 'Sai: 3000', '15000'], f'Got {lines}'",
          solution: "pay = {'Naruto': 5000, 'Sakura': 7000, 'Sai': 3000}\nfor name, ryo in pay.items():\n    print(name + ': ' + str(ryo))\nprint(sum(pay.values()))" },
        { id: "jd4", title: "Who actually showed up",
          say: "Naruto signed the attendance sheet three times. A set throws away duplicates and answers 'is this person here?' instantly.",
          task: "Turn the attendance list `signed` into a set called `present`. Print how many different shinobi are present, then print whether `'Sai'` is present, then add `'Ino'` and print the count again.",
          starter: "signed = ['Naruto', 'Sakura', 'Naruto', 'Sai', 'Sakura', 'Naruto']\n",
          examples: ["It should print:\n3\nTrue\n4"],
          check: "assert 'present' in dir() and isinstance(present, set), 'Make a set called present with set(signed).'\nassert present == {'Naruto', 'Sakura', 'Sai', 'Ino'}, f'present is {present}'\nlines = [l.strip() for l in _out.strip().splitlines()]\nassert lines == ['3', 'True', '4'], f'Got {lines}'",
          solution: "signed = ['Naruto', 'Sakura', 'Naruto', 'Sai', 'Sakura', 'Naruto']\npresent = set(signed)\nprint(len(present))\nprint('Sai' in present)\npresent.add('Ino')\nprint(len(present))" }
      ]},
      { id: "jd-linked", title: "Linked lists", kanji: "鎖", intro: "A linked list is a chain of shadow clones: each one holds a value and points to the next. You only ever hold the first clone — the head.", problems: [
        { id: "jd5", title: "Forge the chain",
          say: "Make three nodes by hand and link them like clones holding hands. Then walk the chain with a while loop until you run out of clones.",
          task: "Using the provided `ListNode` class, make a chain `head` with the values 1, 2, 3 in that order by creating nodes and setting `.next`. Then walk it with a while loop and print each value.",
          prelude: LIST,
          examples: ["It should print:\n1\n2\n3"],
          check: "assert 'head' in dir() and isinstance(head, ListNode), 'Make head a ListNode.'\nassert to_list(head) == [1, 2, 3], f'The chain holds {to_list(head)}, expected [1, 2, 3].'\nassert 'build_list' not in _src, 'Build the nodes yourself this time.'\nlines = [l.strip() for l in _out.strip().splitlines()]\nassert lines == ['1', '2', '3'], f'Got {lines}'",
          solution: "head = ListNode(1)\nhead.next = ListNode(2)\nhead.next.next = ListNode(3)\n\nnode = head\nwhile node:\n    print(node.val)\n    node = node.next" },
        { id: "jd6", title: "How many clones?",
          say: "You can't call len on a chain of clones. Walk it and count as you go.",
          task: "Write a function called `clone_count` that takes in the head of a linked list and returns how many nodes it has (0 for an empty chain, which is `None`).",
          prelude: LIST,
          examples: ["clone_count(build_list([5, 7, 9])) → 3", "clone_count(None) → 0"],
          check: "assert clone_count(build_list([5, 7, 9])) == 3, f'clone_count of [5, 7, 9] came back {clone_count(build_list([5, 7, 9]))}'\nassert clone_count(None) == 0, 'An empty chain (None) has 0 clones.'\nassert clone_count(build_list([1])) == 1",
          solution: "def clone_count(head):\n    count = 0\n    node = head\n    while node:\n        count += 1\n        node = node.next\n    return count" },
        { id: "jd7", title: "Summon one more clone",
          say: "To add a clone at the end, walk to the last one (whose .next is None) and attach the new one there. Watch out for an empty chain.",
          task: "Write a function called `summon` that takes in the head of a linked list and a value, adds a new node with that value to the end, and returns the head. If the chain is empty (`None`), the new node becomes the head.",
          prelude: LIST,
          examples: ["to_list(summon(build_list([1, 2]), 3)) → [1, 2, 3]", "to_list(summon(None, 7)) → [7]"],
          check: "assert to_list(summon(build_list([1, 2]), 3)) == [1, 2, 3], f'Got {to_list(summon(build_list([1, 2]), 3))}'\nassert to_list(summon(None, 7)) == [7], 'Summoning into an empty chain should return a one-node chain.'",
          solution: "def summon(head, val):\n    new = ListNode(val)\n    if head is None:\n        return new\n    node = head\n    while node.next:\n        node = node.next\n    node.next = new\n    return head" }
      ]},
      { id: "jd-stack", title: "Stacks", kanji: "積", intro: "A stack is a pile of scrolls on the Hokage's desk: the last one placed is the first one picked up. In Python a plain list is a stack — append pushes, pop takes the top.", problems: [
        { id: "jd8", title: "Pile of scrolls",
          say: "Stack three scrolls, then take two off. The last one placed is the first one lifted.",
          task: "Make an empty list called `pile`. Push `'fire'`, `'water'`, `'wind'` with append. Pop twice, printing each scroll you lift. Then print the pile.",
          examples: ["It should print:\nwind\nwater\n['fire']"],
          check: "assert '.append(' in _src and '.pop()' in _src, 'Use append to push and pop() to take the top.'\nassert pile == ['fire'], f'pile is {pile}'\nlines = [l.strip() for l in _out.strip().splitlines()]\nassert lines == ['wind', 'water', \"['fire']\"], f'Got {lines}'",
          solution: "pile = []\npile.append('fire')\npile.append('water')\npile.append('wind')\nprint(pile.pop())\nprint(pile.pop())\nprint(pile)" },
        { id: "jd9", title: "Peek at the top scroll",
          say: "Two checks you'll make constantly: what's on top (without lifting it) and whether the pile is empty.",
          task: "Write a function called `top_scroll` that returns the top item of a stack without removing it, or `None` if the stack is empty. Write a function called `is_empty` that returns True if the stack has nothing in it.",
          examples: ["top_scroll(['fire', 'water', 'wind']) → 'wind'", "top_scroll([]) → None", "is_empty([]) → True"],
          check: "assert top_scroll(['fire', 'water', 'wind']) == 'wind', 'top_scroll should return the last item.'\ns = [1, 2, 3]; top_scroll(s); assert s == [1, 2, 3], 'top_scroll must not remove the item.'\nassert top_scroll([]) is None, 'An empty pile has no top: None.'\nassert is_empty([]) is True and is_empty([1]) is False",
          solution: "def top_scroll(stack):\n    if len(stack) == 0:\n        return None\n    return stack[-1]\n\ndef is_empty(stack):\n    return len(stack) == 0" }
      ]},
      { id: "jd-queue", title: "Queues", kanji: "列", intro: "A queue is the line at Ichiraku Ramen: first in, first served. Use collections.deque — append at the back, popleft from the front.", problems: [
        { id: "jd10", title: "The line at Ichiraku",
          say: "A list is slow at removing from the front. deque does it instantly. Import it, then append and popleft.",
          task: "Import `deque` from `collections`. Make a deque called `line` and add Naruto, Sasuke, Sakura in that order. Serve the person at the front with `popleft` and print their name. Then print how many are still waiting.",
          examples: ["It should print:\nNaruto\n2"],
          check: "assert 'from collections import deque' in _src, 'Start with: from collections import deque'\nassert '.popleft()' in _src, 'Use popleft() to serve from the front.'\nassert list(line) == ['Sasuke', 'Sakura'], f'line holds {list(line)}'\nlines = [l.strip() for l in _out.strip().splitlines()]\nassert lines == ['Naruto', '2'], f'Got {lines}'",
          solution: "from collections import deque\nline = deque()\nline.append('Naruto')\nline.append('Sasuke')\nline.append('Sakura')\nprint(line.popleft())\nprint(len(line))" },
        { id: "jd11", title: "Mission desk",
          say: "The classic queue loop: while there's a mission waiting, take the front one and complete it.",
          task: "Write a function called `complete_all` that takes in a list of mission names, puts them in a deque in order, then takes them out one at a time from the front, printing `Mission complete: <name>` for each. Return how many were completed.",
          examples: ["complete_all(['escort', 'patrol']) prints:\nMission complete: escort\nMission complete: patrol\nand returns 2"],
          check: "assert 'deque' in _src and '.popleft()' in _src, 'Use a deque and popleft.'\nimport io, sys\n_buf = io.StringIO(); _old = sys.stdout; sys.stdout = _buf\nn = complete_all(['escort', 'patrol', 'rescue'])\nsys.stdout = _old\nassert n == 3, f'complete_all returned {n}, expected 3.'\nlines = [l.strip() for l in _buf.getvalue().strip().splitlines()]\nassert lines == ['Mission complete: escort', 'Mission complete: patrol', 'Mission complete: rescue'], f'It printed {lines}'",
          solution: "from collections import deque\n\ndef complete_all(missions):\n    q = deque(missions)\n    count = 0\n    while q:\n        name = q.popleft()\n        print('Mission complete: ' + name)\n        count += 1\n    return count" }
      ]},
      { id: "jd-heap", title: "Heaps", kanji: "峰", intro: "A heap always keeps the smallest item at the front, however you add things — like Shikamaru always knowing the laziest option. Python's heapq works on a plain list.", problems: [
        { id: "jd12", title: "Lightest kunai first",
          say: "Push kunai weights in any order; heappop always hands you the lightest. heap[0] lets you peek at it.",
          task: "Import `heapq`. Make an empty list called `heap` and push the weights 5, 1, 8, 3 with `heapq.heappush`. Pop one with `heapq.heappop` and print it. Then print `heap[0]` (the next lightest, without removing it).",
          examples: ["It should print:\n1\n3"],
          check: "assert 'import heapq' in _src and 'heappush' in _src and 'heappop' in _src, 'Use heapq.heappush and heapq.heappop.'\nlines = [l.strip() for l in _out.strip().splitlines()]\nassert lines == ['1', '3'], f'Got {lines}'\nassert sorted(heap) == [3, 5, 8]",
          solution: "import heapq\nheap = []\nheapq.heappush(heap, 5)\nheapq.heappush(heap, 1)\nheapq.heappush(heap, 8)\nheapq.heappush(heap, 3)\nprint(heapq.heappop(heap))\nprint(heap[0])" },
        { id: "jd13", title: "Strongest two",
          say: "heapq only does smallest-first. The trick for strongest-first: push the negative of each chakra level, and flip it back when you pop.",
          task: "Write a function called `strongest_two` that takes in a list of chakra levels and returns the two highest, biggest first, using a heap of negated values.",
          examples: ["strongest_two([40, 95, 60, 25, 80]) → [95, 80]"],
          hint: "Push -level for each level. heappop gives the most negative, i.e. the largest original. Negate it back.",
          check: "assert 'heapq' in _src, 'Use heapq.'\nassert '-' in _src, 'Negate the values so the largest comes out first.'\nassert strongest_two([40, 95, 60, 25, 80]) == [95, 80], f'Got {strongest_two([40, 95, 60, 25, 80])}'\nassert strongest_two([3, 1, 2]) == [3, 2]",
          solution: "import heapq\n\ndef strongest_two(levels):\n    heap = []\n    for s in levels:\n        heapq.heappush(heap, -s)\n    first = -heapq.heappop(heap)\n    second = -heapq.heappop(heap)\n    return [first, second]" }
      ]},
      { id: "jd-tree", title: "Trees", kanji: "樹", intro: "A binary tree node has a value and up to two children, left and right — like a clan's family scroll. Most tree code is a function that calls itself on each child.", problems: [
        { id: "jd14", title: "Plant the clan tree",
          say: "Build the smallest useful tree: a founder with two children. Then read the children back.",
          task: "Using the provided `TreeNode`, make a tree called `root` with value 1, a left child with value 2 and a right child with value 3. Print the left child's value, then the right child's value.",
          prelude: TREE,
          examples: ["It should print:\n2\n3"],
          check: "assert 'root' in dir() and isinstance(root, TreeNode), 'Make root a TreeNode.'\nassert root.val == 1 and root.left and root.left.val == 2 and root.right and root.right.val == 3, 'root should be 1 with left 2 and right 3.'\nlines = [l.strip() for l in _out.strip().splitlines()]\nassert lines == ['2', '3'], f'Got {lines}'",
          solution: "root = TreeNode(1)\nroot.left = TreeNode(2)\nroot.right = TreeNode(3)\nprint(root.left.val)\nprint(root.right.val)" },
        { id: "jd15", title: "Total chakra of the clan",
          say: "Here's the pattern for almost every tree jutsu: if the node is None, return the base case; otherwise combine the node with the answers for its left and right branches.",
          task: "Write a function called `clan_chakra` that takes in the root of a tree of chakra values and returns the sum of all of them. An empty tree (`None`) sums to 0.",
          prelude: TREE,
          examples: ["clan_chakra(build_tree([1, 2, 3])) → 6", "clan_chakra(build_tree([5, None, 7])) → 12", "clan_chakra(None) → 0"],
          hint: "return node.val + clan_chakra(node.left) + clan_chakra(node.right), after handling None.",
          check: "assert clan_chakra(None) == 0, 'None should sum to 0.'\nassert clan_chakra(build_tree([1, 2, 3])) == 6, f'Got {clan_chakra(build_tree([1, 2, 3]))} for [1, 2, 3]'\nassert clan_chakra(build_tree([5, None, 7])) == 12\nassert clan_chakra(build_tree([1, 2, 3, 4, 5, 6, 7])) == 28",
          solution: "def clan_chakra(node):\n    if node is None:\n        return 0\n    return node.val + clan_chakra(node.left) + clan_chakra(node.right)" }
      ]},
      { id: "jd-graph", title: "Graphs & grids", kanji: "網", intro: "A graph is places and the roads between them — a dictionary from each place to its neighbours. A grid is the Forest of Death map: rows of cells, and each cell's neighbours are up, down, left and right.", problems: [
        { id: "jd16", title: "Roads of the Leaf",
          say: "The simplest graph in Python: a dictionary where each place maps to the list of places you can walk to from it.",
          task: "Make a dictionary called `roads` describing these connections: Gate connects to Market and Academy; Market connects to Gate and Tower; Academy connects to Gate; Tower connects to Market. Print the neighbours of Gate, then print how many places there are.",
          examples: ["It should print:\n['Market', 'Academy']\n4"],
          check: "assert 'roads' in dir() and isinstance(roads, dict), 'Make a dictionary called roads.'\nassert roads.get('Gate') == ['Market', 'Academy'], f'roads[\"Gate\"] is {roads.get(\"Gate\")}'\nassert roads.get('Tower') == ['Market'] and len(roads) == 4, 'Check all four places and their neighbours.'\nlines = [l.strip() for l in _out.strip().splitlines()]\nassert lines == [\"['Market', 'Academy']\", '4'], f'Got {lines}'",
          solution: "roads = {\n    'Gate': ['Market', 'Academy'],\n    'Market': ['Gate', 'Tower'],\n    'Academy': ['Gate'],\n    'Tower': ['Market'],\n}\nprint(roads['Gate'])\nprint(len(roads))" },
        { id: "jd17", title: "Reading the forest map",
          say: "A grid is a list of rows. grid[r][c] is row r, column c. Rows and columns both start at 0.",
          task: "The Forest of Death map `forest` has a number of traps in each sector. Print the traps at row 1, column 2. Then print the number of rows, then the number of columns. Finally print the total traps in row 0.",
          starter: "forest = [\n    [1, 2, 3],\n    [4, 5, 6],\n    [7, 8, 9],\n    [10, 11, 12],\n]\n",
          examples: ["It should print:\n6\n4\n3\n6"],
          check: "lines = [l.strip() for l in _out.strip().splitlines()]\nassert lines == ['6', '4', '3', '6'], f'Got {lines}. Rows = len(forest), columns = len(forest[0]).'",
          solution: "forest = [\n    [1, 2, 3],\n    [4, 5, 6],\n    [7, 8, 9],\n    [10, 11, 12],\n]\nprint(forest[1][2])\nprint(len(forest))\nprint(len(forest[0]))\nprint(sum(forest[0]))" },
        { id: "jd18", title: "Which way can you step?",
          say: "Every grid jutsu needs this: standing in a sector, which of the four neighbouring sectors are actually inside the map?",
          task: "Write a function called `steps` that takes in the number of rows, the number of columns, and a cell `(r, c)`, and returns a list of the in-bounds neighbouring cells as `(row, col)` tuples, in the order up, down, left, right.",
          examples: ["steps(3, 3, 1, 1) → [(0, 1), (2, 1), (1, 0), (1, 2)]", "steps(3, 3, 0, 0) → [(1, 0), (0, 1)]   (up and left are off the map)"],
          check: "assert steps(3, 3, 1, 1) == [(0, 1), (2, 1), (1, 0), (1, 2)], f'Got {steps(3, 3, 1, 1)}'\nassert steps(3, 3, 0, 0) == [(1, 0), (0, 1)], f'Corner: got {steps(3, 3, 0, 0)}, expected [(1, 0), (0, 1)]'\nassert steps(2, 2, 1, 1) == [(0, 1), (1, 0)]",
          solution: "def steps(rows, cols, r, c):\n    result = []\n    for dr, dc in [(-1, 0), (1, 0), (0, -1), (0, 1)]:\n        nr = r + dr\n        nc = c + dc\n        if 0 <= nr < rows and 0 <= nc < cols:\n            result.append((nr, nc))\n    return result" }
      ]},
      { id: "jd-dp", title: "Dynamic programming", kanji: "記", intro: "Dynamic programming is the Sharingan of problem solving: remember every answer you've seen so you never solve the same sub-problem twice. Two forms — a memo dictionary on a recursive function, or a table filled from the bottom up.", problems: [
        { id: "jd19", title: "Sharingan memory",
          say: "Naive fib(35) makes tens of millions of calls. With a memo dictionary it makes 35. Write the fast one.",
          task: "Shadow clones multiply like Fibonacci: clones(0) = 0, clones(1) = 1, and each number is the sum of the two before. Write a function called `clones` that returns the n-th number, using a dictionary called `memo` so each n is only computed once.",
          examples: ["clones(10) → 55", "clones(50) → 12586269025"],
          hint: "If n is in memo, return memo[n]. Otherwise compute it, store it in memo[n], and return it.",
          check: "assert 'memo' in _src, 'Use a dictionary called memo.'\nassert clones(10) == 55, f'clones(10) returned {clones(10)}'\nassert clones(50) == 12586269025, 'clones(50) should be 12586269025 — if this is slow or crashes, the memo is not being used.'",
          solution: "memo = {}\n\ndef clones(n):\n    if n < 2:\n        return n\n    if n in memo:\n        return memo[n]\n    memo[n] = clones(n - 1) + clones(n - 2)\n    return memo[n]" },
        { id: "jd20", title: "Fill the scroll",
          say: "The other form: no recursion at all. Make a list, fill the first entries by hand, then fill each next entry from the ones before it.",
          task: "Write a function called `clones_table` that returns the n-th clone number by building a list `dp` of length n + 1, where `dp[0] = 0`, `dp[1] = 1`, and each later `dp[i] = dp[i-1] + dp[i-2]`. Return `dp[n]`.",
          examples: ["clones_table(10) → 55", "clones_table(1) → 1"],
          check: "assert 'dp' in _src, 'Build a list called dp.'\nassert 'clones_table(' not in _src.replace('def clones_table(', ''), 'No recursion this time — fill the table with a loop.'\nassert clones_table(10) == 55, f'clones_table(10) returned {clones_table(10)}'\nassert clones_table(1) == 1 and clones_table(0) == 0\nassert clones_table(50) == 12586269025",
          solution: "def clones_table(n):\n    if n < 2:\n        return n\n    dp = [0] * (n + 1)\n    dp[1] = 1\n    for i in range(2, n + 1):\n        dp[i] = dp[i - 1] + dp[i - 2]\n    return dp[n]" }
      ]}
    ]},

  /* ============================ C-RANK ============================ */
  { id: "C", rank: "C", title: "Shape Transformation", short: "Shape", kanji: "形",
    intro: "Shape transformation! You know the seals — now you shape the chakra into something useful. Small problems, one structure at a time. The structure is the obvious tool; the work is applying it cleanly.",
    topics: [
      { id: "jc-hash", title: "Hash maps & sets", kanji: "辞", problems: [
        { id: "jc1", title: "Spot the impostor",
          say: "Someone signed the mission roster twice — a transformed enemy. Walk the roster once; a set remembers who you've seen.",
          task: "Write a function called `impostor` that takes in a list of names and returns the first name that appears for the second time. Return `None` if nobody repeats.",
          examples: ["impostor(['Naruto', 'Sakura', 'Sai', 'Sakura', 'Naruto']) → 'Sakura'", "impostor(['Naruto', 'Sakura']) → None"],
          check: "assert impostor(['Naruto', 'Sakura', 'Sai', 'Sakura', 'Naruto']) == 'Sakura', f'Got {impostor([\"Naruto\", \"Sakura\", \"Sai\", \"Sakura\", \"Naruto\"])!r} — Sakura repeats before Naruto does.'\nassert impostor(['Naruto', 'Sakura']) is None\nassert impostor([]) is None",
          solution: "def impostor(names):\n    seen = set()\n    for n in names:\n        if n in seen:\n            return n\n        seen.add(n)\n    return None" },
        { id: "jc2", title: "Clan census",
          say: "Group and count. Each clan is a key; how many shinobi it has is the value.",
          task: "Write a function called `census` that takes in a list of clan names (one per shinobi) and returns a dictionary from clan to how many shinobi belong to it.",
          examples: ["census(['Uchiha', 'Nara', 'Uchiha', 'Hyuga', 'Nara', 'Uchiha']) → {'Uchiha': 3, 'Nara': 2, 'Hyuga': 1}"],
          check: "assert census(['Uchiha', 'Nara', 'Uchiha', 'Hyuga', 'Nara', 'Uchiha']) == {'Uchiha': 3, 'Nara': 2, 'Hyuga': 1}, f'Got {census([\"Uchiha\", \"Nara\", \"Uchiha\", \"Hyuga\", \"Nara\", \"Uchiha\"])}'\nassert census([]) == {}",
          solution: "def census(clans):\n    sizes = {}\n    for c in clans:\n        sizes[c] = sizes.get(c, 0) + 1\n    return sizes" },
        { id: "jc3", title: "Double agents",
          say: "Which shinobi appear on both the Leaf roster and the Sand roster? Sets have operators for exactly this: & for both, | for either, - for one but not the other.",
          task: "Write a function called `on_both` that takes in two lists of names and returns a sorted list of the names that appear in both.",
          examples: ["on_both(['Naruto', 'Sakura', 'Sai'], ['Sai', 'Ino', 'Naruto']) → ['Naruto', 'Sai']"],
          check: "assert on_both(['Naruto', 'Sakura', 'Sai'], ['Sai', 'Ino', 'Naruto']) == ['Naruto', 'Sai'], f'Got {on_both([\"Naruto\", \"Sakura\", \"Sai\"], [\"Sai\", \"Ino\", \"Naruto\"])}'\nassert on_both(['Gaara'], ['Kankuro']) == []",
          solution: "def on_both(a, b):\n    return sorted(set(a) & set(b))" }
      ]},
      { id: "jc-linked", title: "Linked lists", kanji: "鎖", problems: [
        { id: "jc4", title: "Is the real one in the chain?",
          say: "Walk the clones until you find the one you want or run out of clones.",
          task: "Write a function called `in_chain` that takes in the head of a linked list and a value, and returns True if any node holds that value.",
          prelude: LIST,
          examples: ["in_chain(build_list([4, 8, 15]), 8) → True", "in_chain(build_list([4, 8, 15]), 9) → False", "in_chain(None, 1) → False"],
          check: "assert in_chain(build_list([4, 8, 15]), 8) is True\nassert in_chain(build_list([4, 8, 15]), 9) is False\nassert in_chain(None, 1) is False, 'An empty chain contains nothing.'",
          solution: "def in_chain(head, val):\n    node = head\n    while node:\n        if node.val == val:\n            return True\n        node = node.next\n    return False" },
        { id: "jc5", title: "Dispel a clone",
          say: "Dispelling a clone means the one before it links to the one after it. The head is special — nothing is before it.",
          task: "Write a function called `dispel` that takes in the head of a linked list and a value, removes the first node with that value, and returns the (possibly new) head. If the value isn't there, return the head unchanged.",
          prelude: LIST,
          examples: ["to_list(dispel(build_list([1, 2, 3, 2]), 2)) → [1, 3, 2]", "to_list(dispel(build_list([1, 2]), 1)) → [2]   (the head itself was dispelled)", "to_list(dispel(build_list([1, 2]), 9)) → [1, 2]"],
          hint: "If head.val matches, return head.next. Otherwise walk with a prev pointer; when node.val matches, set prev.next = node.next.",
          check: "assert to_list(dispel(build_list([1, 2, 3, 2]), 2)) == [1, 3, 2], f'Got {to_list(dispel(build_list([1, 2, 3, 2]), 2))}'\nassert to_list(dispel(build_list([1, 2]), 1)) == [2], 'Dispelling the head should return the second node as the new head.'\nassert to_list(dispel(build_list([1, 2]), 9)) == [1, 2]\nassert dispel(None, 1) is None",
          solution: "def dispel(head, val):\n    if head is None:\n        return None\n    if head.val == val:\n        return head.next\n    prev = head\n    node = head.next\n    while node:\n        if node.val == val:\n            prev.next = node.next\n            return head\n        prev = node\n        node = node.next\n    return head" },
        { id: "jc6", title: "Scroll to chain, chain to scroll",
          say: "Converting between a chain and a plain list is something you'll do in every exam. Write both directions yourself — without the provided helpers.",
          task: "Write `unroll(head)` that returns a Python list of the node values, and `roll(values)` that builds a chain from a Python list and returns its head (`None` for an empty list). Don't call the provided `to_list` or `build_list`.",
          prelude: LIST,
          examples: ["unroll(build_list([1, 2, 3])) → [1, 2, 3]", "to_list(roll([4, 5])) → [4, 5]"],
          check: "assert 'to_list(' not in _src.replace('def to_list(', '') and 'build_list(' not in _src.replace('def build_list(', ''), 'Write them yourself without to_list or build_list.'\nassert unroll(build_list([1, 2, 3])) == [1, 2, 3], f'Got {unroll(build_list([1, 2, 3]))}'\nassert unroll(None) == []\nassert to_list(roll([4, 5])) == [4, 5], f'roll([4, 5]) built {to_list(roll([4, 5]))}'\nassert roll([]) is None",
          solution: "def unroll(head):\n    values = []\n    node = head\n    while node:\n        values.append(node.val)\n        node = node.next\n    return values\n\ndef roll(values):\n    head = None\n    for v in reversed(values):\n        head = ListNode(v, head)\n    return head" }
      ]},
      { id: "jc-stack", title: "Stacks", kanji: "積", problems: [
        { id: "jc7", title: "Reverse the password",
          say: "The gate password is read backwards. Push every character onto a stack, then pop them all — out they come reversed.",
          task: "Write a function called `reverse_password` that takes in a string and returns it reversed, using a list as a stack. No slicing tricks like `[::-1]` and no `reversed()`.",
          examples: ["reverse_password('kunai') → 'ianuk'", "reverse_password('') → ''"],
          check: "assert '[::-1]' not in _src and 'reversed(' not in _src, 'Use a stack — push each character, then pop.'\nassert '.pop()' in _src, 'Pop the characters off the stack.'\nassert reverse_password('kunai') == 'ianuk', f'Got {reverse_password(\"kunai\")!r}'\nassert reverse_password('') == ''",
          solution: "def reverse_password(text):\n    stack = []\n    for ch in text:\n        stack.append(ch)\n    result = ''\n    while stack:\n        result += stack.pop()\n    return result" },
        { id: "jc8", title: "Sealing formula",
          say: "A sealing formula is written with brackets. Every opening bracket waits on the stack for its partner. A closing bracket with nothing waiting breaks the seal, and so does anything left waiting at the end.",
          task: "Write a function called `sealed` that takes in a string containing only `(` and `)` and returns True if every opening bracket is closed in the right order.",
          examples: ["sealed('(())') → True", "sealed('(()') → False", "sealed(')(') → False", "sealed('') → True"],
          hint: "Push on '('. On ')', if the stack is empty return False, otherwise pop. At the end, return whether the stack is empty.",
          check: "assert sealed('(())') is True\nassert sealed('(()') is False, 'An unclosed ( breaks the seal.'\nassert sealed(')(') is False, 'A ) with nothing open breaks the seal.'\nassert sealed('') is True\nassert sealed('()()') is True",
          solution: "def sealed(text):\n    stack = []\n    for ch in text:\n        if ch == '(':\n            stack.append(ch)\n        else:\n            if not stack:\n                return False\n            stack.pop()\n    return len(stack) == 0" }
      ]},
      { id: "jc-queue", title: "Queues", kanji: "列", problems: [
        { id: "jc9", title: "Teuchi serves k bowls",
          say: "Serve some of the ramen line, and tell me who's still waiting.",
          task: "Write a function called `serve` that takes in a list of names and a number k, serves the first k people (removing them from the front of a deque), and returns a list of who is still in line.",
          examples: ["serve(['Naruto', 'Sasuke', 'Sakura', 'Sai'], 2) → ['Sakura', 'Sai']", "serve(['Naruto'], 5) → []"],
          check: "assert 'deque' in _src and '.popleft()' in _src, 'Use a deque and popleft.'\nassert serve(['Naruto', 'Sasuke', 'Sakura', 'Sai'], 2) == ['Sakura', 'Sai'], f'Got {serve([\"Naruto\", \"Sasuke\", \"Sakura\", \"Sai\"], 2)}'\nassert serve(['Naruto'], 5) == [], 'Serving more than the line has should leave an empty list, not crash.'",
          solution: "from collections import deque\n\ndef serve(names, k):\n    line = deque(names)\n    for _ in range(k):\n        if line:\n            line.popleft()\n    return list(line)" },
        { id: "jc10", title: "Paper bomb circle",
          say: "Genin stand in a circle passing a paper bomb. Every k-th pass, whoever is holding it is out. Who's last standing? A deque makes the circle easy: move the front to the back k-1 times, then drop the front.",
          task: "Write a function called `last_standing` that takes in a list of names and a number k, and returns the name of the last person left when every k-th person is eliminated around the circle.",
          examples: ["last_standing(['Kiba', 'Shino', 'Hinata', 'Choji'], 2) → 'Kiba'   (Shino out, Choji out, Hinata out)", "last_standing(['Naruto', 'Sasuke', 'Sakura'], 3) → 'Sasuke'"],
          hint: "While more than one remains: repeat k-1 times move popleft() to the back with append; then popleft() the eliminated one.",
          check: "assert 'deque' in _src, 'Use a deque for the circle.'\nassert last_standing(['Kiba', 'Shino', 'Hinata', 'Choji'], 2) == 'Kiba', f'Got {last_standing([\"Kiba\", \"Shino\", \"Hinata\", \"Choji\"], 2)!r}, expected Kiba.'\nassert last_standing(['Naruto', 'Sasuke', 'Sakura'], 3) == 'Sasuke'\nassert last_standing(['Lee'], 7) == 'Lee'",
          solution: "from collections import deque\n\ndef last_standing(names, k):\n    circle = deque(names)\n    while len(circle) > 1:\n        for _ in range(k - 1):\n            circle.append(circle.popleft())\n        circle.popleft()\n    return circle[0]" }
      ]},
      { id: "jc-heap", title: "Heaps", kanji: "峰", problems: [
        { id: "jc11", title: "Tenten's lightest kunai",
          say: "Put every kunai on a heap and pop k times. Sorting works too — but the heap is the jutsu we're drilling.",
          task: "Write a function called `lightest` that takes in a list of kunai weights and a number k, and returns the k lightest in increasing order, using a heap.",
          examples: ["lightest([9, 2, 7, 4, 1], 3) → [1, 2, 4]", "lightest([5, 3], 5) → [3, 5]"],
          check: "assert 'heapq' in _src and 'sort' not in _src, 'Use heapq, not sorting.'\nassert lightest([9, 2, 7, 4, 1], 3) == [1, 2, 4], f'Got {lightest([9, 2, 7, 4, 1], 3)}'\nassert lightest([5, 3], 5) == [3, 5], 'If k is bigger than the list, return everything in order.'",
          solution: "import heapq\n\ndef lightest(weights, k):\n    heap = list(weights)\n    heapq.heapify(heap)\n    result = []\n    while heap and len(result) < k:\n        result.append(heapq.heappop(heap))\n    return result" },
        { id: "jc12", title: "Top exam scores",
          say: "Highest-first again, but this time return the top k. Push the negative, pop k times, flip them back.",
          task: "Write a function called `top_scores` that takes in a list of Chunin exam scores and a number k and returns the k highest, biggest first, using a heap.",
          examples: ["top_scores([40, 95, 60, 25, 80], 2) → [95, 80]", "top_scores([7], 3) → [7]"],
          check: "assert 'heapq' in _src and 'sort' not in _src, 'Use heapq, not sorting.'\nassert top_scores([40, 95, 60, 25, 80], 2) == [95, 80], f'Got {top_scores([40, 95, 60, 25, 80], 2)}'\nassert top_scores([7], 3) == [7]\nassert top_scores([1, 2, 3, 4], 3) == [4, 3, 2]",
          solution: "import heapq\n\ndef top_scores(scores, k):\n    heap = [-s for s in scores]\n    heapq.heapify(heap)\n    result = []\n    while heap and len(result) < k:\n        result.append(-heapq.heappop(heap))\n    return result" }
      ]},
      { id: "jc-tree", title: "Trees", kanji: "樹", problems: [
        { id: "jc13", title: "Count the clan",
          say: "Same shape as clan_chakra: base case for None, then one plus the two branches.",
          task: "Write a function called `clan_size` that takes in the root of a tree and returns how many nodes it has.",
          prelude: TREE,
          examples: ["clan_size(build_tree([1, 2, 3, 4])) → 4", "clan_size(None) → 0"],
          check: "assert clan_size(None) == 0\nassert clan_size(build_tree([1, 2, 3, 4])) == 4, f'Got {clan_size(build_tree([1, 2, 3, 4]))}'\nassert clan_size(build_tree([1, None, 2, None, 3])) == 3",
          solution: "def clan_size(node):\n    if node is None:\n        return 0\n    return 1 + clan_size(node.left) + clan_size(node.right)" },
        { id: "jc14", title: "How many generations?",
          say: "The height of a clan tree is the longest line from founder to youngest. It's 1 plus the taller of the two branches.",
          task: "Write a function called `generations` that takes in the root of a tree and returns its height: the number of nodes on the longest root-to-leaf path. An empty tree has height 0.",
          prelude: TREE,
          examples: ["generations(build_tree([1, 2, 3])) → 2", "generations(build_tree([1, 2, None, 3])) → 3", "generations(None) → 0"],
          check: "assert generations(None) == 0\nassert generations(build_tree([1, 2, 3])) == 2, f'Got {generations(build_tree([1, 2, 3]))} for a root with two children.'\nassert generations(build_tree([1, 2, None, 3])) == 3, 'A line of three nodes down the left has height 3.'\nassert generations(build_tree([1])) == 1",
          solution: "def generations(node):\n    if node is None:\n        return 0\n    return 1 + max(generations(node.left), generations(node.right))" },
        { id: "jc15", title: "Strongest in the clan",
          say: "Combine the node with the best from each branch. Be careful what you return for None — it has to lose against any real value, even a negative one.",
          task: "Write a function called `clan_strongest` that takes in the root of a non-empty tree of chakra values and returns the largest value in it.",
          prelude: TREE,
          examples: ["clan_strongest(build_tree([3, 9, 20, None, None, 15, 7])) → 20", "clan_strongest(build_tree([-5, -9, -1])) → -1"],
          hint: "Gather the node's value and the maxima of any children that exist, then return max of those.",
          check: "assert clan_strongest(build_tree([3, 9, 20, None, None, 15, 7])) == 20, f'Got {clan_strongest(build_tree([3, 9, 20, None, None, 15, 7]))}'\nassert clan_strongest(build_tree([-5, -9, -1])) == -1, 'With negative values, make sure None does not win with a 0.'\nassert clan_strongest(build_tree([4])) == 4",
          solution: "def clan_strongest(node):\n    best = node.val\n    if node.left:\n        best = max(best, clan_strongest(node.left))\n    if node.right:\n        best = max(best, clan_strongest(node.right))\n    return best" }
      ]},
      { id: "jc-graph", title: "Graphs & grids", kanji: "網", problems: [
        { id: "jc16", title: "Count the roads",
          say: "On a map where roads go both ways, every road appears twice — once from each end. Count the neighbour entries and halve them.",
          task: "Write a function called `road_count` that takes in a map (a dictionary from place to list of neighbours, with every road listed from both ends) and returns how many roads there are.",
          examples: ["road_count({'Gate': ['Market', 'Academy'], 'Market': ['Gate'], 'Academy': ['Gate']}) → 2", "road_count({'Gate': []}) → 0"],
          check: "assert road_count({'Gate': ['Market', 'Academy'], 'Market': ['Gate'], 'Academy': ['Gate']}) == 2, f'Got {road_count({\"Gate\": [\"Market\", \"Academy\"], \"Market\": [\"Gate\"], \"Academy\": [\"Gate\"]})}'\nassert road_count({'Gate': []}) == 0\nassert road_count({'A': ['B'], 'B': ['A', 'C'], 'C': ['B', 'D'], 'D': ['C']}) == 3",
          solution: "def road_count(roads):\n    total = 0\n    for place in roads:\n        total += len(roads[place])\n    return total // 2" },
        { id: "jc17", title: "Count the traps",
          say: "A Forest of Death map of 0s (clear) and 1s (trap). Two loops, one over rows and one over columns, visit every sector.",
          task: "Write a function called `count_traps` that takes in a grid (a list of rows of 0s and 1s) and returns how many traps (1s) it contains.",
          examples: ["count_traps([[0, 1, 0], [1, 1, 0]]) → 3", "count_traps([[0]]) → 0"],
          check: "assert count_traps([[0, 1, 0], [1, 1, 0]]) == 3, f'Got {count_traps([[0, 1, 0], [1, 1, 0]])}'\nassert count_traps([[0]]) == 0\nassert count_traps([[1, 1], [1, 1], [1, 1]]) == 6",
          solution: "def count_traps(grid):\n    total = 0\n    for row in grid:\n        for cell in row:\n            if cell == 1:\n                total += 1\n    return total" },
        { id: "jc18", title: "Safe steps from here",
          say: "Combine the two: a map, and the four-neighbour check. From a sector, how many neighbouring sectors are clear of traps?",
          task: "Write a function called `safe_steps` that takes in a grid (0 = clear, 1 = trap) and a cell `(r, c)`, and returns how many of the cell's up/down/left/right neighbours are inside the grid and clear.",
          examples: ["forest = [[0, 0, 1],\n          [1, 0, 0],\n          [0, 1, 0]]\nsafe_steps(forest, 1, 1) → 2   (up and right are clear; left and down are traps)", "safe_steps(forest, 0, 0) → 1"],
          check: "g = [[0, 0, 1], [1, 0, 0], [0, 1, 0]]\nassert safe_steps(g, 1, 1) == 2, f'Got {safe_steps(g, 1, 1)} for the centre sector, expected 2.'\nassert safe_steps(g, 0, 0) == 1, f'Got {safe_steps(g, 0, 0)} for the corner, expected 1 (only right is clear).'\nassert safe_steps(g, 2, 2) == 1",
          solution: "def safe_steps(grid, r, c):\n    rows = len(grid)\n    cols = len(grid[0])\n    count = 0\n    for dr, dc in [(-1, 0), (1, 0), (0, -1), (0, 1)]:\n        nr = r + dr\n        nc = c + dc\n        if 0 <= nr < rows and 0 <= nc < cols and grid[nr][nc] == 0:\n            count += 1\n    return count" }
      ]},
      { id: "jc-dp", title: "Dynamic programming", kanji: "記", problems: [
        { id: "jc19", title: "Climbing the Hokage Rock",
          say: "You climb the steps up Hokage Rock one or two at a time. How many different ways to the top? The ways to reach step n are the ways to reach n-1 plus the ways to reach n-2 — that's a table.",
          task: "Write a function called `ways` that takes in a number of steps n and returns how many distinct ways there are to climb them taking 1 or 2 steps at a time.",
          examples: ["ways(2) → 2   (1+1, 2)", "ways(3) → 3   (1+1+1, 1+2, 2+1)", "ways(10) → 89"],
          hint: "ways(1) = 1, ways(2) = 2, and ways(n) = ways(n-1) + ways(n-2). Fill a table or use a memo — a plain recursive version will be far too slow for 40.",
          check: "assert ways(1) == 1 and ways(2) == 2 and ways(3) == 3\nassert ways(10) == 89, f'ways(10) returned {ways(10)}'\nassert ways(40) == 165580141, 'ways(40) should be 165580141 — if this hangs, remember the answers.'",
          solution: "def ways(n):\n    if n <= 2:\n        return n\n    dp = [0] * (n + 1)\n    dp[1] = 1\n    dp[2] = 2\n    for i in range(3, n + 1):\n        dp[i] = dp[i - 1] + dp[i - 2]\n    return dp[n]" },
        { id: "jc20", title: "Cheapest climb",
          say: "Each step up the Rock costs chakra. You can start on step 0 or step 1 and climb one or two at a time; you've finished once you're past the last step. What's the least chakra you can spend? For each step, the cheapest way to stand on it comes from the cheaper of the two steps below.",
          task: "Write a function called `min_chakra` that takes in a list of step costs and returns the minimum total cost to get past the top. You may start on step 0 or step 1 and move 1 or 2 steps at a time; you pay a step's cost when you stand on it.",
          examples: ["min_chakra([10, 15, 20]) → 15   (start on step 1, jump past the top)", "min_chakra([1, 100, 1, 1, 1, 100, 1, 1, 100, 1]) → 6"],
          hint: "dp[i] = cost[i] + min(dp[i-1], dp[i-2]) is the cheapest way to stand on step i. The answer is the cheaper of the last two steps.",
          check: "assert min_chakra([10, 15, 20]) == 15, f'min_chakra([10, 15, 20]) returned {min_chakra([10, 15, 20])}, expected 15.'\nassert min_chakra([1, 100, 1, 1, 1, 100, 1, 1, 100, 1]) == 6, f'Got {min_chakra([1, 100, 1, 1, 1, 100, 1, 1, 100, 1])}, expected 6.'\nassert min_chakra([5, 3]) == 3",
          solution: "def min_chakra(cost):\n    n = len(cost)\n    dp = [0] * n\n    dp[0] = cost[0]\n    dp[1] = cost[1]\n    for i in range(2, n):\n        dp[i] = cost[i] + min(dp[i - 1], dp[i - 2])\n    return min(dp[n - 1], dp[n - 2])" }
      ]}
    ]},

  /* ============================ B-RANK ============================ */
  { id: "B", rank: "B", title: "Nature Transformation", short: "Nature", kanji: "性",
    intro: "Nature transformation — the real thing. These are the problems shinobi face in the Chunin exams and in job interviews. Still one structure each, but now you have to see which trick fits. Read every example before you write a line.",
    topics: [
      { id: "jb-hash", title: "Hash maps & sets", kanji: "辞", problems: [
        { id: "jb1", title: "Transformation jutsu",
          say: "Two code words are transformations of each other if they use exactly the same letters the same number of times. Count the letters of each and compare.",
          task: "Write a function called `is_transformation` that takes in two strings and returns True if one is a rearrangement of the other's letters.",
          examples: ["is_transformation('listen', 'silent') → True", "is_transformation('kunai', 'kunal') → False", "is_transformation('ab', 'a') → False"],
          hint: "Build a count dictionary from the first word, then spend the counts with the second.",
          check: "assert is_transformation('listen', 'silent') is True\nassert is_transformation('kunai', 'kunal') is False\nassert is_transformation('ab', 'a') is False, 'Different lengths can never be transformations.'\nassert is_transformation('aab', 'abb') is False, 'Same letters but different counts: no.'",
          solution: "def is_transformation(a, b):\n    if len(a) != len(b):\n        return False\n    count = {}\n    for ch in a:\n        count[ch] = count.get(ch, 0) + 1\n    for ch in b:\n        if count.get(ch, 0) == 0:\n            return False\n        count[ch] -= 1\n    return True" },
        { id: "jb2", title: "Ransom note",
          say: "Kidnappers want a note spelled from letters cut out of a Konoha newspaper. Each cut-out letter can be used once. Count what you have, then spend it.",
          task: "Write a function called `can_write` that takes in a note and a pile of cut-out letters (both strings) and returns True if the note can be spelled from the pile, using each letter at most once.",
          examples: ["can_write('aa', 'aab') → True", "can_write('aa', 'ab') → False", "can_write('', 'xyz') → True"],
          check: "assert can_write('aa', 'aab') is True\nassert can_write('aa', 'ab') is False, 'Only one a is available.'\nassert can_write('', 'xyz') is True\nassert can_write('kunai', 'iaknu') is True",
          solution: "def can_write(note, pile):\n    available = {}\n    for ch in pile:\n        available[ch] = available.get(ch, 0) + 1\n    for ch in note:\n        if available.get(ch, 0) == 0:\n            return False\n        available[ch] -= 1\n    return True" }
      ]},
      { id: "jb-linked", title: "Linked lists", kanji: "鎖", problems: [
        { id: "jb3", title: "Reverse the formation",
          say: "The classic. Walk the chain and at each clone flip its .next to point backwards. Three pointers: previous, current, and a saved next so you don't lose the rest of the chain.",
          task: "Write a function called `reverse_chain` that takes in the head of a linked list and returns the head of the reversed chain. Reverse it in place by changing the `.next` pointers — don't build a new chain.",
          prelude: LIST,
          examples: ["to_list(reverse_chain(build_list([1, 2, 3, 4]))) → [4, 3, 2, 1]", "reverse_chain(None) → None"],
          hint: "prev = None; node = head. Loop: nxt = node.next; node.next = prev; prev = node; node = nxt. Return prev.",
          check: "assert 'ListNode(' not in _src, 'Reverse in place by changing .next — don\\'t make new nodes.'\nh = build_list([1, 2, 3, 4]); r = reverse_chain(h)\nassert to_list(r) == [4, 3, 2, 1], f'Got {to_list(r)}'\nassert reverse_chain(None) is None\nassert to_list(reverse_chain(build_list([1]))) == [1]",
          solution: "def reverse_chain(head):\n    prev = None\n    node = head\n    while node:\n        nxt = node.next\n        node.next = prev\n        prev = node\n        node = nxt\n    return prev" },
        { id: "jb4", title: "The clone in the middle",
          say: "Two runners: Lee walks one clone at a time, Guy-sensei runs two. When Guy reaches the end, Lee is standing at the middle.",
          task: "Write a function called `middle` that takes in the head of a linked list and returns the value of the middle node. If there are two middle nodes, return the second one.",
          prelude: LIST,
          examples: ["middle(build_list([1, 2, 3, 4, 5])) → 3", "middle(build_list([1, 2, 3, 4, 5, 6])) → 4"],
          hint: "slow = fast = head. While fast and fast.next: slow = slow.next; fast = fast.next.next.",
          check: "assert middle(build_list([1, 2, 3, 4, 5])) == 3, f'Got {middle(build_list([1, 2, 3, 4, 5]))}'\nassert middle(build_list([1, 2, 3, 4, 5, 6])) == 4, 'With an even length, return the second middle.'\nassert middle(build_list([9])) == 9",
          solution: "def middle(head):\n    slow = head\n    fast = head\n    while fast and fast.next:\n        slow = slow.next\n        fast = fast.next.next\n    return slow.val" },
        { id: "jb5", title: "Merge two squads",
          say: "Two squads already lined up by chakra. Merge them into one line, still in order. A dummy node at the front saves you from special-casing the head.",
          task: "Write a function called `merge_squads` that takes in the heads of two sorted linked lists and returns the head of one sorted chain containing all the nodes. Relink the existing nodes — don't create new ones.",
          prelude: LIST,
          examples: ["to_list(merge_squads(build_list([1, 3, 5]), build_list([2, 4]))) → [1, 2, 3, 4, 5]", "to_list(merge_squads(None, build_list([1]))) → [1]"],
          hint: "dummy = ListNode(0); tail = dummy. While both: attach the smaller head to tail.next, advance that chain and tail. Then attach whatever is left. Return dummy.next.",
          check: "assert to_list(merge_squads(build_list([1, 3, 5]), build_list([2, 4]))) == [1, 2, 3, 4, 5], f'Got {to_list(merge_squads(build_list([1, 3, 5]), build_list([2, 4])))}'\nassert to_list(merge_squads(None, build_list([1]))) == [1]\nassert to_list(merge_squads(build_list([1, 1]), build_list([1]))) == [1, 1, 1]\nassert merge_squads(None, None) is None",
          solution: "def merge_squads(a, b):\n    dummy = ListNode(0)\n    tail = dummy\n    while a and b:\n        if a.val <= b.val:\n            tail.next = a\n            a = a.next\n        else:\n            tail.next = b\n            b = b.next\n        tail = tail.next\n    tail.next = a if a else b\n    return dummy.next" }
      ]},
      { id: "jb-stack", title: "Stacks", kanji: "積", problems: [
        { id: "jb6", title: "Three kinds of seal",
          say: "Three kinds of bracket in the sealing formula now. A closing bracket must match the most recent opening one — which is exactly what the top of the stack is.",
          task: "Write a function called `valid_seal` that takes in a string of `()[]{}` characters and returns True if every bracket is closed by the matching kind in the right order.",
          examples: ["valid_seal('()[]{}') → True", "valid_seal('([)]') → False", "valid_seal('{[]}') → True", "valid_seal('(') → False"],
          hint: "A dictionary from closing to opening bracket: pairs = {')': '(', ']': '[', '}': '{'}. On a closer, the stack must be non-empty and its top must equal pairs[ch].",
          check: "assert valid_seal('()[]{}') is True\nassert valid_seal('([)]') is False, '([)] closes the wrong bracket first.'\nassert valid_seal('{[]}') is True\nassert valid_seal('(') is False\nassert valid_seal(']') is False",
          solution: "def valid_seal(text):\n    pairs = {')': '(', ']': '[', '}': '{'}\n    stack = []\n    for ch in text:\n        if ch in pairs:\n            if not stack or stack[-1] != pairs[ch]:\n                return False\n            stack.pop()\n        else:\n            stack.append(ch)\n    return len(stack) == 0" },
        { id: "jb7", title: "Weakest-link stack",
          say: "A stack of shinobi that can also tell you the lowest chakra in it instantly. Keep a second stack that records the minimum as of each push.",
          task: "Make a class called `MinStack` with methods `push(x)`, `pop()`, `top()` (returns the top without removing it) and `get_min()` (returns the smallest value currently in the stack). Every method must be instant — no scanning the whole stack in get_min.",
          examples: ["s = MinStack()\ns.push(5); s.push(2); s.push(7)\ns.get_min() → 2\ns.pop()\ns.top() → 2\ns.pop()\ns.get_min() → 5"],
          hint: "Keep two lists: items and mins. On push(x), push x to items and min(x, mins[-1]) to mins. Pop both together.",
          check: "assert _src.count('min(') - _src.count('get_min(') <= 1, 'Keep a second stack of minimums rather than scanning.'\ns = MinStack()\ns.push(5); s.push(2); s.push(7)\nassert s.get_min() == 2, f'get_min returned {s.get_min()}, expected 2.'\nassert s.top() == 7\ns.pop()\nassert s.top() == 2 and s.get_min() == 2\ns.pop()\nassert s.get_min() == 5, 'After popping the 2, the minimum should go back to 5.'",
          solution: "class MinStack:\n    def __init__(self):\n        self.items = []\n        self.mins = []\n\n    def push(self, x):\n        self.items.append(x)\n        if self.mins:\n            self.mins.append(min(x, self.mins[-1]))\n        else:\n            self.mins.append(x)\n\n    def pop(self):\n        self.mins.pop()\n        return self.items.pop()\n\n    def top(self):\n        return self.items[-1]\n\n    def get_min(self):\n        return self.mins[-1]" }
      ]},
      { id: "jb-queue", title: "Queues", kanji: "列", problems: [
        { id: "jb8", title: "Byakugan sensor",
          say: "Hinata's sensor counts how many chakra pings arrived in the last 3000 milliseconds. Old pings drop off the front of the queue as time moves on.",
          task: "Make a class called `ChakraSensor` with a method `ping(t)` that records a ping at time t (times only ever increase) and returns how many pings have happened in the window `[t - 3000, t]`, including this one.",
          examples: ["s = ChakraSensor()\ns.ping(1) → 1\ns.ping(100) → 2\ns.ping(3001) → 3\ns.ping(3002) → 3   (the ping at 1 is now too old)"],
          hint: "Append t to a deque. While the front is less than t - 3000, popleft. Return the length.",
          check: "assert 'deque' in _src, 'Use a deque so dropping old pings is instant.'\nc = ChakraSensor()\nassert c.ping(1) == 1 and c.ping(100) == 2 and c.ping(3001) == 3\nassert c.ping(3002) == 3, 'At t=3002 the ping at t=1 is outside the window.'",
          solution: "from collections import deque\n\nclass ChakraSensor:\n    def __init__(self):\n        self.pings = deque()\n\n    def ping(self, t):\n        self.pings.append(t)\n        while self.pings[0] < t - 3000:\n            self.pings.popleft()\n        return len(self.pings)" },
        { id: "jb9", title: "Rolling average score",
          say: "Keep only the last k scores and average them. When a new one arrives and the window is full, the oldest leaves.",
          task: "Make a class called `RollingAverage` whose constructor takes in a window size k. Its method `add(x)` records x and returns the average of the most recent k values (or of all values if fewer than k have been added).",
          examples: ["m = RollingAverage(3)\nm.add(1) → 1.0\nm.add(10) → 5.5\nm.add(3) → 4.666...\nm.add(5) → 6.0   (the 1 dropped out: (10 + 3 + 5) / 3)"],
          hint: "Keep a deque and a running total. When len exceeds k, popleft and subtract it from the total.",
          check: "m = RollingAverage(3)\nassert m.add(1) == 1.0\nassert m.add(10) == 5.5\nassert abs(m.add(3) - 14 / 3) < 1e-9\nassert m.add(5) == 6.0, f'After adding 5 the window is [10, 3, 5], average 6.0.'",
          solution: "from collections import deque\n\nclass RollingAverage:\n    def __init__(self, k):\n        self.k = k\n        self.window = deque()\n        self.total = 0\n\n    def add(self, x):\n        self.window.append(x)\n        self.total += x\n        if len(self.window) > self.k:\n            self.total -= self.window.popleft()\n        return self.total / len(self.window)" }
      ]},
      { id: "jb-heap", title: "Heaps", kanji: "峰", problems: [
        { id: "jb10", title: "k-th strongest",
          say: "Keep a min-heap of size k. Its smallest element is the k-th strongest overall — anyone weaker than it can't be in the top k.",
          task: "Write a function called `kth_strongest` that takes in a list of chakra levels and a number k and returns the k-th largest value (duplicates count separately).",
          examples: ["kth_strongest([3, 2, 1, 5, 6, 4], 2) → 5", "kth_strongest([3, 2, 3, 1, 2, 4, 5, 5, 6], 4) → 4"],
          hint: "Push each number; if the heap grows past k, heappop. At the end heap[0] is the answer.",
          check: "assert 'heapq' in _src and 'sort' not in _src, 'Use a heap, not sorting.'\nassert kth_strongest([3, 2, 1, 5, 6, 4], 2) == 5, f'Got {kth_strongest([3, 2, 1, 5, 6, 4], 2)}'\nassert kth_strongest([3, 2, 3, 1, 2, 4, 5, 5, 6], 4) == 4\nassert kth_strongest([1], 1) == 1",
          solution: "import heapq\n\ndef kth_strongest(levels, k):\n    heap = []\n    for n in levels:\n        heapq.heappush(heap, n)\n        if len(heap) > k:\n            heapq.heappop(heap)\n    return heap[0]" },
        { id: "jb11", title: "Boulder smash",
          say: "Tsunade smashes the two heaviest boulders together. Equal weights shatter completely; otherwise the difference survives. Repeat until one or none is left. 'Two heaviest, repeatedly' is a heap's job.",
          task: "Write a function called `last_boulder` that takes in a list of boulder weights and returns the weight of the last boulder left, or 0 if none remain.",
          examples: ["last_boulder([2, 7, 4, 1, 8, 1]) → 1", "last_boulder([1]) → 1", "last_boulder([3, 3]) → 0"],
          hint: "Max-heap via negatives. While more than one boulder: pop two; if they differ, push the difference back.",
          check: "assert 'heapq' in _src, 'Use heapq.'\nassert last_boulder([2, 7, 4, 1, 8, 1]) == 1, f'Got {last_boulder([2, 7, 4, 1, 8, 1])}'\nassert last_boulder([1]) == 1\nassert last_boulder([3, 3]) == 0, 'Two equal boulders shatter each other.'",
          solution: "import heapq\n\ndef last_boulder(boulders):\n    heap = [-s for s in boulders]\n    heapq.heapify(heap)\n    while len(heap) > 1:\n        a = -heapq.heappop(heap)\n        b = -heapq.heappop(heap)\n        if a != b:\n            heapq.heappush(heap, -(a - b))\n    return -heap[0] if heap else 0" }
      ]},
      { id: "jb-tree", title: "Trees", kanji: "樹", problems: [
        { id: "jb12", title: "Mirror reflection",
          say: "Haku's ice mirrors reflect the whole tree: swap every node's left and right children. Recursion does the whole tree in four lines.",
          task: "Write a function called `mirror` that takes in the root of a tree, swaps the left and right children of every node, and returns the root.",
          prelude: TREE,
          examples: ["Before: [4, 2, 7, 1, 3, 6, 9]   After: root.left.val → 7, root.right.val → 2, root.left.left.val → 9"],
          check: "r = mirror(build_tree([4, 2, 7, 1, 3, 6, 9]))\nassert r.val == 4 and r.left.val == 7 and r.right.val == 2, 'The root\\'s children should be swapped.'\nassert r.left.left.val == 9 and r.left.right.val == 6 and r.right.left.val == 3 and r.right.right.val == 1, 'Deeper levels must be swapped too.'\nassert mirror(None) is None",
          solution: "def mirror(node):\n    if node is None:\n        return None\n    node.left, node.right = node.right, node.left\n    mirror(node.left)\n    mirror(node.right)\n    return node" },
        { id: "jb13", title: "Clone or original?",
          say: "Two trees are identical if the roots match, both left branches match and both right branches match. Handle the cases where one or both are None first.",
          task: "Write a function called `identical` that takes in the roots of two trees and returns True if they have the same shape and the same values everywhere.",
          prelude: TREE,
          examples: ["identical(build_tree([1, 2, 3]), build_tree([1, 2, 3])) → True", "identical(build_tree([1, 2]), build_tree([1, None, 2])) → False", "identical(None, None) → True"],
          check: "assert identical(build_tree([1, 2, 3]), build_tree([1, 2, 3])) is True\nassert identical(build_tree([1, 2]), build_tree([1, None, 2])) is False, 'Same values but different shape: not identical.'\nassert identical(None, None) is True\nassert identical(build_tree([1]), None) is False",
          solution: "def identical(a, b):\n    if a is None and b is None:\n        return True\n    if a is None or b is None:\n        return False\n    return a.val == b.val and identical(a.left, b.left) and identical(a.right, b.right)" },
        { id: "jb14", title: "Balanced stance",
          say: "A stance is balanced if, at every node, the left and right heights differ by at most one. Compute heights from the bottom up and bail out the moment you find an imbalance.",
          task: "Write a function called `balanced_tree` that takes in the root of a tree and returns True if every node's left and right subtree heights differ by no more than 1.",
          prelude: TREE,
          examples: ["balanced_tree(build_tree([3, 9, 20, None, None, 15, 7])) → True", "balanced_tree(build_tree([1, 2, 2, 3, 3, None, None, 4, 4])) → False", "balanced_tree(None) → True"],
          hint: "Write a helper that returns the height, or -1 if the subtree is unbalanced. If either child returns -1 or the heights differ by more than 1, return -1.",
          check: "assert balanced_tree(build_tree([3, 9, 20, None, None, 15, 7])) is True\nassert balanced_tree(build_tree([1, 2, 2, 3, 3, None, None, 4, 4])) is False, 'The left side is two levels deeper than the right.'\nassert balanced_tree(None) is True\nassert balanced_tree(build_tree([1, None, 2, None, 3])) is False",
          solution: "def balanced_tree(root):\n    def check(node):\n        if node is None:\n            return 0\n        left = check(node.left)\n        if left == -1:\n            return -1\n        right = check(node.right)\n        if right == -1:\n            return -1\n        if abs(left - right) > 1:\n            return -1\n        return 1 + max(left, right)\n    return check(root) != -1" }
      ]},
      { id: "jb-graph", title: "Graphs & grids", kanji: "網", problems: [
        { id: "jb15", title: "Water Style: flood",
          say: "Starting from a sector, flood it and every connected sector of the same terrain. Recursion or a queue — either works. Mark sectors as you go so you don't loop forever.",
          task: "Write a function called `flood` that takes in a grid of terrain numbers, a start row and column, and a new terrain value. Change the start cell and every connected cell (up/down/left/right) with the same original terrain to the new value. Return the grid.",
          examples: ["flood([[1, 1, 0],\n       [1, 0, 0],\n       [1, 1, 1]], 0, 0, 2)\n→ [[2, 2, 0],\n   [2, 0, 0],\n   [2, 2, 2]]"],
          hint: "If the new value equals the old value, return immediately. Otherwise recurse into in-bounds neighbours that still have the old value.",
          check: "assert flood([[1, 1, 0], [1, 0, 0], [1, 1, 1]], 0, 0, 2) == [[2, 2, 0], [2, 0, 0], [2, 2, 2]], f'Got {flood([[1, 1, 0], [1, 0, 0], [1, 1, 1]], 0, 0, 2)}'\nassert flood([[0, 0], [0, 0]], 1, 1, 0) == [[0, 0], [0, 0]], 'Flooding with the same value must not loop forever.'\nassert flood([[1, 0], [0, 1]], 0, 0, 5) == [[5, 0], [0, 1]], 'Diagonal sectors are not connected.'",
          solution: "def flood(grid, r, c, value):\n    old = grid[r][c]\n    if old == value:\n        return grid\n    rows = len(grid)\n    cols = len(grid[0])\n\n    def fill(r, c):\n        if r < 0 or r >= rows or c < 0 or c >= cols:\n            return\n        if grid[r][c] != old:\n            return\n        grid[r][c] = value\n        fill(r - 1, c)\n        fill(r + 1, c)\n        fill(r, c - 1)\n        fill(r, c + 1)\n\n    fill(r, c)\n    return grid" },
        { id: "jb16", title: "Count the hidden villages",
          say: "Land is 1, water is 0. Every time you find land you haven't visited, that's a new island village — flood it so you don't count it twice, and keep scanning.",
          task: "Write a function called `villages` that takes in a grid of 0s and 1s and returns how many islands there are. An island is a group of 1s connected up/down/left/right. You may modify the grid.",
          examples: ["villages([[1, 1, 0, 0],\n          [0, 1, 0, 1],\n          [0, 0, 0, 1],\n          [1, 0, 0, 0]]) → 3"],
          hint: "Loop over every cell. On a 1: count += 1, then sink the whole island (set its cells to 0 with a flood).",
          check: "assert villages([[1, 1, 0, 0], [0, 1, 0, 1], [0, 0, 0, 1], [1, 0, 0, 0]]) == 3, f'Got {villages([[1, 1, 0, 0], [0, 1, 0, 1], [0, 0, 0, 1], [1, 0, 0, 0]])}, expected 3.'\nassert villages([[0, 0], [0, 0]]) == 0\nassert villages([[1, 0, 1], [0, 1, 0], [1, 0, 1]]) == 5, 'Diagonals do not connect: 5 separate islands.'",
          solution: "def villages(grid):\n    rows = len(grid)\n    cols = len(grid[0])\n\n    def sink(r, c):\n        if r < 0 or r >= rows or c < 0 or c >= cols or grid[r][c] != 1:\n            return\n        grid[r][c] = 0\n        sink(r - 1, c)\n        sink(r + 1, c)\n        sink(r, c - 1)\n        sink(r, c + 1)\n\n    count = 0\n    for r in range(rows):\n        for c in range(cols):\n            if grid[r][c] == 1:\n                count += 1\n                sink(r, c)\n    return count" }
      ]},
      { id: "jb-dp", title: "Dynamic programming", kanji: "記", problems: [
        { id: "jb17", title: "Raid the Akatsuki hideouts",
          say: "A row of hideouts with ryō inside. Raid any you like, but never two next to each other or the alarm trips. At each hideout, the best haul so far is either skip it, or take it plus the best from two hideouts back.",
          task: "Write a function called `max_loot` that takes in a list of amounts (one per hideout) and returns the most you can take without raiding two adjacent hideouts.",
          examples: ["max_loot([1, 2, 3, 1]) → 4   (hideouts 1 and 3)", "max_loot([2, 7, 9, 3, 1]) → 12   (2 + 9 + 1)", "max_loot([]) → 0"],
          hint: "Keep two numbers: best including the previous hideout, and best excluding it. For each amount: new_include = exclude + amount; new_exclude = max(include, exclude).",
          check: "assert max_loot([1, 2, 3, 1]) == 4, f'Got {max_loot([1, 2, 3, 1])}, expected 4.'\nassert max_loot([2, 7, 9, 3, 1]) == 12, f'Got {max_loot([2, 7, 9, 3, 1])}, expected 12.'\nassert max_loot([]) == 0\nassert max_loot([5]) == 5",
          solution: "def max_loot(hideouts):\n    include = 0\n    exclude = 0\n    for amount in hideouts:\n        new_include = exclude + amount\n        new_exclude = max(include, exclude)\n        include = new_include\n        exclude = new_exclude\n    return max(include, exclude)" },
        { id: "jb18", title: "Routes through the forest",
          say: "A messenger hawk starts in the top-left of the Forest of Death and can only fly right or down. How many routes to the bottom-right? Every cell's count is the count from above plus the count from the left.",
          task: "Write a function called `routes` that takes in a number of rows and columns and returns how many distinct right/down paths lead from the top-left cell to the bottom-right cell.",
          examples: ["routes(2, 2) → 2", "routes(3, 7) → 28", "routes(1, 5) → 1"],
          hint: "Make a rows×cols table of 1s (the first row and column each have one path). Then for every other cell: dp[r][c] = dp[r-1][c] + dp[r][c-1].",
          check: "assert routes(2, 2) == 2\nassert routes(3, 7) == 28, f'routes(3, 7) returned {routes(3, 7)}'\nassert routes(1, 5) == 1\nassert routes(10, 10) == 48620, 'If this is slow, you are recomputing cells — use a table.'",
          solution: "def routes(rows, cols):\n    dp = [[1] * cols for _ in range(rows)]\n    for r in range(1, rows):\n        for c in range(1, cols):\n            dp[r][c] = dp[r - 1][c] + dp[r][c - 1]\n    return dp[rows - 1][cols - 1]" }
      ]}
    ]},

  /* ============================ A-RANK ============================ */
  { id: "A", rank: "A", title: "Combat Practice", short: "Combat", kanji: "戦",
    intro: "Combat practice! In a real fight you combine jutsu. Each of these needs two structures working together. The first question is always: which two, and which does what? Decide that before you type.",
    topics: [
      { id: "ja-all", title: "Combination jutsu", kanji: "合", problems: [
        { id: "ja1", title: "Most-used jutsu",
          say: "Hash map plus heap. Count how often each jutsu was cast in the battle, then use a heap to pull out the k most used.",
          task: "Write a function called `most_used` that takes in a list of jutsu names (one per cast) and a number k and returns the k jutsu cast most often, most frequent first. You can assume there are no ties for the k-th place.",
          examples: ["most_used(['Rasengan', 'Clone', 'Rasengan', 'Fireball', 'Rasengan', 'Clone'], 2) → ['Rasengan', 'Clone']", "most_used(['a', 'a', 'a', 'b', 'b', 'c'], 1) → ['a']"],
          hint: "Count into a dictionary. Push (-count, name) for each entry onto a heap; pop k times.",
          check: "assert 'heapq' in _src, 'Use a heap for the top k.'\nassert most_used(['Rasengan', 'Clone', 'Rasengan', 'Fireball', 'Rasengan', 'Clone'], 2) == ['Rasengan', 'Clone'], f'Got {most_used([\"Rasengan\", \"Clone\", \"Rasengan\", \"Fireball\", \"Rasengan\", \"Clone\"], 2)}'\nassert most_used(['a', 'a', 'a', 'b', 'b', 'c'], 1) == ['a']\nassert most_used(['Chidori'], 1) == ['Chidori']",
          solution: "import heapq\n\ndef most_used(casts, k):\n    count = {}\n    for name in casts:\n        count[name] = count.get(name, 0) + 1\n    heap = []\n    for name, n in count.items():\n        heapq.heappush(heap, (-n, name))\n    result = []\n    for _ in range(k):\n        result.append(heapq.heappop(heap)[1])\n    return result" },
        { id: "ja2", title: "Group the transformations",
          say: "Hash map with a clever key. Code words that are transformations of each other become identical when you sort their letters — so the sorted word is the key, and the value is the list of words that share it.",
          task: "Write a function called `group_transformations` that takes in a list of words and returns a list of groups, where each group is a list of words that are rearrangements of each other. Keep words in their original order within a group, and order the groups by the first appearance of each group.",
          examples: ["group_transformations(['eat', 'tea', 'tan', 'ate', 'nat', 'bat']) → [['eat', 'tea', 'ate'], ['tan', 'nat'], ['bat']]"],
          hint: "key = ''.join(sorted(word)). If the key isn't in the dictionary yet, start a list; append the word. Return list(groups.values()).",
          check: "assert group_transformations(['eat', 'tea', 'tan', 'ate', 'nat', 'bat']) == [['eat', 'tea', 'ate'], ['tan', 'nat'], ['bat']], f'Got {group_transformations([\"eat\", \"tea\", \"tan\", \"ate\", \"nat\", \"bat\"])}'\nassert group_transformations(['']) == [['']]\nassert group_transformations(['a']) == [['a']]",
          solution: "def group_transformations(words):\n    groups = {}\n    for w in words:\n        key = ''.join(sorted(w))\n        if key not in groups:\n            groups[key] = []\n        groups[key].append(w)\n    return list(groups.values())" },
        { id: "ja3", title: "Next stronger opponent",
          say: "Stack plus hash map. For each fighter in the tournament line, who is the next fighter to their right with higher chakra? A stack of 'still waiting for someone stronger' handles it in one pass; a dictionary remembers each answer so you can look up the ones you were asked about.",
          task: "Write a function called `next_stronger` that takes in two lists, `query` and `line`, where every value in `query` appears in `line` (all values distinct). For each query value, return the first value to its right in `line` that is greater, or -1 if there is none.",
          examples: ["next_stronger([4, 1, 2], [1, 3, 4, 2]) → [-1, 3, -1]", "next_stronger([2, 4], [1, 2, 3, 4]) → [3, -1]"],
          hint: "Walk line with a stack. While the stack's top is smaller than the current value, pop it and record current as its answer in a dictionary. Push the current value. Anything left on the stack gets -1.",
          check: "assert next_stronger([4, 1, 2], [1, 3, 4, 2]) == [-1, 3, -1], f'Got {next_stronger([4, 1, 2], [1, 3, 4, 2])}'\nassert next_stronger([2, 4], [1, 2, 3, 4]) == [3, -1]\nassert next_stronger([1], [1]) == [-1]",
          solution: "def next_stronger(query, line):\n    answer = {}\n    stack = []\n    for w in line:\n        while stack and stack[-1] < w:\n            answer[stack.pop()] = w\n        stack.append(w)\n    for w in stack:\n        answer[w] = -1\n    return [answer[q] for q in query]" },
        { id: "ja4", title: "Genjutsu loop",
          say: "Linked list plus set. If you're caught in a genjutsu, the chain of clones loops back on itself and walking it never ends. Remember every clone you've visited; if you see one twice, you're in the loop.",
          task: "Write a function called `in_genjutsu` that takes in the head of a linked list and returns True if following `.next` pointers ever revisits a node.",
          prelude: LIST,
          examples: ["h = build_list([1, 2, 3]); h.next.next.next = h.next   (3 points back to 2)\nin_genjutsu(h) → True", "in_genjutsu(build_list([1, 2, 3])) → False"],
          hint: "Put each node (the node itself, not its value) in a set as you walk. Values can repeat without a loop; nodes can't.",
          check: "h = build_list([1, 2, 3]); h.next.next.next = h.next\nassert in_genjutsu(h) is True, 'The last node points back to the second: that is a loop.'\nassert in_genjutsu(build_list([1, 2, 3])) is False\nassert in_genjutsu(build_list([1, 1, 1])) is False, 'Repeated values are not a loop — track nodes, not values.'\nassert in_genjutsu(None) is False",
          solution: "def in_genjutsu(head):\n    seen = set()\n    node = head\n    while node:\n        if node in seen:\n            return True\n        seen.add(node)\n        node = node.next\n    return False" },
        { id: "ja5", title: "Generation by generation",
          say: "Tree plus queue. To read a clan tree one generation at a time, put the founder in a queue; then repeatedly take out everyone currently in the queue (that's one generation) and add their children.",
          task: "Write a function called `generations_list` that takes in the root of a tree and returns a list of lists, one inner list per level from top to bottom, each holding that level's values left to right.",
          prelude: TREE,
          examples: ["generations_list(build_tree([3, 9, 20, None, None, 15, 7])) → [[3], [9, 20], [15, 7]]", "generations_list(None) → []"],
          hint: "q = deque([root]). While q: n = len(q); take n nodes with popleft, collect their values into one list, and append their children.",
          check: "assert 'deque' in _src, 'Use a deque as the queue.'\nassert generations_list(build_tree([3, 9, 20, None, None, 15, 7])) == [[3], [9, 20], [15, 7]], f'Got {generations_list(build_tree([3, 9, 20, None, None, 15, 7]))}'\nassert generations_list(None) == []\nassert generations_list(build_tree([1, 2, None, 3])) == [[1], [2], [3]]",
          solution: "from collections import deque\n\ndef generations_list(root):\n    if root is None:\n        return []\n    result = []\n    q = deque([root])\n    while q:\n        level = []\n        for _ in range(len(q)):\n            node = q.popleft()\n            level.append(node.val)\n            if node.left:\n                q.append(node.left)\n            if node.right:\n                q.append(node.right)\n        result.append(level)\n    return result" },
        { id: "ja6", title: "Can the messenger get through?",
          say: "Graph plus queue plus set. Breadth-first search: start at the home village, visit neighbouring villages, and keep a set of where you've been so you never go in circles.",
          task: "Write a function called `can_reach` that takes in a number of villages n (numbered 0 to n-1), a list of roads (each a two-element list meaning the two villages are connected both ways), a start village and a goal village. Return True if a messenger can travel from start to goal.",
          examples: ["can_reach(3, [[0, 1], [1, 2], [2, 0]], 0, 2) → True", "can_reach(6, [[0, 1], [0, 2], [3, 5], [5, 4], [4, 3]], 0, 5) → False"],
          hint: "Build a dictionary from village to its neighbours (add both directions). BFS with a deque and a visited set; return True the moment you pop the goal.",
          check: "assert can_reach(3, [[0, 1], [1, 2], [2, 0]], 0, 2) is True\nassert can_reach(6, [[0, 1], [0, 2], [3, 5], [5, 4], [4, 3]], 0, 5) is False, 'Villages 0 and 5 are in different regions.'\nassert can_reach(1, [], 0, 0) is True, 'Start equals goal: True.'\nassert can_reach(4, [[0, 1], [2, 3]], 1, 0) is True, 'Roads go both ways.'",
          solution: "from collections import deque\n\ndef can_reach(n, roads, start, goal):\n    graph = {i: [] for i in range(n)}\n    for a, b in roads:\n        graph[a].append(b)\n        graph[b].append(a)\n    seen = {start}\n    q = deque([start])\n    while q:\n        village = q.popleft()\n        if village == goal:\n            return True\n        for nxt in graph[village]:\n            if nxt not in seen:\n                seen.add(nxt)\n                q.append(nxt)\n    return False" },
        { id: "ja7", title: "Ramen line from two piles",
          say: "Two stacks can act as a queue. Push onto the first pile. To serve, if the second pile is empty, pour everything from the first into it — that reverses the order, so its top is now the oldest customer.",
          task: "Make a class called `RamenLine` using two Python lists as stacks, with methods `join(x)` (customer joins), `serve()` (removes and returns the customer who's been waiting longest) and `peek()` (returns that customer without removing them). Don't use deque or list.pop(0) / insert(0, …).",
          examples: ["q = RamenLine()\nq.join('Naruto'); q.join('Choji'); q.join('Kiba')\nq.serve() → 'Naruto'\nq.join('Lee')\nq.peek() → 'Choji'\nq.serve() → 'Choji'\nq.serve() → 'Kiba'\nq.serve() → 'Lee'"],
          check: "assert 'deque' not in _src and 'pop(0)' not in _src and 'insert(0' not in _src, 'Only two stacks: append and pop() from the end.'\nq = RamenLine()\nq.join('Naruto'); q.join('Choji'); q.join('Kiba')\nassert q.serve() == 'Naruto', 'The first to join should be served first.'\nq.join('Lee')\nassert q.peek() == 'Choji' and q.serve() == 'Choji' and q.serve() == 'Kiba' and q.serve() == 'Lee', 'Customers who join after a serve must still come out in order.'",
          solution: "class RamenLine:\n    def __init__(self):\n        self.inbox = []\n        self.outbox = []\n\n    def _shift(self):\n        if not self.outbox:\n            while self.inbox:\n                self.outbox.append(self.inbox.pop())\n\n    def join(self, x):\n        self.inbox.append(x)\n\n    def serve(self):\n        self._shift()\n        return self.outbox.pop()\n\n    def peek(self):\n        self._shift()\n        return self.outbox[-1]" },
        { id: "ja8", title: "Chakra pair in the clan",
          say: "Tree plus set. Walk every member of the clan; for each chakra value, check whether target minus value has already been seen. Any traversal order works.",
          task: "Write a function called `clan_pair` that takes in the root of a tree and a target, and returns True if two different nodes have values that add up to the target.",
          prelude: TREE,
          examples: ["clan_pair(build_tree([5, 3, 6, 2, 4, None, 7]), 9) → True   (2 + 7, or 3 + 6)", "clan_pair(build_tree([5, 3, 6, 2, 4, None, 7]), 28) → False", "clan_pair(build_tree([4]), 8) → False   (one node can't pair with itself)"],
          hint: "Recursive walk carrying a set. At each node: if target - node.val in seen, return True; add node.val; recurse into children.",
          check: "t = build_tree([5, 3, 6, 2, 4, None, 7])\nassert clan_pair(t, 9) is True\nassert clan_pair(t, 28) is False\nassert clan_pair(build_tree([4]), 8) is False, 'A single node cannot pair with itself.'\nassert clan_pair(None, 0) is False",
          solution: "def clan_pair(root, target):\n    seen = set()\n\n    def walk(node):\n        if node is None:\n            return False\n        if target - node.val in seen:\n            return True\n        seen.add(node.val)\n        return walk(node.left) or walk(node.right)\n\n    return walk(root)" },
        { id: "ja9", title: "Escape the Forest of Death",
          say: "Grid plus queue. Breadth-first search finds the shortest way out: explore all sectors 1 step away, then 2, then 3. The first time you reach the tower, that's the shortest route.",
          task: "Write a function called `shortest_escape` that takes in a grid (0 = clear, 1 = wall), a start sector and the tower sector (each `(row, col)`), and returns the fewest up/down/left/right moves from start to the tower, or -1 if it can't be reached.",
          examples: ["forest = [[0, 0, 0],\n          [1, 1, 0],\n          [0, 0, 0]]\nshortest_escape(forest, (0, 0), (2, 0)) → 6", "shortest_escape([[0, 1], [1, 0]], (0, 0), (1, 1)) → -1"],
          hint: "Queue of (row, col, distance). Visited set. Pop; if it's the tower return the distance; otherwise push in-bounds, clear, unvisited neighbours with distance + 1.",
          check: "assert 'deque' in _src, 'Use a deque for breadth-first search.'\ng = [[0, 0, 0], [1, 1, 0], [0, 0, 0]]\nassert shortest_escape(g, (0, 0), (2, 0)) == 6, f'Got {shortest_escape(g, (0, 0), (2, 0))}, expected 6 (around the wall).'\nassert shortest_escape([[0, 1], [1, 0]], (0, 0), (1, 1)) == -1, 'Blocked by walls: -1.'\nassert shortest_escape([[0]], (0, 0), (0, 0)) == 0",
          solution: "from collections import deque\n\ndef shortest_escape(grid, start, tower):\n    rows = len(grid)\n    cols = len(grid[0])\n    q = deque([(start[0], start[1], 0)])\n    seen = {start}\n    while q:\n        r, c, dist = q.popleft()\n        if (r, c) == tower:\n            return dist\n        for dr, dc in [(-1, 0), (1, 0), (0, -1), (0, 1)]:\n            nr = r + dr\n            nc = c + dc\n            if 0 <= nr < rows and 0 <= nc < cols and grid[nr][nc] == 0 and (nr, nc) not in seen:\n                seen.add((nr, nc))\n                q.append((nr, nc, dist + 1))\n    return -1" },
        { id: "ja10", title: "Exact change at Ichiraku",
          say: "Dynamic programming with a table. Given the coin values in your pouch, what's the fewest coins that pay for the ramen exactly? For every amount from 1 up, the best is 1 plus the best for (amount minus some coin).",
          task: "Write a function called `fewest_coins` that takes in a list of coin values and a price and returns the fewest coins needed to pay exactly that price, or -1 if it can't be done. You have unlimited coins of each value.",
          examples: ["fewest_coins([1, 2, 5], 11) → 3   (5 + 5 + 1)", "fewest_coins([2], 3) → -1", "fewest_coins([1], 0) → 0"],
          hint: "dp = [big] * (price + 1); dp[0] = 0. For a in 1..price, for each coin ≤ a: dp[a] = min(dp[a], dp[a - coin] + 1). Return dp[price] unless it's still big.",
          check: "assert fewest_coins([1, 2, 5], 11) == 3, f'Got {fewest_coins([1, 2, 5], 11)}, expected 3.'\nassert fewest_coins([2], 3) == -1, 'Odd prices cannot be paid with 2s.'\nassert fewest_coins([1], 0) == 0\nassert fewest_coins([1, 3, 4], 6) == 2, 'Greedy (4 + 1 + 1) is wrong here; the answer is 3 + 3.'",
          solution: "def fewest_coins(coins, price):\n    big = price + 1\n    dp = [big] * (price + 1)\n    dp[0] = 0\n    for a in range(1, price + 1):\n        for coin in coins:\n            if coin <= a:\n                dp[a] = min(dp[a], dp[a - coin] + 1)\n    if dp[price] == big:\n        return -1\n    return dp[price]" }
      ]}
    ]}
  ];
})();
