/* Training Grounds curriculum, taught by Rock Lee. Eight jutsu (data structures):
   hash maps & sets, linked lists, stacks, queues, heaps, trees, graphs & grids, dynamic programming.
     D  Basic Forms   — learn each structure's everyday operations in Python
     C  Sparring      — small problems, one structure each
     B  Chunin Trials — LeetCode-easy problems, one structure each
     A  Combination   — NeetCode-easy problems that mix structures
   Same problem format as lessons.js. `prelude` is code that runs before the student's (and is shown to them). */
(function () {
  var LIST = "class ListNode:\n    def __init__(self, val, next=None):\n        self.val = val\n        self.next = next\n\ndef build_list(values):\n    head = None\n    for v in reversed(values):\n        head = ListNode(v, head)\n    return head\n\ndef to_list(head):\n    out = []\n    while head:\n        out.append(head.val)\n        head = head.next\n    return out\n";
  var TREE = "class TreeNode:\n    def __init__(self, val, left=None, right=None):\n        self.val = val\n        self.left = left\n        self.right = right\n\ndef build_tree(values):\n    # level order, None for a missing child, e.g. [1, 2, 3, None, 4]\n    if not values or values[0] is None:\n        return None\n    nodes = [TreeNode(v) if v is not None else None for v in values]\n    kids = nodes[1:][::-1]\n    for node in nodes:\n        if node:\n            if kids: node.left = kids.pop()\n            if kids: node.right = kids.pop()\n    return nodes[0]\n";

  window.JUTSU = [
  /* ============================ D-RANK ============================ */
  { id: "D", rank: "D", title: "Basic Forms", short: "Forms", kanji: "型",
    intro: "Every jutsu starts with the basic form! Here you learn what each structure does in Python and the handful of operations you'll use every day. Drill them until your fingers know them.",
    topics: [
      { id: "jd-hash", title: "Hash maps & sets", kanji: "辞", intro: "A dictionary maps keys to values and finds any key instantly. A set is a bag of unique keys with no values.", problems: [
        { id: "jd1", title: "Rank registry",
          say: "A dictionary is like the village registry: look up a name, get a rank — instantly, no matter how big the book.",
          task: "Make a dictionary called `ranks` where `'Naruto'` maps to `'Genin'`, `'Kakashi'` to `'Jonin'` and `'Tsunade'` to `'Kage'`. Print Kakashi's rank. Then add `'Sakura'` with rank `'Genin'` and print how many entries the dictionary has.",
          examples: ["It should print:\nJonin\n4"],
          check: "assert 'ranks' in dir() and isinstance(ranks, dict), 'Make a dictionary called ranks.'\nassert ranks.get('Kakashi') == 'Jonin', 'ranks[\"Kakashi\"] should be Jonin.'\nassert ranks.get('Sakura') == 'Genin', 'Add Sakura with ranks[\"Sakura\"] = \"Genin\".'\nassert len(ranks) == 4\nlines = [l.strip() for l in _out.strip().splitlines()]\nassert lines == ['Jonin', '4'], f'Got {lines}'",
          solution: "ranks = {'Naruto': 'Genin', 'Kakashi': 'Jonin', 'Tsunade': 'Kage'}\nprint(ranks['Kakashi'])\nranks['Sakura'] = 'Genin'\nprint(len(ranks))" },
        { id: "jd2", title: "Count the weapons",
          say: "The most common dictionary move: counting. .get(key, 0) gives you 0 the first time you see something, instead of an error.",
          task: "Count how many times each word appears in `words`, storing the counts in a dictionary called `count`. Then print the count for `'kunai'`.",
          starter: "words = ['kunai', 'shuriken', 'kunai', 'scroll', 'kunai', 'shuriken']\n",
          examples: ["It should print:\n3", "count ends up as {'kunai': 3, 'shuriken': 2, 'scroll': 1}"],
          hint: "count[w] = count.get(w, 0) + 1 inside a loop.",
          check: "assert 'count' in dir() and isinstance(count, dict), 'Make a dictionary called count.'\nassert count == {'kunai': 3, 'shuriken': 2, 'scroll': 1}, f'count is {count}'\nassert _out.strip() == '3'",
          solution: "words = ['kunai', 'shuriken', 'kunai', 'scroll', 'kunai', 'shuriken']\ncount = {}\nfor w in words:\n    count[w] = count.get(w, 0) + 1\nprint(count['kunai'])" },
        { id: "jd3", title: "Keys, values, items",
          say: "You can walk a dictionary three ways: its keys, its values, or both at once with .items().",
          task: "Loop over `pay` with `.items()` and print each line as `<name>: <amount>`. Then print the total of all the values.",
          starter: "pay = {'Naruto': 5000, 'Sakura': 7000, 'Sai': 3000}\n",
          examples: ["It should print:\nNaruto: 5000\nSakura: 7000\nSai: 3000\n15000"],
          check: "assert '.items()' in _src, 'Loop with for name, amount in pay.items().'\nlines = [l.strip() for l in _out.strip().splitlines()]\nassert lines == ['Naruto: 5000', 'Sakura: 7000', 'Sai: 3000', '15000'], f'Got {lines}'",
          solution: "pay = {'Naruto': 5000, 'Sakura': 7000, 'Sai': 3000}\nfor name, amount in pay.items():\n    print(name + ': ' + str(amount))\nprint(sum(pay.values()))" },
        { id: "jd4", title: "Sets",
          say: "A set throws away duplicates and answers 'is this in here?' instantly.",
          task: "Turn `names` into a set called `unique`. Print how many unique names there are, then print whether `'Sai'` is in the set, then add `'Ino'` and print the length again.",
          starter: "names = ['Naruto', 'Sakura', 'Naruto', 'Sai', 'Sakura', 'Naruto']\n",
          examples: ["It should print:\n3\nTrue\n4"],
          check: "assert 'unique' in dir() and isinstance(unique, set), 'Make a set called unique with set(names).'\nassert unique == {'Naruto', 'Sakura', 'Sai', 'Ino'}, f'unique is {unique}'\nlines = [l.strip() for l in _out.strip().splitlines()]\nassert lines == ['3', 'True', '4'], f'Got {lines}'",
          solution: "names = ['Naruto', 'Sakura', 'Naruto', 'Sai', 'Sakura', 'Naruto']\nunique = set(names)\nprint(len(unique))\nprint('Sai' in unique)\nunique.add('Ino')\nprint(len(unique))" }
      ]},
      { id: "jd-linked", title: "Linked lists", kanji: "鎖", intro: "A linked list is a chain of nodes. Each node holds a value and a pointer to the next node. You only ever hold the head.", problems: [
        { id: "jd5", title: "Forge a chain",
          say: "Build three nodes by hand and link them. Then walk the chain with a while loop until you fall off the end.",
          task: "Using the provided `ListNode` class, make a chain `head` with the values 1, 2, 3 in that order by creating nodes and setting `.next`. Then walk it with a while loop and print each value.",
          prelude: LIST,
          examples: ["It should print:\n1\n2\n3"],
          check: "assert 'head' in dir() and isinstance(head, ListNode), 'Make head a ListNode.'\nassert to_list(head) == [1, 2, 3], f'The chain holds {to_list(head)}, expected [1, 2, 3].'\nassert 'build_list' not in _src, 'Build the nodes yourself this time.'\nlines = [l.strip() for l in _out.strip().splitlines()]\nassert lines == ['1', '2', '3'], f'Got {lines}'",
          solution: "head = ListNode(1)\nhead.next = ListNode(2)\nhead.next.next = ListNode(3)\n\nnode = head\nwhile node:\n    print(node.val)\n    node = node.next" },
        { id: "jd6", title: "Count the links",
          say: "You can't call len on a chain. Walk it and count.",
          task: "Write a function called `length` that takes in the head of a linked list and returns how many nodes it has (0 for an empty list, which is `None`).",
          prelude: LIST,
          examples: ["length(build_list([5, 7, 9])) → 3", "length(None) → 0"],
          check: "assert length(build_list([5, 7, 9])) == 3, f'length of [5, 7, 9] came back {length(build_list([5, 7, 9]))}'\nassert length(None) == 0, 'An empty list (None) has length 0.'\nassert length(build_list([1])) == 1",
          solution: "def length(head):\n    count = 0\n    node = head\n    while node:\n        count += 1\n        node = node.next\n    return count" },
        { id: "jd7", title: "Add a link to the end",
          say: "To append, walk to the last node (the one whose .next is None) and hang the new node there. Watch out for the empty list.",
          task: "Write a function called `append` that takes in the head of a linked list and a value, adds a new node with that value to the end, and returns the head. If the list is empty (`None`), the new node becomes the head.",
          prelude: LIST,
          examples: ["to_list(append(build_list([1, 2]), 3)) → [1, 2, 3]", "to_list(append(None, 7)) → [7]"],
          check: "assert to_list(append(build_list([1, 2]), 3)) == [1, 2, 3], f'Got {to_list(append(build_list([1, 2]), 3))}'\nassert to_list(append(None, 7)) == [7], 'Appending to an empty list should return a one-node list.'",
          solution: "def append(head, val):\n    new = ListNode(val)\n    if head is None:\n        return new\n    node = head\n    while node.next:\n        node = node.next\n    node.next = new\n    return head" }
      ]},
      { id: "jd-stack", title: "Stacks", kanji: "積", intro: "A stack is last-in, first-out, like a pile of scrolls. In Python a plain list is a stack: append pushes, pop takes the top.", problems: [
        { id: "jd8", title: "Push and pop",
          say: "Push three scrolls onto a pile, then take two off. The last one on is the first one off.",
          task: "Make an empty list called `stack`. Push `'a'`, `'b'`, `'c'` with append. Pop twice, printing each popped value. Then print the stack.",
          examples: ["It should print:\nc\nb\n['a']"],
          check: "assert '.append(' in _src and '.pop()' in _src, 'Use append to push and pop() to take the top.'\nassert stack == ['a'], f'stack is {stack}'\nlines = [l.strip() for l in _out.strip().splitlines()]\nassert lines == ['c', 'b', \"['a']\"], f'Got {lines}'",
          solution: "stack = []\nstack.append('a')\nstack.append('b')\nstack.append('c')\nprint(stack.pop())\nprint(stack.pop())\nprint(stack)" },
        { id: "jd9", title: "Peek and empty",
          say: "Two things you check constantly: what's on top (without removing it) and whether the stack is empty.",
          task: "Write a function called `top` that returns the top item of a stack without removing it, or `None` if the stack is empty. Write a function called `is_empty` that returns True if the stack is empty.",
          examples: ["top([1, 2, 3]) → 3", "top([]) → None", "is_empty([]) → True"],
          check: "assert top([1, 2, 3]) == 3, 'top([1, 2, 3]) should be 3 — the last item.'\ns = [1, 2, 3]; top(s); assert s == [1, 2, 3], 'top must not remove the item.'\nassert top([]) is None, 'top of an empty stack is None.'\nassert is_empty([]) is True and is_empty([1]) is False",
          solution: "def top(stack):\n    if len(stack) == 0:\n        return None\n    return stack[-1]\n\ndef is_empty(stack):\n    return len(stack) == 0" }
      ]},
      { id: "jd-queue", title: "Queues", kanml: "列", kanji: "列", intro: "A queue is first-in, first-out, like a line at Ichiraku. Use collections.deque: append at the back, popleft from the front.", problems: [
        { id: "jd10", title: "Join the line",
          say: "A list is slow at removing from the front. deque does it instantly. Import it, then append and popleft.",
          task: "Import `deque` from `collections`. Make a deque called `line` and add Naruto, Sasuke, Sakura in that order. Remove the person at the front with `popleft` and print them. Then print the deque's length.",
          examples: ["It should print:\nNaruto\n2"],
          check: "assert 'from collections import deque' in _src, 'Start with: from collections import deque'\nassert '.popleft()' in _src, 'Use popleft() to take from the front.'\nassert list(line) == ['Sasuke', 'Sakura'], f'line holds {list(line)}'\nlines = [l.strip() for l in _out.strip().splitlines()]\nassert lines == ['Naruto', '2'], f'Got {lines}'",
          solution: "from collections import deque\nline = deque()\nline.append('Naruto')\nline.append('Sasuke')\nline.append('Sakura')\nprint(line.popleft())\nprint(len(line))" },
        { id: "jd11", title: "Work through the queue",
          say: "The classic queue loop: while there's anything in it, take the front and deal with it.",
          task: "Write a function called `process` that takes in a list of mission names, puts them in a deque in order, and then takes them out one at a time from the front, printing `Done: <name>` for each. It should return how many it processed.",
          examples: ["process(['escort', 'patrol']) prints:\nDone: escort\nDone: patrol\nand returns 2"],
          check: "assert 'deque' in _src and '.popleft()' in _src, 'Use a deque and popleft.'\nimport io, sys\n_buf = io.StringIO(); _old = sys.stdout; sys.stdout = _buf\nn = process(['escort', 'patrol', 'rescue'])\nsys.stdout = _old\nassert n == 3, f'process returned {n}, expected 3.'\nlines = [l.strip() for l in _buf.getvalue().strip().splitlines()]\nassert lines == ['Done: escort', 'Done: patrol', 'Done: rescue'], f'It printed {lines}'",
          solution: "from collections import deque\n\ndef process(missions):\n    q = deque(missions)\n    count = 0\n    while q:\n        name = q.popleft()\n        print('Done: ' + name)\n        count += 1\n    return count" }
      ]},
      { id: "jd-heap", title: "Heaps", kanji: "峰", intro: "A heap always keeps the smallest item at the front, no matter what order you add things. Python's heapq works on a plain list.", problems: [
        { id: "jd12", title: "Smallest first",
          say: "Push numbers in any order; heappop always hands you the smallest. heap[0] lets you peek at it.",
          task: "Import `heapq`. Make an empty list called `heap` and push 5, 1, 8, 3 onto it with `heapq.heappush`. Pop one value with `heapq.heappop` and print it. Then print `heap[0]` (the new smallest, without removing it).",
          examples: ["It should print:\n1\n3"],
          check: "assert 'import heapq' in _src and 'heappush' in _src and 'heappop' in _src, 'Use heapq.heappush and heapq.heappop.'\nlines = [l.strip() for l in _out.strip().splitlines()]\nassert lines == ['1', '3'], f'Got {lines}'\nassert sorted(heap) == [3, 5, 8]",
          solution: "import heapq\nheap = []\nheapq.heappush(heap, 5)\nheapq.heappush(heap, 1)\nheapq.heappush(heap, 8)\nheapq.heappush(heap, 3)\nprint(heapq.heappop(heap))\nprint(heap[0])" },
        { id: "jd13", title: "Largest first",
          say: "heapq only does smallest-first. The trick for largest-first: push the negative of each number, and negate again when you pop.",
          task: "Write a function called `largest_two` that takes in a list of scores and returns the two largest, biggest first, using a heap of negated values.",
          examples: ["largest_two([40, 95, 60, 25, 80]) → [95, 80]"],
          hint: "Push -score for each score. heappop gives the most negative, i.e. the largest original. Negate it back.",
          check: "assert 'heapq' in _src, 'Use heapq.'\nassert '-' in _src, 'Negate the values so the largest comes out first.'\nassert largest_two([40, 95, 60, 25, 80]) == [95, 80], f'Got {largest_two([40, 95, 60, 25, 80])}'\nassert largest_two([3, 1, 2]) == [3, 2]",
          solution: "import heapq\n\ndef largest_two(scores):\n    heap = []\n    for s in scores:\n        heapq.heappush(heap, -s)\n    first = -heapq.heappop(heap)\n    second = -heapq.heappop(heap)\n    return [first, second]" }
      ]},
      { id: "jd-tree", title: "Trees", kanji: "樹", intro: "A binary tree node has a value and up to two children, left and right. Most tree code is a function that calls itself on each child.", problems: [
        { id: "jd14", title: "Plant a tree",
          say: "Build the smallest useful tree: a root with two children. Then read the children back.",
          task: "Using the provided `TreeNode`, make a tree called `root` with value 1, a left child with value 2 and a right child with value 3. Print the left child's value, then the right child's value.",
          prelude: TREE,
          examples: ["It should print:\n2\n3"],
          check: "assert 'root' in dir() and isinstance(root, TreeNode), 'Make root a TreeNode.'\nassert root.val == 1 and root.left and root.left.val == 2 and root.right and root.right.val == 3, 'root should be 1 with left 2 and right 3.'\nlines = [l.strip() for l in _out.strip().splitlines()]\nassert lines == ['2', '3'], f'Got {lines}'",
          solution: "root = TreeNode(1)\nroot.left = TreeNode(2)\nroot.right = TreeNode(3)\nprint(root.left.val)\nprint(root.right.val)" },
        { id: "jd15", title: "Sum of a tree",
          say: "Here's the pattern you'll use for almost every tree problem: if the node is None, return the base case; otherwise combine the node with the answers for its left and right subtrees.",
          task: "Write a function called `tree_sum` that takes in the root of a tree and returns the sum of all its values. An empty tree (`None`) sums to 0.",
          prelude: TREE,
          examples: ["tree_sum(build_tree([1, 2, 3])) → 6", "tree_sum(build_tree([5, None, 7])) → 12", "tree_sum(None) → 0"],
          hint: "return node.val + tree_sum(node.left) + tree_sum(node.right), after handling None.",
          check: "assert tree_sum(None) == 0, 'None should sum to 0.'\nassert tree_sum(build_tree([1, 2, 3])) == 6, f'Got {tree_sum(build_tree([1, 2, 3]))} for [1, 2, 3]'\nassert tree_sum(build_tree([5, None, 7])) == 12\nassert tree_sum(build_tree([1, 2, 3, 4, 5, 6, 7])) == 28",
          solution: "def tree_sum(node):\n    if node is None:\n        return 0\n    return node.val + tree_sum(node.left) + tree_sum(node.right)" }
      ]},
      { id: "jd-graph", title: "Graphs & grids", kanji: "網", intro: "A graph is nodes and the connections between them — usually a dictionary from each node to its neighbours. A grid is a list of rows, and each cell's neighbours are up, down, left and right.", problems: [
        { id: "jd16", title: "Village roads",
          say: "The simplest graph in Python: a dictionary where each place maps to the list of places you can walk to from it.",
          task: "Make a dictionary called `roads` describing these connections: Gate connects to Market and Academy; Market connects to Gate and Tower; Academy connects to Gate; Tower connects to Market. Print the neighbours of Gate, then print how many places there are.",
          examples: ["It should print:\n['Market', 'Academy']\n4"],
          check: "assert 'roads' in dir() and isinstance(roads, dict), 'Make a dictionary called roads.'\nassert roads.get('Gate') == ['Market', 'Academy'], f'roads[\"Gate\"] is {roads.get(\"Gate\")}'\nassert roads.get('Tower') == ['Market'] and len(roads) == 4, 'Check all four places and their neighbours.'\nlines = [l.strip() for l in _out.strip().splitlines()]\nassert lines == [\"['Market', 'Academy']\", '4'], f'Got {lines}'",
          solution: "roads = {\n    'Gate': ['Market', 'Academy'],\n    'Market': ['Gate', 'Tower'],\n    'Academy': ['Gate'],\n    'Tower': ['Market'],\n}\nprint(roads['Gate'])\nprint(len(roads))" },
        { id: "jd17", title: "Reading a grid",
          say: "A grid is a list of rows. grid[r][c] is row r, column c. Rows and columns both start at 0.",
          task: "Print the value at row 1, column 2 of `grid`. Then print the number of rows, then the number of columns. Finally print the sum of row 0.",
          starter: "grid = [\n    [1, 2, 3],\n    [4, 5, 6],\n    [7, 8, 9],\n    [10, 11, 12],\n]\n",
          examples: ["It should print:\n6\n4\n3\n6"],
          check: "lines = [l.strip() for l in _out.strip().splitlines()]\nassert lines == ['6', '4', '3', '6'], f'Got {lines}. Rows = len(grid), columns = len(grid[0]).'",
          solution: "grid = [\n    [1, 2, 3],\n    [4, 5, 6],\n    [7, 8, 9],\n    [10, 11, 12],\n]\nprint(grid[1][2])\nprint(len(grid))\nprint(len(grid[0]))\nprint(sum(grid[0]))" },
        { id: "jd18", title: "Neighbours of a cell",
          say: "Every grid problem needs this: given a cell, which of its four neighbours are actually inside the grid?",
          task: "Write a function called `neighbours` that takes in the number of rows, the number of columns, and a cell `(r, c)`, and returns a list of the in-bounds neighbouring cells as `(row, col)` tuples, in the order up, down, left, right.",
          examples: ["neighbours(3, 3, 1, 1) → [(0, 1), (2, 1), (1, 0), (1, 2)]", "neighbours(3, 3, 0, 0) → [(1, 0), (0, 1)]   (up and left are off the grid)"],
          check: "assert neighbours(3, 3, 1, 1) == [(0, 1), (2, 1), (1, 0), (1, 2)], f'Got {neighbours(3, 3, 1, 1)}'\nassert neighbours(3, 3, 0, 0) == [(1, 0), (0, 1)], f'Corner: got {neighbours(3, 3, 0, 0)}, expected [(1, 0), (0, 1)]'\nassert neighbours(2, 2, 1, 1) == [(0, 1), (1, 0)]",
          solution: "def neighbours(rows, cols, r, c):\n    result = []\n    for dr, dc in [(-1, 0), (1, 0), (0, -1), (0, 1)]:\n        nr = r + dr\n        nc = c + dc\n        if 0 <= nr < rows and 0 <= nc < cols:\n            result.append((nr, nc))\n    return result" }
      ]},
      { id: "jd-dp", title: "Dynamic programming", kanji: "記", intro: "Dynamic programming is remembering answers so you never solve the same sub-problem twice. Two forms: a memo dictionary on a recursive function, or a table you fill from the bottom up.", problems: [
        { id: "jd19", title: "Remember the answer",
          say: "Naive fib(35) makes tens of millions of calls. With a memo dictionary it makes 35. Write it both ways in your head — then write the fast one.",
          task: "Write a function called `fib` that returns the n-th Fibonacci number (fib(0) = 0, fib(1) = 1, each number is the sum of the two before). Use a dictionary called `memo` so each n is only computed once.",
          examples: ["fib(10) → 55", "fib(50) → 12586269025"],
          hint: "If n is in memo, return memo[n]. Otherwise compute it, store it in memo[n], and return it.",
          check: "assert 'memo' in _src, 'Use a dictionary called memo.'\nassert fib(10) == 55, f'fib(10) returned {fib(10)}'\nassert fib(50) == 12586269025, 'fib(50) should be 12586269025 — if this is slow or crashes, the memo is not being used.'",
          solution: "memo = {}\n\ndef fib(n):\n    if n < 2:\n        return n\n    if n in memo:\n        return memo[n]\n    memo[n] = fib(n - 1) + fib(n - 2)\n    return memo[n]" },
        { id: "jd20", title: "Fill the table",
          say: "The other form: no recursion at all. Make a list, fill the first entries by hand, then fill each next entry from the ones before it.",
          task: "Write a function called `fib_table` that returns the n-th Fibonacci number by building a list `dp` of length n + 1, where `dp[0] = 0`, `dp[1] = 1`, and each later `dp[i] = dp[i-1] + dp[i-2]`. Return `dp[n]`.",
          examples: ["fib_table(10) → 55", "fib_table(1) → 1"],
          check: "assert 'dp' in _src, 'Build a list called dp.'\nassert 'fib_table(' not in _src.replace('def fib_table(', ''), 'No recursion this time — fill the table with a loop.'\nassert fib_table(10) == 55, f'fib_table(10) returned {fib_table(10)}'\nassert fib_table(1) == 1 and fib_table(0) == 0\nassert fib_table(50) == 12586269025",
          solution: "def fib_table(n):\n    if n < 2:\n        return n\n    dp = [0] * (n + 1)\n    dp[1] = 1\n    for i in range(2, n + 1):\n        dp[i] = dp[i - 1] + dp[i - 2]\n    return dp[n]" }
      ]}
    ]},

  /* ============================ C-RANK ============================ */
  { id: "C", rank: "C", title: "Sparring", short: "Sparring", kanji: "稽",
    intro: "Now we spar! Small problems, one structure at a time. The structure is the obvious tool — the work is applying it cleanly.",
    topics: [
      { id: "jc-hash", title: "Hash maps & sets", kanji: "辞", problems: [
        { id: "jc1", title: "First repeated name",
          say: "Walk the list once. A set remembers who you've seen.",
          task: "Write a function called `first_repeat` that takes in a list of names and returns the first name that appears for the second time. Return `None` if nobody repeats.",
          examples: ["first_repeat(['Naruto', 'Sakura', 'Sai', 'Sakura', 'Naruto']) → 'Sakura'", "first_repeat(['Naruto', 'Sakura']) → None"],
          check: "assert first_repeat(['Naruto', 'Sakura', 'Sai', 'Sakura', 'Naruto']) == 'Sakura', f'Got {first_repeat([\"Naruto\", \"Sakura\", \"Sai\", \"Sakura\", \"Naruto\"])!r} — Sakura repeats before Naruto does.'\nassert first_repeat(['Naruto', 'Sakura']) is None\nassert first_repeat([]) is None",
          solution: "def first_repeat(names):\n    seen = set()\n    for n in names:\n        if n in seen:\n            return n\n        seen.add(n)\n    return None" },
        { id: "jc2", title: "Clan sizes",
          say: "Group and count. Each clan is a key; the count is the value.",
          task: "Write a function called `clan_sizes` that takes in a list of clan names (one per shinobi) and returns a dictionary from clan to how many shinobi are in it.",
          examples: ["clan_sizes(['Uchiha', 'Nara', 'Uchiha', 'Hyuga', 'Nara', 'Uchiha']) → {'Uchiha': 3, 'Nara': 2, 'Hyuga': 1}"],
          check: "assert clan_sizes(['Uchiha', 'Nara', 'Uchiha', 'Hyuga', 'Nara', 'Uchiha']) == {'Uchiha': 3, 'Nara': 2, 'Hyuga': 1}, f'Got {clan_sizes([\"Uchiha\", \"Nara\", \"Uchiha\", \"Hyuga\", \"Nara\", \"Uchiha\"])}'\nassert clan_sizes([]) == {}",
          solution: "def clan_sizes(clans):\n    sizes = {}\n    for c in clans:\n        sizes[c] = sizes.get(c, 0) + 1\n    return sizes" },
        { id: "jc3", title: "Who's on both teams?",
          say: "Sets have operators for exactly this: & for both, | for either, - for in one but not the other.",
          task: "Write a function called `on_both` that takes in two lists of names and returns a sorted list of the names that appear in both.",
          examples: ["on_both(['Naruto', 'Sakura', 'Sai'], ['Sai', 'Ino', 'Naruto']) → ['Naruto', 'Sai']"],
          check: "assert on_both(['Naruto', 'Sakura', 'Sai'], ['Sai', 'Ino', 'Naruto']) == ['Naruto', 'Sai'], f'Got {on_both([\"Naruto\", \"Sakura\", \"Sai\"], [\"Sai\", \"Ino\", \"Naruto\"])}'\nassert on_both(['A'], ['B']) == []",
          solution: "def on_both(a, b):\n    return sorted(set(a) & set(b))" }
      ]},
      { id: "jc-linked", title: "Linked lists", kanji: "鎖", problems: [
        { id: "jc4", title: "Is it in the chain?",
          say: "Walk until you find it or run out of nodes.",
          task: "Write a function called `contains` that takes in the head of a linked list and a value, and returns True if any node holds that value.",
          prelude: LIST,
          examples: ["contains(build_list([4, 8, 15]), 8) → True", "contains(build_list([4, 8, 15]), 9) → False", "contains(None, 1) → False"],
          check: "assert contains(build_list([4, 8, 15]), 8) is True\nassert contains(build_list([4, 8, 15]), 9) is False\nassert contains(None, 1) is False, 'An empty list contains nothing.'",
          solution: "def contains(head, val):\n    node = head\n    while node:\n        if node.val == val:\n            return True\n        node = node.next\n    return False" },
        { id: "jc5", title: "Remove the first match",
          say: "Removing a node means making the node before it skip over it. The head is a special case because nothing is before it.",
          task: "Write a function called `remove_first` that takes in the head of a linked list and a value, removes the first node with that value, and returns the (possibly new) head. If the value isn't there, return the head unchanged.",
          prelude: LIST,
          examples: ["to_list(remove_first(build_list([1, 2, 3, 2]), 2)) → [1, 3, 2]", "to_list(remove_first(build_list([1, 2]), 1)) → [2]   (the head itself was removed)", "to_list(remove_first(build_list([1, 2]), 9)) → [1, 2]"],
          hint: "If head.val matches, return head.next. Otherwise walk with a prev pointer; when node.val matches, set prev.next = node.next.",
          check: "assert to_list(remove_first(build_list([1, 2, 3, 2]), 2)) == [1, 3, 2], f'Got {to_list(remove_first(build_list([1, 2, 3, 2]), 2))}'\nassert to_list(remove_first(build_list([1, 2]), 1)) == [2], 'Removing the head should return the second node as the new head.'\nassert to_list(remove_first(build_list([1, 2]), 9)) == [1, 2]\nassert remove_first(None, 1) is None",
          solution: "def remove_first(head, val):\n    if head is None:\n        return None\n    if head.val == val:\n        return head.next\n    prev = head\n    node = head.next\n    while node:\n        if node.val == val:\n            prev.next = node.next\n            return head\n        prev = node\n        node = node.next\n    return head" },
        { id: "jc6", title: "Chain to list, list to chain",
          say: "Converting back and forth is something you'll do in every test. Write both directions yourself — without the provided helpers.",
          task: "Write `to_values(head)` that returns a Python list of the node values, and `from_values(values)` that builds a chain from a Python list and returns its head (`None` for an empty list). Don't call the provided `to_list` or `build_list`.",
          prelude: LIST,
          examples: ["to_values(build_list([1, 2, 3])) → [1, 2, 3]", "to_list(from_values([4, 5])) → [4, 5]"],
          check: "assert 'to_list(' not in _src.replace('def to_list(', '') and 'build_list(' not in _src.replace('def build_list(', ''), 'Write them yourself without to_list or build_list.'\nassert to_values(build_list([1, 2, 3])) == [1, 2, 3], f'Got {to_values(build_list([1, 2, 3]))}'\nassert to_values(None) == []\nassert to_list(from_values([4, 5])) == [4, 5], f'from_values([4, 5]) built {to_list(from_values([4, 5]))}'\nassert from_values([]) is None",
          solution: "def to_values(head):\n    values = []\n    node = head\n    while node:\n        values.append(node.val)\n        node = node.next\n    return values\n\ndef from_values(values):\n    head = None\n    for v in reversed(values):\n        head = ListNode(v, head)\n    return head" }
      ]},
      { id: "jc-stack", title: "Stacks", kanji: "積", problems: [
        { id: "jc7", title: "Reverse with a stack",
          say: "Push every character, then pop them all — out they come backwards.",
          task: "Write a function called `reverse_text` that takes in a string and returns it reversed, using a list as a stack. No slicing tricks like `[::-1]` and no `reversed()`.",
          examples: ["reverse_text('kunai') → 'ianuk'", "reverse_text('') → ''"],
          check: "assert '[::-1]' not in _src and 'reversed(' not in _src, 'Use a stack — push each character, then pop.'\nassert '.pop()' in _src, 'Pop the characters off the stack.'\nassert reverse_text('kunai') == 'ianuk', f'Got {reverse_text(\"kunai\")!r}'\nassert reverse_text('') == ''",
          solution: "def reverse_text(text):\n    stack = []\n    for ch in text:\n        stack.append(ch)\n    result = ''\n    while stack:\n        result += stack.pop()\n    return result" },
        { id: "jc8", title: "Matching brackets",
          say: "Every opening bracket waits on the stack for its partner. A closing bracket with nothing waiting is an error, and so is anything left waiting at the end.",
          task: "Write a function called `balanced` that takes in a string containing only `(` and `)` and returns True if every opening bracket is closed in the right order.",
          examples: ["balanced('(())') → True", "balanced('(()') → False", "balanced(')(') → False", "balanced('') → True"],
          hint: "Push on '('. On ')', if the stack is empty return False, otherwise pop. At the end, return whether the stack is empty.",
          check: "assert balanced('(())') is True\nassert balanced('(()') is False, 'An unclosed ( should fail.'\nassert balanced(')(') is False, 'A ) with nothing open should fail.'\nassert balanced('') is True\nassert balanced('()()') is True",
          solution: "def balanced(text):\n    stack = []\n    for ch in text:\n        if ch == '(':\n            stack.append(ch)\n        else:\n            if not stack:\n                return False\n            stack.pop()\n    return len(stack) == 0" }
      ]},
      { id: "jc-queue", title: "Queues", kanji: "列", problems: [
        { id: "jc9", title: "Serve the first k",
          say: "Serve some of the line, and tell me who's still waiting.",
          task: "Write a function called `serve` that takes in a list of names and a number k, serves the first k people (removing them from the front of a deque), and returns a list of who is still in line.",
          examples: ["serve(['Naruto', 'Sasuke', 'Sakura', 'Sai'], 2) → ['Sakura', 'Sai']", "serve(['Naruto'], 5) → []"],
          check: "assert 'deque' in _src and '.popleft()' in _src, 'Use a deque and popleft.'\nassert serve(['Naruto', 'Sasuke', 'Sakura', 'Sai'], 2) == ['Sakura', 'Sai'], f'Got {serve([\"Naruto\", \"Sasuke\", \"Sakura\", \"Sai\"], 2)}'\nassert serve(['Naruto'], 5) == [], 'Serving more than the line has should leave an empty list, not crash.'",
          solution: "from collections import deque\n\ndef serve(names, k):\n    line = deque(names)\n    for _ in range(k):\n        if line:\n            line.popleft()\n    return list(line)" },
        { id: "jc10", title: "Hot potato",
          say: "Shinobi stand in a circle passing a smoke bomb. Every k-th pass, whoever holds it is out. Who's left? A deque makes the circle easy: move the front to the back k-1 times, then drop the front.",
          task: "Write a function called `last_standing` that takes in a list of names and a number k, and returns the name of the last person left when every k-th person is eliminated in a circle.",
          examples: ["last_standing(['A', 'B', 'C', 'D'], 2) → 'A'   (B out, D out, C out)", "last_standing(['Naruto', 'Sasuke', 'Sakura'], 3) → 'Sasuke'"],
          hint: "While more than one remains: repeat k-1 times move popleft() to the back with append; then popleft() the eliminated one.",
          check: "assert 'deque' in _src, 'Use a deque for the circle.'\nassert last_standing(['A', 'B', 'C', 'D'], 2) == 'A', f'Got {last_standing([\"A\", \"B\", \"C\", \"D\"], 2)!r}, expected A.'\nassert last_standing(['Naruto', 'Sasuke', 'Sakura'], 3) == 'Sasuke'\nassert last_standing(['Lee'], 7) == 'Lee'",
          solution: "from collections import deque\n\ndef last_standing(names, k):\n    circle = deque(names)\n    while len(circle) > 1:\n        for _ in range(k - 1):\n            circle.append(circle.popleft())\n        circle.popleft()\n    return circle[0]" }
      ]},
      { id: "jc-heap", title: "Heaps", kanji: "峰", problems: [
        { id: "jc11", title: "The k lightest kunai",
          say: "Put everything on a heap and pop k times. Sorting the whole list works too — but the heap is the tool we're drilling.",
          task: "Write a function called `lightest` that takes in a list of weights and a number k, and returns the k smallest weights in increasing order, using a heap.",
          examples: ["lightest([9, 2, 7, 4, 1], 3) → [1, 2, 4]", "lightest([5, 3], 5) → [3, 5]"],
          check: "assert 'heapq' in _src and 'sort' not in _src, 'Use heapq, not sorting.'\nassert lightest([9, 2, 7, 4, 1], 3) == [1, 2, 4], f'Got {lightest([9, 2, 7, 4, 1], 3)}'\nassert lightest([5, 3], 5) == [3, 5], 'If k is bigger than the list, return everything in order.'",
          solution: "import heapq\n\ndef lightest(weights, k):\n    heap = list(weights)\n    heapq.heapify(heap)\n    result = []\n    while heap and len(result) < k:\n        result.append(heapq.heappop(heap))\n    return result" },
        { id: "jc12", title: "Top scores",
          say: "Largest-first again, but this time return the top k and keep the heap small: push the negative, and remember that heapq has nlargest too.",
          task: "Write a function called `top_scores` that takes in a list of scores and a number k and returns the k highest, biggest first, using a heap.",
          examples: ["top_scores([40, 95, 60, 25, 80], 2) → [95, 80]", "top_scores([7], 3) → [7]"],
          check: "assert 'heapq' in _src and 'sort' not in _src, 'Use heapq, not sorting.'\nassert top_scores([40, 95, 60, 25, 80], 2) == [95, 80], f'Got {top_scores([40, 95, 60, 25, 80], 2)}'\nassert top_scores([7], 3) == [7]\nassert top_scores([1, 2, 3, 4], 3) == [4, 3, 2]",
          solution: "import heapq\n\ndef top_scores(scores, k):\n    heap = [-s for s in scores]\n    heapq.heapify(heap)\n    result = []\n    while heap and len(result) < k:\n        result.append(-heapq.heappop(heap))\n    return result" }
      ]},
      { id: "jc-tree", title: "Trees", kanji: "樹", problems: [
        { id: "jc13", title: "Count the nodes",
          say: "Same shape as tree_sum: base case for None, then one plus the two subtrees.",
          task: "Write a function called `count_nodes` that takes in the root of a tree and returns how many nodes it has.",
          prelude: TREE,
          examples: ["count_nodes(build_tree([1, 2, 3, 4])) → 4", "count_nodes(None) → 0"],
          check: "assert count_nodes(None) == 0\nassert count_nodes(build_tree([1, 2, 3, 4])) == 4, f'Got {count_nodes(build_tree([1, 2, 3, 4]))}'\nassert count_nodes(build_tree([1, None, 2, None, 3])) == 3",
          solution: "def count_nodes(node):\n    if node is None:\n        return 0\n    return 1 + count_nodes(node.left) + count_nodes(node.right)" },
        { id: "jc14", title: "Tallest branch",
          say: "The height of a tree is the longest path from the root down. It's 1 plus the taller of the two subtrees.",
          task: "Write a function called `height` that takes in the root of a tree and returns its height: the number of nodes on the longest root-to-leaf path. An empty tree has height 0.",
          prelude: TREE,
          examples: ["height(build_tree([1, 2, 3])) → 2", "height(build_tree([1, 2, None, 3])) → 3", "height(None) → 0"],
          check: "assert height(None) == 0\nassert height(build_tree([1, 2, 3])) == 2, f'Got {height(build_tree([1, 2, 3]))} for a root with two children.'\nassert height(build_tree([1, 2, None, 3])) == 3, 'A chain of three nodes down the left has height 3.'\nassert height(build_tree([1])) == 1",
          solution: "def height(node):\n    if node is None:\n        return 0\n    return 1 + max(height(node.left), height(node.right))" },
        { id: "jc15", title: "Largest value",
          say: "Combine the node with the best from each side. Be careful what you return for None — it has to lose against any real value.",
          task: "Write a function called `tree_max` that takes in the root of a non-empty tree and returns the largest value in it.",
          prelude: TREE,
          examples: ["tree_max(build_tree([3, 9, 20, None, None, 15, 7])) → 20", "tree_max(build_tree([-5, -9, -1])) → -1"],
          hint: "Gather the node's value and the maxima of any children that exist, then return max of those.",
          check: "assert tree_max(build_tree([3, 9, 20, None, None, 15, 7])) == 20, f'Got {tree_max(build_tree([3, 9, 20, None, None, 15, 7]))}'\nassert tree_max(build_tree([-5, -9, -1])) == -1, 'With negative values, make sure None does not win with a 0.'\nassert tree_max(build_tree([4])) == 4",
          solution: "def tree_max(node):\n    best = node.val\n    if node.left:\n        best = max(best, tree_max(node.left))\n    if node.right:\n        best = max(best, tree_max(node.right))\n    return best" }
      ]},
      { id: "jc-graph", title: "Graphs & grids", kanji: "網", problems: [
        { id: "jc16", title: "Count the roads",
          say: "In an undirected graph every road appears twice — once from each end. Count the neighbour entries and halve them.",
          task: "Write a function called `road_count` that takes in a graph (a dictionary from place to list of neighbours, with every road listed from both ends) and returns how many roads there are.",
          examples: ["road_count({'A': ['B', 'C'], 'B': ['A'], 'C': ['A']}) → 2", "road_count({'A': []}) → 0"],
          check: "assert road_count({'A': ['B', 'C'], 'B': ['A'], 'C': ['A']}) == 2, f'Got {road_count({\"A\": [\"B\", \"C\"], \"B\": [\"A\"], \"C\": [\"A\"]})}'\nassert road_count({'A': []}) == 0\nassert road_count({'A': ['B'], 'B': ['A', 'C'], 'C': ['B', 'D'], 'D': ['C']}) == 3",
          solution: "def road_count(graph):\n    total = 0\n    for place in graph:\n        total += len(graph[place])\n    return total // 2" },
        { id: "jc17", title: "Count the trees on the map",
          say: "A grid of 0s (grass) and 1s (trees). Two loops, one over rows and one over columns, visit every cell.",
          task: "Write a function called `count_trees` that takes in a grid (a list of rows of 0s and 1s) and returns how many 1s it contains.",
          examples: ["count_trees([[0, 1, 0], [1, 1, 0]]) → 3", "count_trees([[0]]) → 0"],
          check: "assert count_trees([[0, 1, 0], [1, 1, 0]]) == 3, f'Got {count_trees([[0, 1, 0], [1, 1, 0]])}'\nassert count_trees([[0]]) == 0\nassert count_trees([[1, 1], [1, 1], [1, 1]]) == 6",
          solution: "def count_trees(grid):\n    total = 0\n    for row in grid:\n        for cell in row:\n            if cell == 1:\n                total += 1\n    return total" },
        { id: "jc18", title: "Who can you reach in one step?",
          say: "Combine the two: a grid, and the four-neighbour check. Count the open cells next to a given cell.",
          task: "Write a function called `open_neighbours` that takes in a grid (0 = open, 1 = wall) and a cell `(r, c)`, and returns how many of the cell's up/down/left/right neighbours are inside the grid and open.",
          examples: ["grid = [[0, 0, 1],\n        [1, 0, 0],\n        [0, 1, 0]]\nopen_neighbours(grid, 1, 1) → 2   (up and right are open; left and down are walls)", "open_neighbours(grid, 0, 0) → 1"],
          check: "g = [[0, 0, 1], [1, 0, 0], [0, 1, 0]]\nassert open_neighbours(g, 1, 1) == 2, f'Got {open_neighbours(g, 1, 1)} for the centre cell, expected 2.'\nassert open_neighbours(g, 0, 0) == 1, f'Got {open_neighbours(g, 0, 0)} for the corner, expected 1 (only right is open).'\nassert open_neighbours(g, 2, 2) == 1",
          solution: "def open_neighbours(grid, r, c):\n    rows = len(grid)\n    cols = len(grid[0])\n    count = 0\n    for dr, dc in [(-1, 0), (1, 0), (0, -1), (0, 1)]:\n        nr = r + dr\n        nc = c + dc\n        if 0 <= nr < rows and 0 <= nc < cols and grid[nr][nc] == 0:\n            count += 1\n    return count" }
      ]},
      { id: "jc-dp", title: "Dynamic programming", kanji: "記", problems: [
        { id: "jc19", title: "Climbing the Hokage steps",
          say: "You climb one or two steps at a time. How many different ways up n steps? The ways to reach step n are the ways to reach n-1 plus the ways to reach n-2 — that's a table.",
          task: "Write a function called `ways` that takes in a number of steps n and returns how many distinct ways there are to climb them taking 1 or 2 steps at a time.",
          examples: ["ways(2) → 2   (1+1, 2)", "ways(3) → 3   (1+1+1, 1+2, 2+1)", "ways(10) → 89"],
          hint: "ways(1) = 1, ways(2) = 2, and ways(n) = ways(n-1) + ways(n-2). Fill a table or use a memo — a plain recursive version will be far too slow for 40.",
          check: "assert ways(1) == 1 and ways(2) == 2 and ways(3) == 3\nassert ways(10) == 89, f'ways(10) returned {ways(10)}'\nassert ways(40) == 165580141, 'ways(40) should be 165580141 — if this hangs, remember the answers.'",
          solution: "def ways(n):\n    if n <= 2:\n        return n\n    dp = [0] * (n + 1)\n    dp[1] = 1\n    dp[2] = 2\n    for i in range(3, n + 1):\n        dp[i] = dp[i - 1] + dp[i - 2]\n    return dp[n]" },
        { id: "jc20", title: "Cheapest climb",
          say: "Each step has a toll. You can start on step 0 or step 1 and climb one or two at a time; you've finished once you're past the last step. What's the least you can pay? For each step, the cheapest way to stand on it comes from the cheaper of the two steps below.",
          task: "Write a function called `min_cost` that takes in a list of step costs and returns the minimum total cost to get past the top. You may start on step 0 or step 1 and move 1 or 2 steps at a time; you pay a step's cost when you stand on it.",
          examples: ["min_cost([10, 15, 20]) → 15   (start on step 1, jump past the top)", "min_cost([1, 100, 1, 1, 1, 100, 1, 1, 100, 1]) → 6"],
          hint: "dp[i] = cost[i] + min(dp[i-1], dp[i-2]) is the cheapest way to stand on step i. The answer is the cheaper of the last two steps.",
          check: "assert min_cost([10, 15, 20]) == 15, f'min_cost([10, 15, 20]) returned {min_cost([10, 15, 20])}, expected 15.'\nassert min_cost([1, 100, 1, 1, 1, 100, 1, 1, 100, 1]) == 6, f'Got {min_cost([1, 100, 1, 1, 1, 100, 1, 1, 100, 1])}, expected 6.'\nassert min_cost([5, 3]) == 3",
          solution: "def min_cost(cost):\n    n = len(cost)\n    dp = [0] * n\n    dp[0] = cost[0]\n    dp[1] = cost[1]\n    for i in range(2, n):\n        dp[i] = cost[i] + min(dp[i - 1], dp[i - 2])\n    return min(dp[n - 1], dp[n - 2])" }
      ]}
    ]},

  /* ============================ B-RANK ============================ */
  { id: "B", rank: "B", title: "Chunin Trials", short: "Trials", kanji: "試",
    intro: "These are the real thing — the kind of problems shinobi face in interviews. Still one structure each, but now you have to see which trick fits. Read every example before you write a line.",
    topics: [
      { id: "jb-hash", title: "Hash maps & sets", kanji: "辞", problems: [
        { id: "jb1", title: "Anagram jutsu",
          say: "Two words are anagrams if they use exactly the same letters the same number of times. Count the letters of each and compare.",
          task: "Write a function called `is_anagram` that takes in two strings and returns True if one is a rearrangement of the other.",
          examples: ["is_anagram('listen', 'silent') → True", "is_anagram('kunai', 'kunal') → False", "is_anagram('ab', 'a') → False"],
          hint: "Build a count dictionary for each word (or use the first word to count up and the second to count down).",
          check: "assert is_anagram('listen', 'silent') is True\nassert is_anagram('kunai', 'kunal') is False\nassert is_anagram('ab', 'a') is False, 'Different lengths can never be anagrams.'\nassert is_anagram('aab', 'abb') is False, 'Same letters but different counts: not an anagram.'",
          solution: "def is_anagram(a, b):\n    if len(a) != len(b):\n        return False\n    count = {}\n    for ch in a:\n        count[ch] = count.get(ch, 0) + 1\n    for ch in b:\n        if count.get(ch, 0) == 0:\n            return False\n        count[ch] -= 1\n    return True" },
        { id: "jb2", title: "Ransom note",
          say: "Can you spell the note using only the letters cut from the magazine? Each letter can be used once. Count what you have, then spend it.",
          task: "Write a function called `can_build` that takes in a note and a pile of letters (both strings) and returns True if the note can be built from the pile, using each letter in the pile at most once.",
          examples: ["can_build('aa', 'aab') → True", "can_build('aa', 'ab') → False", "can_build('', 'xyz') → True"],
          check: "assert can_build('aa', 'aab') is True\nassert can_build('aa', 'ab') is False, 'Only one a is available.'\nassert can_build('', 'xyz') is True\nassert can_build('kunai', 'iaknu') is True",
          solution: "def can_build(note, pile):\n    available = {}\n    for ch in pile:\n        available[ch] = available.get(ch, 0) + 1\n    for ch in note:\n        if available.get(ch, 0) == 0:\n            return False\n        available[ch] -= 1\n    return True" }
      ]},
      { id: "jb-linked", title: "Linked lists", kanji: "鎖", problems: [
        { id: "jb3", title: "Reverse the chain",
          say: "The classic. Walk the chain, and at each node flip its .next to point backwards. You need three pointers: previous, current, and a saved copy of next so you don't lose the rest of the chain.",
          task: "Write a function called `reverse` that takes in the head of a linked list and returns the head of the reversed list. Reverse it in place by changing the `.next` pointers — don't build a new list.",
          prelude: LIST,
          examples: ["to_list(reverse(build_list([1, 2, 3, 4]))) → [4, 3, 2, 1]", "reverse(None) → None"],
          hint: "prev = None; node = head. Loop: nxt = node.next; node.next = prev; prev = node; node = nxt. Return prev.",
          check: "assert 'ListNode(' not in _src, 'Reverse in place by changing .next — don\\'t make new nodes.'\nh = build_list([1, 2, 3, 4]); r = reverse(h)\nassert to_list(r) == [4, 3, 2, 1], f'Got {to_list(r)}'\nassert reverse(None) is None\nassert to_list(reverse(build_list([1]))) == [1]",
          solution: "def reverse(head):\n    prev = None\n    node = head\n    while node:\n        nxt = node.next\n        node.next = prev\n        prev = node\n        node = nxt\n    return prev" },
        { id: "jb4", title: "Middle of the chain",
          say: "Two runners: a slow one moving one node at a time and a fast one moving two. When the fast one reaches the end, the slow one is in the middle.",
          task: "Write a function called `middle` that takes in the head of a linked list and returns the value of the middle node. If there are two middle nodes, return the second one.",
          prelude: LIST,
          examples: ["middle(build_list([1, 2, 3, 4, 5])) → 3", "middle(build_list([1, 2, 3, 4, 5, 6])) → 4"],
          hint: "slow = fast = head. While fast and fast.next: slow = slow.next; fast = fast.next.next.",
          check: "assert middle(build_list([1, 2, 3, 4, 5])) == 3, f'Got {middle(build_list([1, 2, 3, 4, 5]))}'\nassert middle(build_list([1, 2, 3, 4, 5, 6])) == 4, 'With an even length, return the second middle.'\nassert middle(build_list([9])) == 9",
          solution: "def middle(head):\n    slow = head\n    fast = head\n    while fast and fast.next:\n        slow = slow.next\n        fast = fast.next.next\n    return slow.val" },
        { id: "jb5", title: "Merge two sorted chains",
          say: "Like merging two sorted lists, but with pointers. A dummy starting node saves you from special-casing the head.",
          task: "Write a function called `merge_chains` that takes in the heads of two sorted linked lists and returns the head of one sorted chain containing all the nodes. Relink the existing nodes — don't create new ones.",
          prelude: LIST,
          examples: ["to_list(merge_chains(build_list([1, 3, 5]), build_list([2, 4]))) → [1, 2, 3, 4, 5]", "to_list(merge_chains(None, build_list([1]))) → [1]"],
          hint: "dummy = ListNode(0); tail = dummy. While both: attach the smaller head to tail.next, advance that list and tail. Then attach whatever is left. Return dummy.next.",
          check: "assert to_list(merge_chains(build_list([1, 3, 5]), build_list([2, 4]))) == [1, 2, 3, 4, 5], f'Got {to_list(merge_chains(build_list([1, 3, 5]), build_list([2, 4])))}'\nassert to_list(merge_chains(None, build_list([1]))) == [1]\nassert to_list(merge_chains(build_list([1, 1]), build_list([1]))) == [1, 1, 1]\nassert merge_chains(None, None) is None",
          solution: "def merge_chains(a, b):\n    dummy = ListNode(0)\n    tail = dummy\n    while a and b:\n        if a.val <= b.val:\n            tail.next = a\n            a = a.next\n        else:\n            tail.next = b\n            b = b.next\n        tail = tail.next\n    tail.next = a if a else b\n    return dummy.next" }
      ]},
      { id: "jb-stack", title: "Stacks", kanji: "積", problems: [
        { id: "jb6", title: "Valid brackets",
          say: "Three kinds of bracket now. A closing bracket must match the most recent opening one — which is exactly what the top of the stack is.",
          task: "Write a function called `valid` that takes in a string of `()[]{}` characters and returns True if every bracket is closed by the matching kind in the right order.",
          examples: ["valid('()[]{}') → True", "valid('([)]') → False", "valid('{[]}') → True", "valid('(') → False"],
          hint: "A dictionary from closing to opening bracket: pairs = {')': '(', ']': '[', '}': '{'}. On a closer, the stack must be non-empty and its top must equal pairs[ch].",
          check: "assert valid('()[]{}') is True\nassert valid('([)]') is False, '([)] closes the wrong bracket first.'\nassert valid('{[]}') is True\nassert valid('(') is False\nassert valid(']') is False",
          solution: "def valid(text):\n    pairs = {')': '(', ']': '[', '}': '{'}\n    stack = []\n    for ch in text:\n        if ch in pairs:\n            if not stack or stack[-1] != pairs[ch]:\n                return False\n            stack.pop()\n        else:\n            stack.append(ch)\n    return len(stack) == 0" },
        { id: "jb7", title: "Min stack",
          say: "A stack that can also tell you its smallest item instantly. Keep a second stack that records the minimum as of each push.",
          task: "Make a class called `MinStack` with methods `push(x)`, `pop()`, `top()` (returns the top without removing it) and `get_min()` (returns the smallest value currently in the stack). Every method must be instant — no scanning the whole stack in get_min.",
          examples: ["s = MinStack()\ns.push(5); s.push(2); s.push(7)\ns.get_min() → 2\ns.pop()\ns.top() → 2\ns.pop()\ns.get_min() → 5"],
          hint: "Keep two lists: items and mins. On push(x), push x to items and min(x, mins[-1]) to mins. Pop both together.",
          check: "assert 'min(' not in _src.replace('get_min(', '') or _src.count('min(') - _src.count('get_min(') <= 1, 'Keep a second stack of minimums rather than scanning.'\ns = MinStack()\ns.push(5); s.push(2); s.push(7)\nassert s.get_min() == 2, f'get_min returned {s.get_min()}, expected 2.'\nassert s.top() == 7\ns.pop()\nassert s.top() == 2 and s.get_min() == 2\ns.pop()\nassert s.get_min() == 5, 'After popping the 2, the minimum should go back to 5.'",
          solution: "class MinStack:\n    def __init__(self):\n        self.items = []\n        self.mins = []\n\n    def push(self, x):\n        self.items.append(x)\n        if self.mins:\n            self.mins.append(min(x, self.mins[-1]))\n        else:\n            self.mins.append(x)\n\n    def pop(self):\n        self.mins.pop()\n        return self.items.pop()\n\n    def top(self):\n        return self.items[-1]\n\n    def get_min(self):\n        return self.mins[-1]" }
      ]},
      { id: "jb-queue", title: "Queues", kanji: "列", problems: [
        { id: "jb8", title: "Recent pings",
          say: "A sensor counts how many pings arrived in the last 3000 milliseconds. Old pings drop off the front of the queue as time moves on.",
          task: "Make a class called `RecentCounter` with a method `ping(t)` that records a ping at time t (times only ever increase) and returns how many pings have happened in the window `[t - 3000, t]`, including this one.",
          examples: ["c = RecentCounter()\nc.ping(1) → 1\nc.ping(100) → 2\nc.ping(3001) → 3\nc.ping(3002) → 3   (the ping at 1 is now too old)"],
          hint: "Append t to a deque. While the front is less than t - 3000, popleft. Return the length.",
          check: "assert 'deque' in _src, 'Use a deque so dropping old pings is instant.'\nc = RecentCounter()\nassert c.ping(1) == 1 and c.ping(100) == 2 and c.ping(3001) == 3\nassert c.ping(3002) == 3, 'At t=3002 the ping at t=1 is outside the window.'",
          solution: "from collections import deque\n\nclass RecentCounter:\n    def __init__(self):\n        self.pings = deque()\n\n    def ping(self, t):\n        self.pings.append(t)\n        while self.pings[0] < t - 3000:\n            self.pings.popleft()\n        return len(self.pings)" },
        { id: "jb9", title: "Moving average",
          say: "Keep only the last k numbers and average them. When a new one arrives and the window is full, the oldest leaves.",
          task: "Make a class called `MovingAverage` whose constructor takes in a window size k. Its method `add(x)` records x and returns the average of the most recent k values (or of all values if fewer than k have been added).",
          examples: ["m = MovingAverage(3)\nm.add(1) → 1.0\nm.add(10) → 5.5\nm.add(3) → 4.666...\nm.add(5) → 6.0   (the 1 dropped out: (10 + 3 + 5) / 3)"],
          hint: "Keep a deque and a running total. When len exceeds k, popleft and subtract it from the total.",
          check: "m = MovingAverage(3)\nassert m.add(1) == 1.0\nassert m.add(10) == 5.5\nassert abs(m.add(3) - 14 / 3) < 1e-9\nassert m.add(5) == 6.0, f'After adding 5 the window is [10, 3, 5], average 6.0.'",
          solution: "from collections import deque\n\nclass MovingAverage:\n    def __init__(self, k):\n        self.k = k\n        self.window = deque()\n        self.total = 0\n\n    def add(self, x):\n        self.window.append(x)\n        self.total += x\n        if len(self.window) > self.k:\n            self.total -= self.window.popleft()\n        return self.total / len(self.window)" }
      ]},
      { id: "jb-heap", title: "Heaps", kanji: "峰", problems: [
        { id: "jb10", title: "k-th largest",
          say: "Keep a min-heap of size k. Its smallest element is the k-th largest overall — anything smaller than it can't be in the top k.",
          task: "Write a function called `kth_largest` that takes in a list of numbers and a number k and returns the k-th largest value (duplicates count separately).",
          examples: ["kth_largest([3, 2, 1, 5, 6, 4], 2) → 5", "kth_largest([3, 2, 3, 1, 2, 4, 5, 5, 6], 4) → 4"],
          hint: "Push each number; if the heap grows past k, heappop. At the end heap[0] is the answer.",
          check: "assert 'heapq' in _src and 'sort' not in _src, 'Use a heap, not sorting.'\nassert kth_largest([3, 2, 1, 5, 6, 4], 2) == 5, f'Got {kth_largest([3, 2, 1, 5, 6, 4], 2)}'\nassert kth_largest([3, 2, 3, 1, 2, 4, 5, 5, 6], 4) == 4\nassert kth_largest([1], 1) == 1",
          solution: "import heapq\n\ndef kth_largest(nums, k):\n    heap = []\n    for n in nums:\n        heapq.heappush(heap, n)\n        if len(heap) > k:\n            heapq.heappop(heap)\n    return heap[0]" },
        { id: "jb11", title: "Last stone standing",
          say: "Smash the two heaviest stones together. Equal weights destroy each other; otherwise the difference survives. Repeat until one or none is left. 'Two heaviest, repeatedly' is a heap's job.",
          task: "Write a function called `last_stone` that takes in a list of stone weights and returns the weight of the last stone left, or 0 if none remain.",
          examples: ["last_stone([2, 7, 4, 1, 8, 1]) → 1", "last_stone([1]) → 1", "last_stone([3, 3]) → 0"],
          hint: "Max-heap via negatives. While more than one stone: pop two; if they differ, push the difference back.",
          check: "assert 'heapq' in _src, 'Use heapq.'\nassert last_stone([2, 7, 4, 1, 8, 1]) == 1, f'Got {last_stone([2, 7, 4, 1, 8, 1])}'\nassert last_stone([1]) == 1\nassert last_stone([3, 3]) == 0, 'Two equal stones destroy each other.'",
          solution: "import heapq\n\ndef last_stone(stones):\n    heap = [-s for s in stones]\n    heapq.heapify(heap)\n    while len(heap) > 1:\n        a = -heapq.heappop(heap)\n        b = -heapq.heappop(heap)\n        if a != b:\n            heapq.heappush(heap, -(a - b))\n    return -heap[0] if heap else 0" }
      ]},
      { id: "jb-tree", title: "Trees", kanji: "樹", problems: [
        { id: "jb12", title: "Mirror the tree",
          say: "Swap every node's left and right children. Recursion does the whole tree in four lines.",
          task: "Write a function called `invert` that takes in the root of a tree, swaps the left and right children of every node, and returns the root.",
          prelude: TREE,
          examples: ["Before: [4, 2, 7, 1, 3, 6, 9]   After: root.left.val → 7, root.right.val → 2, root.left.left.val → 9"],
          check: "r = invert(build_tree([4, 2, 7, 1, 3, 6, 9]))\nassert r.val == 4 and r.left.val == 7 and r.right.val == 2, 'The root\\'s children should be swapped.'\nassert r.left.left.val == 9 and r.left.right.val == 6 and r.right.left.val == 3 and r.right.right.val == 1, 'Deeper levels must be swapped too.'\nassert invert(None) is None",
          solution: "def invert(node):\n    if node is None:\n        return None\n    node.left, node.right = node.right, node.left\n    invert(node.left)\n    invert(node.right)\n    return node" },
        { id: "jb13", title: "Same tree?",
          say: "Two trees are the same if the roots match and both left subtrees match and both right subtrees match. Handle the cases where one or both are None first.",
          task: "Write a function called `same` that takes in the roots of two trees and returns True if they have the same shape and the same values everywhere.",
          prelude: TREE,
          examples: ["same(build_tree([1, 2, 3]), build_tree([1, 2, 3])) → True", "same(build_tree([1, 2]), build_tree([1, None, 2])) → False", "same(None, None) → True"],
          check: "assert same(build_tree([1, 2, 3]), build_tree([1, 2, 3])) is True\nassert same(build_tree([1, 2]), build_tree([1, None, 2])) is False, 'Same values but different shape: not the same.'\nassert same(None, None) is True\nassert same(build_tree([1]), None) is False",
          solution: "def same(a, b):\n    if a is None and b is None:\n        return True\n    if a is None or b is None:\n        return False\n    return a.val == b.val and same(a.left, b.left) and same(a.right, b.right)" },
        { id: "jb14", title: "Is it balanced?",
          say: "A tree is balanced if, at every node, the left and right heights differ by at most one. Compute heights from the bottom up and bail out the moment you find an imbalance.",
          task: "Write a function called `balanced_tree` that takes in the root of a tree and returns True if every node's left and right subtree heights differ by no more than 1.",
          prelude: TREE,
          examples: ["balanced_tree(build_tree([3, 9, 20, None, None, 15, 7])) → True", "balanced_tree(build_tree([1, 2, 2, 3, 3, None, None, 4, 4])) → False", "balanced_tree(None) → True"],
          hint: "Write a helper that returns the height, or -1 if the subtree is unbalanced. If either child returns -1 or the heights differ by more than 1, return -1.",
          check: "assert balanced_tree(build_tree([3, 9, 20, None, None, 15, 7])) is True\nassert balanced_tree(build_tree([1, 2, 2, 3, 3, None, None, 4, 4])) is False, 'The left side is two levels deeper than the right.'\nassert balanced_tree(None) is True\nassert balanced_tree(build_tree([1, None, 2, None, 3])) is False",
          solution: "def balanced_tree(root):\n    def check(node):\n        if node is None:\n            return 0\n        left = check(node.left)\n        if left == -1:\n            return -1\n        right = check(node.right)\n        if right == -1:\n            return -1\n        if abs(left - right) > 1:\n            return -1\n        return 1 + max(left, right)\n    return check(root) != -1" }
      ]},
      { id: "jb-graph", title: "Graphs & grids", kanji: "網", problems: [
        { id: "jb15", title: "Flood fill",
          say: "Paint-bucket. Starting from a cell, recolour it and every same-coloured cell you can reach through neighbours. Recursion or a queue — either works. Mark cells as you go so you don't loop forever.",
          task: "Write a function called `flood_fill` that takes in a grid of numbers, a start row and column, and a new colour. Change the start cell and every connected cell (up/down/left/right) with the same original colour to the new colour. Return the grid.",
          examples: ["flood_fill([[1, 1, 0],\n            [1, 0, 0],\n            [1, 1, 1]], 0, 0, 2)\n→ [[2, 2, 0],\n   [2, 0, 0],\n   [2, 2, 2]]"],
          hint: "If the new colour equals the old colour, return immediately. Otherwise recurse into in-bounds neighbours that still have the old colour.",
          check: "assert flood_fill([[1, 1, 0], [1, 0, 0], [1, 1, 1]], 0, 0, 2) == [[2, 2, 0], [2, 0, 0], [2, 2, 2]], f'Got {flood_fill([[1, 1, 0], [1, 0, 0], [1, 1, 1]], 0, 0, 2)}'\nassert flood_fill([[0, 0], [0, 0]], 1, 1, 0) == [[0, 0], [0, 0]], 'Filling with the same colour must not loop forever.'\nassert flood_fill([[1, 0], [0, 1]], 0, 0, 5) == [[5, 0], [0, 1]], 'Diagonal cells are not connected.'",
          solution: "def flood_fill(grid, r, c, colour):\n    old = grid[r][c]\n    if old == colour:\n        return grid\n    rows = len(grid)\n    cols = len(grid[0])\n\n    def fill(r, c):\n        if r < 0 or r >= rows or c < 0 or c >= cols:\n            return\n        if grid[r][c] != old:\n            return\n        grid[r][c] = colour\n        fill(r - 1, c)\n        fill(r + 1, c)\n        fill(r, c - 1)\n        fill(r, c + 1)\n\n    fill(r, c)\n    return grid" },
        { id: "jb16", title: "Count the islands",
          say: "Land is 1, water is 0. Every time you find a 1 you haven't visited, that's a new island — flood it so you don't count it again, and keep scanning.",
          task: "Write a function called `islands` that takes in a grid of 0s and 1s and returns how many islands there are. An island is a group of 1s connected up/down/left/right. You may modify the grid.",
          examples: ["islands([[1, 1, 0, 0],\n         [0, 1, 0, 1],\n         [0, 0, 0, 1],\n         [1, 0, 0, 0]]) → 3"],
          hint: "Loop over every cell. On a 1: count += 1, then sink the whole island (set its cells to 0 with a flood).",
          check: "assert islands([[1, 1, 0, 0], [0, 1, 0, 1], [0, 0, 0, 1], [1, 0, 0, 0]]) == 3, f'Got {islands([[1, 1, 0, 0], [0, 1, 0, 1], [0, 0, 0, 1], [1, 0, 0, 0]])}, expected 3.'\nassert islands([[0, 0], [0, 0]]) == 0\nassert islands([[1, 0, 1], [0, 1, 0], [1, 0, 1]]) == 5, 'Diagonals do not connect: 5 separate islands.'",
          solution: "def islands(grid):\n    rows = len(grid)\n    cols = len(grid[0])\n\n    def sink(r, c):\n        if r < 0 or r >= rows or c < 0 or c >= cols or grid[r][c] != 1:\n            return\n        grid[r][c] = 0\n        sink(r - 1, c)\n        sink(r + 1, c)\n        sink(r, c - 1)\n        sink(r, c + 1)\n\n    count = 0\n    for r in range(rows):\n        for c in range(cols):\n            if grid[r][c] == 1:\n                count += 1\n                sink(r, c)\n    return count" }
      ]},
      { id: "jb-dp", title: "Dynamic programming", kanji: "記", problems: [
        { id: "jb17", title: "Raid the houses",
          say: "A row of houses with ryō inside. Rob any you like, but never two next to each other or the alarm trips. At each house, the best haul so far is either skip it, or take it plus the best from two houses back.",
          task: "Write a function called `max_loot` that takes in a list of amounts (one per house) and returns the most you can take without robbing two adjacent houses.",
          examples: ["max_loot([1, 2, 3, 1]) → 4   (houses 1 and 3)", "max_loot([2, 7, 9, 3, 1]) → 12   (2 + 9 + 1)", "max_loot([]) → 0"],
          hint: "Keep two numbers: best including the previous house, and best excluding it. For each amount: new_include = exclude + amount; new_exclude = max(include, exclude).",
          check: "assert max_loot([1, 2, 3, 1]) == 4, f'Got {max_loot([1, 2, 3, 1])}, expected 4.'\nassert max_loot([2, 7, 9, 3, 1]) == 12, f'Got {max_loot([2, 7, 9, 3, 1])}, expected 12.'\nassert max_loot([]) == 0\nassert max_loot([5]) == 5",
          solution: "def max_loot(houses):\n    include = 0\n    exclude = 0\n    for amount in houses:\n        new_include = exclude + amount\n        new_exclude = max(include, exclude)\n        include = new_include\n        exclude = new_exclude\n    return max(include, exclude)" },
        { id: "jb18", title: "Count the paths",
          say: "A robot in the top-left of a grid can only move right or down. How many routes to the bottom-right? Every cell's count is the count from above plus the count from the left.",
          task: "Write a function called `paths` that takes in a number of rows and columns and returns how many distinct right/down paths lead from the top-left cell to the bottom-right cell.",
          examples: ["paths(2, 2) → 2", "paths(3, 7) → 28", "paths(1, 5) → 1"],
          hint: "Make a rows×cols table of 1s (the first row and column each have one path). Then for every other cell: dp[r][c] = dp[r-1][c] + dp[r][c-1].",
          check: "assert paths(2, 2) == 2\nassert paths(3, 7) == 28, f'paths(3, 7) returned {paths(3, 7)}'\nassert paths(1, 5) == 1\nassert paths(10, 10) == 48620, 'If this is slow, you are recomputing cells — use a table.'",
          solution: "def paths(rows, cols):\n    dp = [[1] * cols for _ in range(rows)]\n    for r in range(1, rows):\n        for c in range(1, cols):\n            dp[r][c] = dp[r - 1][c] + dp[r][c - 1]\n    return dp[rows - 1][cols - 1]" }
      ]}
    ]},

  /* ============================ A-RANK ============================ */
  { id: "A", rank: "A", title: "Combination Jutsu", short: "Combo", kanji: "合",
    intro: "Combination jutsu! Each of these needs two structures working together. The first question is always: which two, and which does what? Decide that before you type.",
    topics: [
      { id: "ja-all", title: "Mixed techniques", kanji: "合", problems: [
        { id: "ja1", title: "Top k most common",
          say: "Hash map plus heap. Count everything first, then use a heap to pull out the k biggest counts.",
          task: "Write a function called `most_common` that takes in a list of items and a number k and returns the k items that appear most often, most frequent first. You can assume there are no ties for the k-th place.",
          examples: ["most_common(['a', 'b', 'a', 'c', 'a', 'b'], 2) → ['a', 'b']", "most_common([1, 1, 1, 2, 2, 3], 1) → [1]"],
          hint: "Count into a dictionary. Push (-count, item) for each entry onto a heap; pop k times.",
          check: "assert 'heapq' in _src, 'Use a heap for the top k.'\nassert most_common(['a', 'b', 'a', 'c', 'a', 'b'], 2) == ['a', 'b'], f'Got {most_common([\"a\", \"b\", \"a\", \"c\", \"a\", \"b\"], 2)}'\nassert most_common([1, 1, 1, 2, 2, 3], 1) == [1]\nassert most_common([5], 1) == [5]",
          solution: "import heapq\n\ndef most_common(items, k):\n    count = {}\n    for x in items:\n        count[x] = count.get(x, 0) + 1\n    heap = []\n    for item, n in count.items():\n        heapq.heappush(heap, (-n, item))\n    result = []\n    for _ in range(k):\n        result.append(heapq.heappop(heap)[1])\n    return result" },
        { id: "ja2", title: "Group the anagrams",
          say: "Hash map with a clever key. Words that are anagrams become identical when you sort their letters — so the sorted word is the key, and the value is the list of words that share it.",
          task: "Write a function called `group_anagrams` that takes in a list of words and returns a list of groups, where each group is a list of words that are anagrams of each other. Keep words in their original order within a group, and order the groups by the first appearance of each group.",
          examples: ["group_anagrams(['eat', 'tea', 'tan', 'ate', 'nat', 'bat']) → [['eat', 'tea', 'ate'], ['tan', 'nat'], ['bat']]"],
          hint: "key = ''.join(sorted(word)). groups.setdefault(key, []).append(word). Return list(groups.values()).",
          check: "assert group_anagrams(['eat', 'tea', 'tan', 'ate', 'nat', 'bat']) == [['eat', 'tea', 'ate'], ['tan', 'nat'], ['bat']], f'Got {group_anagrams([\"eat\", \"tea\", \"tan\", \"ate\", \"nat\", \"bat\"])}'\nassert group_anagrams(['']) == [['']]\nassert group_anagrams(['a']) == [['a']]",
          solution: "def group_anagrams(words):\n    groups = {}\n    for w in words:\n        key = ''.join(sorted(w))\n        if key not in groups:\n            groups[key] = []\n        groups[key].append(w)\n    return list(groups.values())" },
        { id: "ja3", title: "Next greater kunai",
          say: "Stack plus hash map. For each weight, find the next weight to its right that's bigger. A stack of 'waiting for something bigger' handles it in one pass; a dictionary remembers each answer so you can look them up for the query list.",
          task: "Write a function called `next_greater` that takes in two lists, `query` and `weights`, where every element of `query` appears in `weights`. For each query value, return the first element to its right in `weights` that is greater, or -1 if there is none.",
          examples: ["next_greater([4, 1, 2], [1, 3, 4, 2]) → [-1, 3, -1]", "next_greater([2, 4], [1, 2, 3, 4]) → [3, -1]"],
          hint: "Walk weights with a stack. While the stack's top is smaller than the current value, pop it and record current as its answer in a dictionary. Push the current value. Anything left on the stack gets -1.",
          check: "assert next_greater([4, 1, 2], [1, 3, 4, 2]) == [-1, 3, -1], f'Got {next_greater([4, 1, 2], [1, 3, 4, 2])}'\nassert next_greater([2, 4], [1, 2, 3, 4]) == [3, -1]\nassert next_greater([1], [1]) == [-1]",
          solution: "def next_greater(query, weights):\n    answer = {}\n    stack = []\n    for w in weights:\n        while stack and stack[-1] < w:\n            answer[stack.pop()] = w\n        stack.append(w)\n    for w in stack:\n        answer[w] = -1\n    return [answer[q] for q in query]" },
        { id: "ja4", title: "Is the chain a loop?",
          say: "Linked list plus set. If a chain loops back on itself, walking it never ends. Remember every node you've visited; if you see one twice, it's a loop.",
          task: "Write a function called `has_loop` that takes in the head of a linked list and returns True if following `.next` pointers ever revisits a node.",
          prelude: LIST,
          examples: ["h = build_list([1, 2, 3]); h.next.next.next = h.next   (3 points back to 2)\nhas_loop(h) → True", "has_loop(build_list([1, 2, 3])) → False"],
          hint: "Put each node (the node itself, not its value) in a set as you walk. Values can repeat without a loop; nodes can't.",
          check: "h = build_list([1, 2, 3]); h.next.next.next = h.next\nassert has_loop(h) is True, 'The last node points back to the second: that is a loop.'\nassert has_loop(build_list([1, 2, 3])) is False\nassert has_loop(build_list([1, 1, 1])) is False, 'Repeated values are not a loop — track nodes, not values.'\nassert has_loop(None) is False",
          solution: "def has_loop(head):\n    seen = set()\n    node = head\n    while node:\n        if node in seen:\n            return True\n        seen.add(node)\n        node = node.next\n    return False" },
        { id: "ja5", title: "Level by level",
          say: "Tree plus queue. To read a tree one level at a time, put the root in a queue; then repeatedly take out everything currently in the queue (that's one level) and add their children.",
          task: "Write a function called `levels` that takes in the root of a tree and returns a list of lists, one inner list per level from top to bottom, each holding that level's values left to right.",
          prelude: TREE,
          examples: ["levels(build_tree([3, 9, 20, None, None, 15, 7])) → [[3], [9, 20], [15, 7]]", "levels(None) → []"],
          hint: "q = deque([root]). While q: n = len(q); take n nodes with popleft, collect their values into one list, and append their children.",
          check: "assert 'deque' in _src, 'Use a deque as the queue.'\nassert levels(build_tree([3, 9, 20, None, None, 15, 7])) == [[3], [9, 20], [15, 7]], f'Got {levels(build_tree([3, 9, 20, None, None, 15, 7]))}'\nassert levels(None) == []\nassert levels(build_tree([1, 2, None, 3])) == [[1], [2], [3]]",
          solution: "from collections import deque\n\ndef levels(root):\n    if root is None:\n        return []\n    result = []\n    q = deque([root])\n    while q:\n        level = []\n        for _ in range(len(q)):\n            node = q.popleft()\n            level.append(node.val)\n            if node.left:\n                q.append(node.left)\n            if node.right:\n                q.append(node.right)\n        result.append(level)\n    return result" },
        { id: "ja6", title: "Is there a path?",
          say: "Graph plus queue plus set. Breadth-first search: start at the source, visit neighbours, and keep a set of where you've been so you never go in circles.",
          task: "Write a function called `path_exists` that takes in a number of nodes n (numbered 0 to n-1), a list of edges (each a two-element list meaning the two nodes are connected both ways), a start node and a goal node. Return True if you can travel from start to goal.",
          examples: ["path_exists(3, [[0, 1], [1, 2], [2, 0]], 0, 2) → True", "path_exists(6, [[0, 1], [0, 2], [3, 5], [5, 4], [4, 3]], 0, 5) → False"],
          hint: "Build a dictionary from node to its neighbours (add both directions). BFS with a deque and a visited set; return True the moment you pop the goal.",
          check: "assert path_exists(3, [[0, 1], [1, 2], [2, 0]], 0, 2) is True\nassert path_exists(6, [[0, 1], [0, 2], [3, 5], [5, 4], [4, 3]], 0, 5) is False, 'Nodes 0 and 5 are in different groups.'\nassert path_exists(1, [], 0, 0) is True, 'Start equals goal: True.'\nassert path_exists(4, [[0, 1], [2, 3]], 1, 0) is True, 'Edges go both ways.'",
          solution: "from collections import deque\n\ndef path_exists(n, edges, start, goal):\n    graph = {i: [] for i in range(n)}\n    for a, b in edges:\n        graph[a].append(b)\n        graph[b].append(a)\n    seen = {start}\n    q = deque([start])\n    while q:\n        node = q.popleft()\n        if node == goal:\n            return True\n        for nxt in graph[node]:\n            if nxt not in seen:\n                seen.add(nxt)\n                q.append(nxt)\n    return False" },
        { id: "ja7", title: "Queue from two stacks",
          say: "Two stacks can act as a queue. Push onto the first. To pop, if the second stack is empty, pour everything from the first into it — that reverses the order, so its top is now the oldest item.",
          task: "Make a class called `StackQueue` using two Python lists as stacks, with methods `push(x)`, `pop()` (removes and returns the oldest item) and `peek()` (returns the oldest without removing it). Don't use deque or list.pop(0) / insert(0, …).",
          examples: ["q = StackQueue()\nq.push(1); q.push(2); q.push(3)\nq.pop() → 1\nq.push(4)\nq.peek() → 2\nq.pop() → 2\nq.pop() → 3\nq.pop() → 4"],
          check: "assert 'deque' not in _src and 'pop(0)' not in _src and 'insert(0' not in _src, 'Only two stacks: append and pop() from the end.'\nq = StackQueue()\nq.push(1); q.push(2); q.push(3)\nassert q.pop() == 1, 'The first pushed should come out first.'\nq.push(4)\nassert q.peek() == 2 and q.pop() == 2 and q.pop() == 3 and q.pop() == 4, 'Items pushed after a pop must still come out in order.'",
          solution: "class StackQueue:\n    def __init__(self):\n        self.inbox = []\n        self.outbox = []\n\n    def _shift(self):\n        if not self.outbox:\n            while self.inbox:\n                self.outbox.append(self.inbox.pop())\n\n    def push(self, x):\n        self.inbox.append(x)\n\n    def pop(self):\n        self._shift()\n        return self.outbox.pop()\n\n    def peek(self):\n        self._shift()\n        return self.outbox[-1]" },
        { id: "ja8", title: "Two-sum in a tree",
          say: "Tree plus set. Walk every node; for each value, check whether target minus value has already been seen. Any traversal order works.",
          task: "Write a function called `tree_pair` that takes in the root of a tree and a target, and returns True if two different nodes have values that add up to the target.",
          prelude: TREE,
          examples: ["tree_pair(build_tree([5, 3, 6, 2, 4, None, 7]), 9) → True   (2 + 7, or 3 + 6)", "tree_pair(build_tree([5, 3, 6, 2, 4, None, 7]), 28) → False", "tree_pair(build_tree([4]), 8) → False   (one node can't pair with itself)"],
          hint: "Recursive walk carrying a set. At each node: if target - node.val in seen, return True; add node.val; recurse into children.",
          check: "t = build_tree([5, 3, 6, 2, 4, None, 7])\nassert tree_pair(t, 9) is True\nassert tree_pair(t, 28) is False\nassert tree_pair(build_tree([4]), 8) is False, 'A single node cannot pair with itself.'\nassert tree_pair(None, 0) is False",
          solution: "def tree_pair(root, target):\n    seen = set()\n\n    def walk(node):\n        if node is None:\n            return False\n        if target - node.val in seen:\n            return True\n        seen.add(node.val)\n        return walk(node.left) or walk(node.right)\n\n    return walk(root)" },
        { id: "ja9", title: "Shortest escape",
          say: "Grid plus queue. Breadth-first search finds the shortest path in a maze: explore all cells 1 step away, then 2, then 3. The first time you reach the exit, that's the shortest distance.",
          task: "Write a function called `shortest_path` that takes in a grid (0 = open, 1 = wall), a start cell and a goal cell (each `(row, col)`), and returns the fewest up/down/left/right moves from start to goal, or -1 if the goal can't be reached.",
          examples: ["grid = [[0, 0, 0],\n        [1, 1, 0],\n        [0, 0, 0]]\nshortest_path(grid, (0, 0), (2, 0)) → 6", "shortest_path([[0, 1], [1, 0]], (0, 0), (1, 1)) → -1"],
          hint: "Queue of (row, col, distance). Visited set. Pop; if it's the goal return the distance; otherwise push in-bounds, open, unvisited neighbours with distance + 1.",
          check: "assert 'deque' in _src, 'Use a deque for breadth-first search.'\ng = [[0, 0, 0], [1, 1, 0], [0, 0, 0]]\nassert shortest_path(g, (0, 0), (2, 0)) == 6, f'Got {shortest_path(g, (0, 0), (2, 0))}, expected 6 (around the wall).'\nassert shortest_path([[0, 1], [1, 0]], (0, 0), (1, 1)) == -1, 'Blocked by walls: -1.'\nassert shortest_path([[0]], (0, 0), (0, 0)) == 0",
          solution: "from collections import deque\n\ndef shortest_path(grid, start, goal):\n    rows = len(grid)\n    cols = len(grid[0])\n    q = deque([(start[0], start[1], 0)])\n    seen = {start}\n    while q:\n        r, c, dist = q.popleft()\n        if (r, c) == goal:\n            return dist\n        for dr, dc in [(-1, 0), (1, 0), (0, -1), (0, 1)]:\n            nr = r + dr\n            nc = c + dc\n            if 0 <= nr < rows and 0 <= nc < cols and grid[nr][nc] == 0 and (nr, nc) not in seen:\n                seen.add((nr, nc))\n                q.append((nr, nc, dist + 1))\n    return -1" },
        { id: "ja10", title: "Coins for the ramen",
          say: "Dynamic programming with a table. Given coin values, what's the fewest coins that make an amount? For every amount from 1 up, the best is 1 plus the best for (amount minus some coin).",
          task: "Write a function called `fewest_coins` that takes in a list of coin values and a target amount and returns the fewest coins needed to make exactly that amount, or -1 if it can't be made. You have unlimited coins of each value.",
          examples: ["fewest_coins([1, 2, 5], 11) → 3   (5 + 5 + 1)", "fewest_coins([2], 3) → -1", "fewest_coins([1], 0) → 0"],
          hint: "dp = [big] * (amount + 1); dp[0] = 0. For a in 1..amount, for each coin ≤ a: dp[a] = min(dp[a], dp[a - coin] + 1). Return dp[amount] unless it's still big.",
          check: "assert fewest_coins([1, 2, 5], 11) == 3, f'Got {fewest_coins([1, 2, 5], 11)}, expected 3.'\nassert fewest_coins([2], 3) == -1, 'Odd amounts cannot be made from 2s.'\nassert fewest_coins([1], 0) == 0\nassert fewest_coins([1, 3, 4], 6) == 2, 'Greedy (4 + 1 + 1) is wrong here; the answer is 3 + 3.'",
          solution: "def fewest_coins(coins, amount):\n    big = amount + 1\n    dp = [big] * (amount + 1)\n    dp[0] = 0\n    for a in range(1, amount + 1):\n        for coin in coins:\n            if coin <= a:\n                dp[a] = min(dp[a], dp[a - coin] + 1)\n    if dp[amount] == big:\n        return -1\n    return dp[amount]" }
      ]}
    ]}
  ];
})();
