/* Academy curriculum, taught by Iruka-sensei. Four ranks:
     D  Ninja History      — multiple choice: predict the output of a snippet
     C  Weapon Handling    — one concept at a time, written from scratch
     B  Chakra Control     — several concepts combined
     A  Tactics & Formation— array problems that need a plan before code
   Code problems may give `starter` lines (data to work with, or a buggy program to repair); the logic is the student's. `check` is Python that runs in the
   student's namespace afterwards, with `_out` (what they printed) and `_src` (their source).
   Raise AssertionError("message") to fail; finishing cleanly passes. Every problem has a `solution`.
   Multiple choice (`type: "mc"`): `code`, `question`, `choices`, `answer` (index), `explain`.
   Type the output (`type: "output"`): `code`, `question`, `expected` (exact printed text), `explain`.
   Bug hunt (`type: "bug"`): a code problem whose `starter` is the broken program. */
window.LESSONS = [
  /* ============================ D-RANK ============================ */
  { id: "D", rank: "D", title: "Ninja History", kanji: "史",
    intro: "Before you throw a kunai you learn how one flies. Read each snippet and tell me what it prints — pick from a list, or type the exact output yourself. No running it; reason it out like reading an enemy's hand signs.",
    topics: [
      { id: "d-vars", title: "Variables & arithmetic", problems: [
        { id: "d1", type: "mc", title: "Floor and remainder",
          code: "kunai = 7\nsquads = 2\nprint(kunai // squads, kunai % squads)",
          question: "What does this print?",
          choices: ["3.5 1", "3 1", "3 0", "4 1"], answer: 1,
          explain: "// is floor division (7 // 2 = 3) and % is the remainder (7 % 2 = 1). print separates its arguments with a space." },
        { id: "d2", type: "output", title: "String arithmetic",
          code: "name = 'Naruto'\nprint(len(name) + 1)\nprint(name * 2)",
          question: "What does this print?",
          expected: "7\nNarutoNaruto",
          explain: "len('Naruto') is 6, plus 1 is 7. Multiplying a string by 2 repeats it with no space." },
        { id: "d3", type: "mc", title: "Copy of a number",
          code: "a = 5\nb = a\na = 10\nprint(b)",
          question: "What does this print?",
          choices: ["10", "5", "15", "an error"], answer: 1,
          explain: "b = a copies the value 5 into b. Reassigning a later doesn't touch b — numbers aren't shared, unlike lists." },
        { id: "d4", type: "mc", title: "Truth and comparison",
          code: "chakra = 40\nprint(chakra > 30 and chakra < 35)\nprint(chakra > 30 or chakra < 35)",
          question: "What does this print?",
          choices: ["True\nTrue", "False\nFalse", "False\nTrue", "True\nFalse"], answer: 2,
          explain: "40 > 30 is True but 40 < 35 is False. `and` needs both (False); `or` needs one (True)." }
      ]},
      { id: "d-loops", title: "Loops", problems: [
        { id: "d5", type: "output", title: "Range doubled",
          code: "for i in range(3):\n    print(i * 2)",
          question: "What does this print?",
          expected: "0\n2\n4",
          explain: "range(3) gives 0, 1, 2. Doubled: 0, 2, 4, each on its own line." },
        { id: "d6", type: "mc", title: "Even rewards",
          code: "total = 0\nfor n in [1, 2, 3, 4, 5, 6]:\n    if n % 2 == 0:\n        total += n\nprint(total)",
          question: "What does this print?",
          choices: ["21", "9", "12", "6"], answer: 2,
          explain: "Only even numbers are added: 2 + 4 + 6 = 12." },
        { id: "d7", type: "output", title: "Tripling while",
          code: "n = 1\nwhile n < 20:\n    n *= 3\nprint(n)",
          question: "What does this print?",
          expected: "27",
          explain: "n goes 1 → 3 → 9 → 27. At 27 the condition n < 20 is false, so the loop stops and prints 27." },
        { id: "d8", type: "mc", title: "Break out",
          code: "for name in ['Kiba', 'Shino', 'Hinata', 'Kurenai']:\n    if name == 'Hinata':\n        break\n    print(name)",
          question: "What does this print?",
          choices: ["Kiba\nShino", "Kiba\nShino\nHinata", "Hinata", "Kiba\nShino\nKurenai"], answer: 0,
          explain: "break leaves the loop the moment it runs. Hinata triggers it before being printed, and Kurenai is never reached." }
      ]},
      { id: "d-funcs", title: "Functions", problems: [
        { id: "d9", type: "output", title: "Nested call",
          code: "def boost(x):\n    return x + 1\n\nprint(boost(boost(2)))",
          question: "What does this print?",
          expected: "4",
          explain: "The inner call boost(2) returns 3, then boost(3) returns 4." },
        { id: "d10", type: "mc", title: "Default parameter",
          code: "def greet(name='shinobi'):\n    return 'Hi ' + name\n\nprint(greet())\nprint(greet('Iruka'))",
          question: "What does this print?",
          choices: ["Hi\nHi Iruka", "Hi shinobi\nHi Iruka", "Hi name\nHi Iruka", "an error"], answer: 1,
          explain: "With no argument the default 'shinobi' is used; passing 'Iruka' overrides it." },
        { id: "d11", type: "mc", title: "Return ends it",
          code: "def rank(score):\n    if score > 80:\n        return 'Jonin'\n    return 'Genin'\n    print('done')\n\nprint(rank(90))",
          question: "What does this print?",
          choices: ["Jonin\ndone", "Jonin", "Genin", "done"], answer: 1,
          explain: "return hands the value back immediately. Code after a return that runs never executes, so 'done' is never printed." },
        { id: "d12", type: "output", title: "Lists passed to functions",
          code: "def recruit(team):\n    team.append('Sai')\n\nsquad = ['Naruto', 'Sakura']\nrecruit(squad)\nprint(len(squad))",
          question: "What does this print?",
          expected: "3",
          explain: "The function receives the same list, not a copy, so appending inside it changes squad. It now has 3 names." }
      ]},
      { id: "d-classes", title: "Classes", problems: [
        { id: "d13", type: "mc", title: "Attribute change",
          code: "class Ninja:\n    def __init__(self, rank):\n        self.rank = rank\n\nn = Ninja('Genin')\nn.rank = 'Chunin'\nprint(n.rank)",
          question: "What does this print?",
          choices: ["Genin", "Chunin", "rank", "an error"], answer: 1,
          explain: "Attributes can be reassigned after creation. The last value written wins." },
        { id: "d14", type: "mc", title: "Inherited method",
          code: "class Shinobi:\n    def jutsu(self):\n        return 'Substitution'\n\nclass Uchiha(Shinobi):\n    pass\n\nprint(Uchiha().jutsu())",
          question: "What does this print?",
          choices: ["an error", "None", "Substitution", "pass"], answer: 2,
          explain: "Uchiha adds nothing (pass) but inherits jutsu() from Shinobi, so the call works and returns 'Substitution'." },
        { id: "d15", type: "mc", title: "Override with super",
          code: "class Shinobi:\n    def jutsu(self):\n        return 'Clone'\n\nclass Uchiha(Shinobi):\n    def jutsu(self):\n        return 'Fireball + ' + super().jutsu()\n\nprint(Uchiha().jutsu())",
          question: "What does this print?",
          choices: ["Clone", "Fireball + Clone", "Fireball + ", "an error"], answer: 1,
          explain: "The subclass overrides jutsu() but calls the parent's version through super(), then joins the two strings." },
        { id: "d16", type: "output", title: "Two objects",
          code: "class Counter:\n    def __init__(self):\n        self.n = 0\n    def hit(self):\n        self.n += 1\n\na = Counter()\nb = Counter()\na.hit(); a.hit(); b.hit()\nprint(a.n, b.n)",
          question: "What does this print?",
          expected: "2 1",
          explain: "Each object has its own self.n. a was hit twice and b once; they don't share state." }
      ]}
    ]},

  /* ============================ C-RANK ============================ */
  { id: "C", rank: "C", title: "Weapon Handling", kanji: "器",
    intro: "One weapon at a time. Each problem uses a single concept. Sometimes I hand you the data; the logic is always yours. Read the task carefully: names and values must match exactly.",
    topics: [
      { id: "c-vars", title: "Variables & types", problems: [
        { id: "c1", title: "Registration card",
          say: "Every shinobi has a record. Make one from scratch — four variables, four types.",
          task: "Create `name` (a string of your choosing), `age` (an int), `height` (a float) and `is_genin` (a bool). Print `name`.",
          check: "for n in ['name','age','height','is_genin']: assert n in dir(), f'Missing variable {n}.'\nassert type(name) is str and type(age) is int and type(height) is float and type(is_genin) is bool, 'Check each type: str, int, float, bool.'\nassert name in _out, 'Print name.'",
          solution: "name = 'Rock Lee'\nage = 13\nheight = 1.58\nis_genin = True\nprint(name)" },
        { id: "c2", title: "Chakra math",
          say: "Set `chakra` to 120 and `cost` to 35. Print how many jutsu you can cast and how much chakra is left over.",
          task: "Create `chakra = 120` and `cost = 35`. Print `chakra // cost` on one line, then `chakra % cost` on the next.",
          check: "assert chakra == 120 and cost == 35, 'Use chakra = 120 and cost = 35.'\nlines = [l.strip() for l in _out.strip().splitlines()]\nassert lines[:2] == ['3', '15'], f'Expected 3 then 15, got {lines[:2]}'",
          solution: "chakra = 120\ncost = 35\nprint(chakra // cost)\nprint(chakra % cost)" },
        { id: "c3", title: "Building a sentence",
          say: "Strings join with +. Build an introduction from parts, then print it.",
          task: "Create `first = 'Hatake'` and `last = 'Kakashi'`, then build `intro` equal to `'Hatake Kakashi, Jonin'` using + (and a space) and print it.",
          check: "assert intro == 'Hatake Kakashi, Jonin', f'intro is {intro!r}'\nassert '+' in _src, 'Join the strings with +.'\nassert 'Hatake Kakashi, Jonin' in _out",
          solution: "first = 'Hatake'\nlast = 'Kakashi'\nintro = first + ' ' + last + ', Jonin'\nprint(intro)" }
      ]},
      { id: "c-lists", title: "Lists (arrays)", problems: [
        { id: "c4", starter: "pouch = ['steel', 'iron', 'bronze', 'silver', 'gold']\n", title: "Kunai pouch",
          say: "Make a list of five kunai types and print the third. Zero-based — the third item is index 2.",
          task: "Create a list `pouch` with the strings `'steel'`, `'iron'`, `'bronze'`, `'silver'`, `'gold'` in that order. Print the third item.",
          check: "assert pouch == ['steel','iron','bronze','silver','gold'], 'pouch should hold exactly those five strings in order.'\nassert _out.strip() == 'bronze', 'Print the third item: bronze'",
          solution: "pouch = ['steel', 'iron', 'bronze', 'silver', 'gold']\nprint(pouch[2])" },
        { id: "c5", starter: "squad = ['Naruto', 'Sasuke', 'Sakura']\n", title: "Growing the squad",
          say: "Start with Team 7 and add two members with append. Then print the length.",
          task: "Create `squad = ['Naruto', 'Sasuke', 'Sakura']`, append `'Kakashi'` then `'Sai'`, and print `len(squad)`.",
          check: "assert squad == ['Naruto','Sasuke','Sakura','Kakashi','Sai'], f'squad is {squad}'\nassert '.append(' in _src, 'Use append.'\nassert _out.strip().endswith('5')",
          solution: "squad = ['Naruto', 'Sasuke', 'Sakura']\nsquad.append('Kakashi')\nsquad.append('Sai')\nprint(len(squad))" },
        { id: "c6", starter: "ranks = ['Genin', 'Chunin', 'Jonin', 'Anbu', 'Kage']\n", title: "Last and middle",
          say: "Negative indexes count from the end, and slices take a range. Show me both.",
          task: "Create `ranks = ['Genin', 'Chunin', 'Jonin', 'Anbu', 'Kage']`. Print the last item using a negative index, then print the slice `ranks[1:4]`.",
          check: "lines = [l.strip() for l in _out.strip().splitlines()]\nassert lines[0] == 'Kage', 'First line should be Kage.'\nassert '[-1]' in _src, 'Use a negative index for the last item.'\nassert lines[1] == \"['Chunin', 'Jonin', 'Anbu']\", f'Second line should be the slice, got {lines[1]!r}'",
          solution: "ranks = ['Genin', 'Chunin', 'Jonin', 'Anbu', 'Kage']\nprint(ranks[-1])\nprint(ranks[1:4])" }
      ]},
      { id: "c-for", title: "For loops", problems: [
        { id: "c7", starter: "students = ['Naruto', 'Hinata', 'Shikamaru', 'Choji']\n", title: "Roll call",
          say: "Print each name in the class on its own line with a for loop.",
          task: "Create `students = ['Naruto', 'Hinata', 'Shikamaru', 'Choji']` and print each one on its own line.",
          check: "lines = [l.strip() for l in _out.strip().splitlines()]\nassert 'for' in _src, 'Use a for loop.'\nassert lines == ['Naruto','Hinata','Shikamaru','Choji'], f'Got {lines}'",
          solution: "students = ['Naruto', 'Hinata', 'Shikamaru', 'Choji']\nfor s in students:\n    print(s)" },
        { id: "c8", title: "Lap counter",
          say: "Guy-sensei's warm-up: print 1 to 10 using range. Remember range stops before its end value.",
          task: "Print the numbers 1 through 10, one per line, with `for` and `range`.",
          check: "lines = [l.strip() for l in _out.strip().splitlines()]\nassert 'range(' in _src, 'Use range.'\nassert lines == [str(i) for i in range(1, 11)], f'Got {lines}'",
          solution: "for i in range(1, 11):\n    print(i)" },
        { id: "c9", starter: "rewards = [5000, 3000, 30000, 150000]\ntotal = 0\n", title: "Mission payroll",
          say: "Add up the rewards with a loop and a running total. No sum() — I want to see the accumulation.",
          task: "Create `rewards = [5000, 3000, 30000, 150000]`. Use a for loop to add them into `total`, then print `total`.",
          check: "assert 'for' in _src and 'sum(' not in _src, 'Use a for loop, not sum().'\nassert total == 188000, f'total should be 188000, got {total}'\nassert '188000' in _out",
          solution: "rewards = [5000, 3000, 30000, 150000]\ntotal = 0\nfor r in rewards:\n    total += r\nprint(total)" }
      ]},
      { id: "c-while", title: "While loops", problems: [
        { id: "c10", title: "Countdown",
          say: "Count down from 5 to 1 with a while loop, then print Go!",
          task: "Using `while`, print 5, 4, 3, 2, 1 on separate lines, then `Go!`.",
          check: "assert 'while' in _src, 'Use a while loop.'\nlines = [l.strip() for l in _out.strip().splitlines()]\nassert lines == ['5','4','3','2','1','Go!'], f'Got {lines}'",
          solution: "n = 5\nwhile n > 0:\n    print(n)\n    n -= 1\nprint('Go!')" },
        { id: "c11", title: "Chakra doubling",
          say: "Start at 1 and double until you reach at least 1000. How many doublings did it take?",
          task: "Create `chakra = 1` and `doublings = 0`. While `chakra < 1000`, double chakra and count. Print `doublings`.",
          check: "assert 'while' in _src, 'Use a while loop.'\nassert doublings == 10, f'It takes 10 doublings, you got {doublings}'\nassert '10' in _out",
          solution: "chakra = 1\ndoublings = 0\nwhile chakra < 1000:\n    chakra *= 2\n    doublings += 1\nprint(doublings)" },
        { id: "c12", starter: "names = ['Kabuto', 'Mizuki', 'Orochimaru', 'Danzo']\n", title: "Find the traitor",
          say: "Search a list with a while loop and stop as soon as you find the target. Print the index where you stopped.",
          task: "Create `names = ['Kabuto', 'Mizuki', 'Orochimaru', 'Danzo']`. Use a `while` loop to find the index of `'Orochimaru'` and print it.",
          check: "assert 'while' in _src and '.index(' not in _src, 'Use a while loop, not .index().'\nassert _out.strip() == '2', 'Orochimaru is at index 2.'",
          solution: "names = ['Kabuto', 'Mizuki', 'Orochimaru', 'Danzo']\ni = 0\nwhile names[i] != 'Orochimaru':\n    i += 1\nprint(i)" }
      ]},
      { id: "c-funcs", title: "Functions", problems: [
        { id: "c13", title: "Greeting jutsu",
          say: "A function that returns a greeting — returns it, doesn't print it.",
          task: "Define `greet(name)` that returns `'Welcome to the Leaf, ' + name + '!'`.",
          check: "assert callable(greet), 'Define greet.'\nassert greet('Naruto') == 'Welcome to the Leaf, Naruto!', f'greet(\"Naruto\") returned {greet(\"Naruto\")!r}'",
          solution: "def greet(name):\n    return 'Welcome to the Leaf, ' + name + '!'" },
        { id: "c14", title: "Training ground area",
          say: "Two parameters in, one number out.",
          task: "Define `area(width, height)` that returns their product.",
          check: "assert area(3, 4) == 12 and area(2.5, 2) == 5.0, 'area should return width * height.'",
          solution: "def area(width, height):\n    return width * height" },
        { id: "c15", starter: "RANKS = ['Academy', 'Genin', 'Chunin', 'Jonin', 'Kage']\n\n", title: "Rank up with a default",
          say: "Parameters can have defaults. Climb the ranks list by a number of steps, one by default.",
          task: "Define `RANKS = ['Academy', 'Genin', 'Chunin', 'Jonin', 'Kage']` and `rank_up(rank, steps=1)` returning the rank `steps` positions after `rank`.",
          check: "assert rank_up('Genin') == 'Chunin', 'rank_up(\"Genin\") should be \"Chunin\".'\nassert rank_up('Genin', 2) == 'Jonin', 'rank_up(\"Genin\", 2) should be \"Jonin\".'",
          solution: "RANKS = ['Academy', 'Genin', 'Chunin', 'Jonin', 'Kage']\n\ndef rank_up(rank, steps=1):\n    return RANKS[RANKS.index(rank) + steps]" }
      ]},
      { id: "c-classes", title: "Classes", problems: [
        { id: "c16", title: "A Shinobi class",
          say: "Blueprint time. Store name and rank, and add a method that introduces the shinobi.",
          task: "Define class `Shinobi` with `__init__(self, name, rank)` storing both, and `introduce()` returning `'<name>, <rank> of the Leaf'`.",
          check: "s = Shinobi('Iruka', 'Chunin')\nassert s.name == 'Iruka' and s.rank == 'Chunin', 'Store name and rank on self.'\nassert s.introduce() == 'Iruka, Chunin of the Leaf', f'introduce() returned {s.introduce()!r}'",
          solution: "class Shinobi:\n    def __init__(self, name, rank):\n        self.name = name\n        self.rank = rank\n\n    def introduce(self):\n        return self.name + ', ' + self.rank + ' of the Leaf'" },
        { id: "c17", title: "Mission counter",
          say: "Objects remember things. Count completed missions on the object itself.",
          task: "Define class `Shinobi` with `__init__(self, name)` that sets `name` and `missions = 0`, and `complete_mission()` that adds one to `missions`.",
          check: "s = Shinobi('Lee')\nassert s.missions == 0, 'missions should start at 0.'\ns.complete_mission(); s.complete_mission()\nassert s.missions == 2, 'complete_mission() should add one each call.'",
          solution: "class Shinobi:\n    def __init__(self, name):\n        self.name = name\n        self.missions = 0\n\n    def complete_mission(self):\n        self.missions += 1" }
      ]},
      { id: "c-inherit", title: "Inheritance", problems: [
        { id: "c18", title: "Jonin is a Shinobi",
          say: "Write the parent, then a child that fixes the rank and passes the name up with super().",
          task: "Define `Shinobi` with `__init__(self, name, rank)` storing both. Then define `Jonin(Shinobi)` whose `__init__(self, name)` calls `super().__init__(name, 'Jonin')`.",
          check: "k = Jonin('Kakashi')\nassert isinstance(k, Shinobi), 'Jonin should inherit from Shinobi.'\nassert k.name == 'Kakashi' and k.rank == 'Jonin'\nassert 'super()' in _src, 'Use super().__init__.'",
          solution: "class Shinobi:\n    def __init__(self, name, rank):\n        self.name = name\n        self.rank = rank\n\nclass Jonin(Shinobi):\n    def __init__(self, name):\n        super().__init__(name, 'Jonin')" },
        { id: "c19", title: "Override introduce",
          say: "A child can replace a parent's method entirely.",
          task: "Define `Shinobi` with `__init__(self, name)` and `introduce()` returning the name. Define `Hokage(Shinobi)` whose `introduce()` returns `'Lord <name>, Hokage'`.",
          check: "h = Hokage('Tsunade')\nassert isinstance(h, Shinobi)\nassert h.introduce() == 'Lord Tsunade, Hokage', f'Got {h.introduce()!r}'\nassert Shinobi('Iruka').introduce() == 'Iruka', 'The parent introduce() should still return just the name.'",
          solution: "class Shinobi:\n    def __init__(self, name):\n        self.name = name\n\n    def introduce(self):\n        return self.name\n\nclass Hokage(Shinobi):\n    def introduce(self):\n        return 'Lord ' + self.name + ', Hokage'" }
      ]},
      { id: "c-imports", title: "Imports & libraries", problems: [
        { id: "c20", title: "Square root",
          say: "The math scroll has sqrt. Import it and use it.",
          task: "Import `math` and print `math.sqrt(144)`.",
          check: "assert 'import math' in _src, 'Import math.'\nassert '12' in _out, 'math.sqrt(144) is 12.0'",
          solution: "import math\nprint(math.sqrt(144))" },
        { id: "c21", starter: "names = ['Naruto', 'Sasuke', 'Sakura']\n", title: "Random pick",
          say: "Pull just one tool from a scroll with from ... import.",
          task: "Create `names = ['Naruto', 'Sasuke', 'Sakura']`. Use `from random import choice` and print `choice(names)`.",
          check: "assert 'from random import' in _src, 'Use from random import choice.'\nassert _out.strip() in names, 'Print one of the names.'",
          solution: "from random import choice\nnames = ['Naruto', 'Sasuke', 'Sakura']\nprint(choice(names))" }
      ]},
      { id: "c-copies", title: "Copies & references", problems: [
        { id: "c22", starter: "original = ['Naruto']\nclone = original\n", title: "Shadow clone",
          say: "Two names, one list. Append through the clone and print the original — see what happens.",
          task: "Create `original = ['Naruto']` and `clone = original`. Append `'Sasuke'` to `clone`, then print `original`.",
          check: "assert original == ['Naruto', 'Sasuke'] and clone is original, 'clone = original makes both names point at one list.'\nassert \"['Naruto', 'Sasuke']\" in _out",
          solution: "original = ['Naruto']\nclone = original\nclone.append('Sasuke')\nprint(original)" },
        { id: "c23", starter: "original = ['Naruto']\n", title: "A true copy",
          say: "Now make a real copy so the original is safe.",
          task: "Create `original = ['Naruto']` and `copy` as a real copy of it (`list(original)` or `.copy()`). Append `'Sasuke'` to `copy`, then print `original`.",
          check: "assert copy == ['Naruto', 'Sasuke'] and original == ['Naruto'], 'original must stay unchanged.'\nassert copy is not original\nassert \"['Naruto']\" in _out",
          solution: "original = ['Naruto']\ncopy = original.copy()\ncopy.append('Sasuke')\nprint(original)" }
      ]},
      { id: "c-bugs", title: "Field repairs (find the bug)", problems: [
        { id: "c24", type: "bug", title: "Off by one",
          say: "This roll call is supposed to print all four students, but one is missing. Find the bug and fix it — change as little as you can.",
          task: "Fix the code so it prints all four names, one per line.",
          starter: "students = ['Naruto', 'Hinata', 'Shikamaru', 'Choji']\nfor i in range(len(students) - 1):\n    print(students[i])\n",
          check: "lines = [l.strip() for l in _out.strip().splitlines()]\nassert lines == ['Naruto','Hinata','Shikamaru','Choji'], f'Got {lines} — one name is still missing.'",
          solution: "students = ['Naruto', 'Hinata', 'Shikamaru', 'Choji']\nfor i in range(len(students)):\n    print(students[i])" },
        { id: "c25", type: "bug", title: "The loop that never ends",
          say: "Careful — as written this loops forever, so don't just run it. Read it, spot what never changes, and fix it.",
          task: "Fix the countdown so it prints 3, 2, 1 and then `Go!` and stops.",
          starter: "n = 3\nwhile n > 0:\n    print(n)\nprint('Go!')\n",
          check: "lines = [l.strip() for l in _out.strip().splitlines()]\nassert lines == ['3','2','1','Go!'], f'Got {lines}'",
          solution: "n = 3\nwhile n > 0:\n    print(n)\n    n -= 1\nprint('Go!')" },
        { id: "c26", type: "bug", title: "Silent function",
          say: "This function is meant to return the total, but the caller keeps getting None. Why?",
          task: "Fix `total_chakra` so that `print(total_chakra([10, 20, 30]))` prints 60.",
          starter: "def total_chakra(values):\n    total = 0\n    for v in values:\n        total += v\n    print(total)\n\nresult = total_chakra([10, 20, 30])\nprint(result)\n",
          check: "assert total_chakra([10, 20, 30]) == 60, 'total_chakra should return the total, not print it.'\nassert total_chakra([]) == 0",
          solution: "def total_chakra(values):\n    total = 0\n    for v in values:\n        total += v\n    return total\n\nresult = total_chakra([10, 20, 30])\nprint(result)" },
        { id: "c27", type: "bug", title: "Shared clone",
          say: "Two squads are supposed to be independent, but adding to one adds to both. Fix it so each squad has its own list.",
          task: "Fix the class so two `Squad` objects don't share members: `a.add('Naruto')` must leave `b.members` empty.",
          starter: "class Squad:\n    members = []\n\n    def add(self, name):\n        self.members.append(name)\n\na = Squad()\nb = Squad()\na.add('Naruto')\nprint(b.members)\n",
          check: "a = Squad(); b = Squad(); a.add('Naruto')\nassert a.members == ['Naruto'], 'a should have Naruto.'\nassert b.members == [], 'b should be empty — give each object its own list in __init__.'",
          solution: "class Squad:\n    def __init__(self):\n        self.members = []\n\n    def add(self, name):\n        self.members.append(name)\n\na = Squad()\nb = Squad()\na.add('Naruto')\nprint(b.members)" },
        { id: "c28", type: "bug", title: "Wrong comparison",
          say: "Students with 80 or more should pass, but the report is wrong for some of them. Read the condition carefully.",
          task: "Fix `grade` so scores of 80 and above return `'PASS'` and everything below returns `'FAIL'`.",
          starter: "def grade(score):\n    if score > 80:\n        return 'PASS'\n    else:\n        return 'FAIL'\n\nprint(grade(80))\n",
          check: "assert grade(80) == 'PASS', '80 should pass.'\nassert grade(79) == 'FAIL' and grade(95) == 'PASS'",
          solution: "def grade(score):\n    if score >= 80:\n        return 'PASS'\n    else:\n        return 'FAIL'\n\nprint(grade(80))" }
      ]}
    ]},

  /* ============================ B-RANK ============================ */
  { id: "B", rank: "B", title: "Chakra Control", kanji: "制",
    intro: "Now you combine weapons. Each problem needs two or three concepts working together. Plan the pieces, then write them.",
    topics: [
      { id: "b-all", title: "Combined techniques", problems: [
        { id: "b1", title: "Payout calculator",
          say: "Functions, loops and conditionals together. Missions pay by rank: D is 5000, C is 30000, B is 150000, A is 600000 ryō.",
          task: "Define `payout(ranks)` that takes a list of rank letters like `['D', 'C', 'D']` and returns the total pay. D=5000, C=30000, B=150000, A=600000.",
          check: "assert payout(['D']) == 5000\nassert payout(['D', 'C', 'D']) == 40000, 'D + C + D should be 40000.'\nassert payout(['A', 'B', 'C', 'D']) == 785000\nassert payout([]) == 0, 'An empty list pays 0.'",
          solution: "def payout(ranks):\n    total = 0\n    for r in ranks:\n        if r == 'D':\n            total += 5000\n        elif r == 'C':\n            total += 30000\n        elif r == 'B':\n            total += 150000\n        elif r == 'A':\n            total += 600000\n    return total" },
        { id: "b2", title: "Squad roster",
          say: "A class that holds a list and formats it. Numbered roster, one name per line.",
          task: "Define class `Squad` with `__init__(self)` creating an empty `members` list, `add(name)` appending to it, and `roster()` returning a string like `'1. Naruto\\n2. Sakura'` (numbered from 1, lines joined with newlines).",
          check: "s = Squad()\nassert s.members == [] and s.roster() == '', 'Empty squad: empty members, empty roster string.'\ns.add('Naruto'); s.add('Sakura'); s.add('Sai')\nassert s.members == ['Naruto', 'Sakura', 'Sai']\nassert s.roster() == '1. Naruto\\n2. Sakura\\n3. Sai', f'roster() returned {s.roster()!r}'",
          solution: "class Squad:\n    def __init__(self):\n        self.members = []\n\n    def add(self, name):\n        self.members.append(name)\n\n    def roster(self):\n        lines = []\n        for i in range(len(self.members)):\n            lines.append(str(i + 1) + '. ' + self.members[i])\n        return '\\n'.join(lines)" },
        { id: "b3", title: "Strongest on the team",
          say: "Inheritance plus a function over objects. Genin power is their chakra; Jonin power is double.",
          task: "Define `Shinobi` with `__init__(self, name, chakra)` and `power()` returning `chakra`. Define `Jonin(Shinobi)` overriding `power()` to return `chakra * 2`. Then define `strongest(team)` that returns the name of the member with the highest `power()`.",
          check: "team = [Shinobi('Naruto', 90), Jonin('Kakashi', 50), Shinobi('Sakura', 60)]\nassert Jonin('Kakashi', 50).power() == 100, 'Jonin power is chakra * 2.'\nassert strongest(team) == 'Kakashi', 'Kakashi (100) beats Naruto (90).'\nassert strongest([Shinobi('Naruto', 90), Jonin('Asuma', 40)]) == 'Naruto'",
          solution: "class Shinobi:\n    def __init__(self, name, chakra):\n        self.name = name\n        self.chakra = chakra\n\n    def power(self):\n        return self.chakra\n\nclass Jonin(Shinobi):\n    def power(self):\n        return self.chakra * 2\n\ndef strongest(team):\n    best = team[0]\n    for member in team:\n        if member.power() > best.power():\n            best = member\n    return best.name" },
        { id: "b4", title: "Training sessions",
          say: "A function with a while loop. Each session grows chakra by 10 percent, rounded down. How many sessions to reach the target?",
          task: "Define `sessions(start, target)` returning how many sessions it takes for `start` to reach at least `target`, where each session does `chakra = chakra + chakra // 10`. Return 0 if already there.",
          check: "assert sessions(100, 100) == 0\nassert sessions(100, 121) == 2, '100 → 110 → 121 is 2 sessions.'\nassert sessions(100, 200) == 8\nassert 'while' in _src, 'Use a while loop.'",
          solution: "def sessions(start, target):\n    chakra = start\n    count = 0\n    while chakra < target:\n        chakra = chakra + chakra // 10\n        count += 1\n    return count" },
        { id: "b5", title: "Jutsu scroll",
          say: "A class with a list that refuses duplicates, and a method that reports a count.",
          task: "Define class `Scroll` with an empty `jutsu` list; `learn(name)` appends only if it isn't already there and returns `True` if learned, `False` if already known; `count()` returns how many jutsu are stored.",
          check: "s = Scroll()\nassert s.learn('Rasengan') is True\nassert s.learn('Rasengan') is False, 'Learning the same jutsu twice should return False.'\nassert s.learn('Shadow Clone') is True\nassert s.count() == 2 and s.jutsu == ['Rasengan', 'Shadow Clone']",
          solution: "class Scroll:\n    def __init__(self):\n        self.jutsu = []\n\n    def learn(self, name):\n        if name in self.jutsu:\n            return False\n        self.jutsu.append(name)\n        return True\n\n    def count(self):\n        return len(self.jutsu)" },
        { id: "b6", title: "Filter by rank",
          say: "Two parallel lists and a loop that builds a new list. Position i in one list matches position i in the other.",
          task: "Define `with_rank(names, ranks, want)` where `names[i]` has rank `ranks[i]`. Return a new list of the names whose rank equals `want`, in order.",
          check: "n = ['Naruto', 'Shikamaru', 'Kakashi', 'Neji']\nr = ['Genin', 'Chunin', 'Jonin', 'Chunin']\nassert with_rank(n, r, 'Chunin') == ['Shikamaru', 'Neji']\nassert with_rank(n, r, 'Kage') == []\nassert with_rank(n, r, 'Genin') == ['Naruto']",
          solution: "def with_rank(names, ranks, want):\n    result = []\n    for i in range(len(names)):\n        if ranks[i] == want:\n            result.append(names[i])\n    return result" },
        { id: "b7", title: "Grade the exam",
          say: "Loop, conditionals and string building. Scores of 80 or more pass.",
          task: "Define `report(names, scores)` that returns a list of strings, one per student, formatted `'<name>: PASS'` or `'<name>: FAIL'` (80 and above passes). Also define `pass_rate(scores)` returning the fraction that passed as a float (0.0 for an empty list).",
          check: "assert report(['Naruto', 'Sakura'], [55, 95]) == ['Naruto: FAIL', 'Sakura: PASS']\nassert report(['Lee'], [80]) == ['Lee: PASS'], '80 passes.'\nassert pass_rate([55, 95, 80, 10]) == 0.5\nassert pass_rate([]) == 0.0",
          solution: "def report(names, scores):\n    lines = []\n    for i in range(len(names)):\n        if scores[i] >= 80:\n            lines.append(names[i] + ': PASS')\n        else:\n            lines.append(names[i] + ': FAIL')\n    return lines\n\ndef pass_rate(scores):\n    if len(scores) == 0:\n        return 0.0\n    passed = 0\n    for s in scores:\n        if s >= 80:\n            passed += 1\n    return passed / len(scores)" }
      ]}
    ]},

  /* ============================ A-RANK ============================ */
  { id: "A", rank: "A", title: "Tactics & Formation", kanji: "策",
    intro: "A-rank is about the plan, not the typing. Each of these has an obvious slow way and a clean way. Think about what you need to remember as you walk the list, write it, then test it on the examples.",
    topics: [
      { id: "a-all", title: "Array tactics", problems: [
        { id: "a1", title: "Chakra pair",
          say: "Two kunai whose weights add up to exactly the target. Return their positions. The slow way checks every pair; the fast way remembers what it has seen.",
          task: "Define `find_pair(weights, target)` returning a list of two indices `[i, j]` with `i < j` and `weights[i] + weights[j] == target`. There is exactly one answer.",
          hint: "For each weight, the partner you need is target - weight. Have you seen it already?",
          check: "assert find_pair([2, 7, 11, 15], 9) == [0, 1]\nassert find_pair([3, 2, 4], 6) == [1, 2]\nassert find_pair([5, 1, 9, 4], 13) == [2, 3]",
          solution: "def find_pair(weights, target):\n    seen = {}\n    for i in range(len(weights)):\n        need = target - weights[i]\n        if need in seen:\n            return [seen[need], i]\n        seen[weights[i]] = i" },
        { id: "a2", title: "Ramen trading",
          say: "Daily ramen prices. Buy one day, sell a later day, maximise profit. Track the cheapest day so far as you go.",
          task: "Define `best_profit(prices)` returning the maximum profit from buying on one day and selling on a later day. Return 0 if no profit is possible.",
          hint: "Walk left to right remembering the lowest price so far; today's best sale is today's price minus that low.",
          check: "assert best_profit([7, 1, 5, 3, 6, 4]) == 5, 'Buy at 1, sell at 6.'\nassert best_profit([7, 6, 4, 3, 1]) == 0, 'Prices only fall: 0.'\nassert best_profit([2, 4, 1]) == 2\nassert best_profit([5]) == 0",
          solution: "def best_profit(prices):\n    lowest = prices[0]\n    best = 0\n    for p in prices:\n        if p < lowest:\n            lowest = p\n        elif p - lowest > best:\n            best = p - lowest\n    return best" },
        { id: "a3", title: "Shadow clone check",
          say: "Is anyone on the roster listed twice? A set remembers who you've already seen.",
          task: "Define `has_duplicate(names)` returning `True` if any name appears more than once, else `False`.",
          check: "assert has_duplicate(['Naruto', 'Sasuke', 'Naruto']) is True\nassert has_duplicate(['Naruto', 'Sasuke', 'Sakura']) is False\nassert has_duplicate([]) is False",
          solution: "def has_duplicate(names):\n    seen = set()\n    for n in names:\n        if n in seen:\n            return True\n        seen.add(n)\n    return False" },
        { id: "a4", title: "Chakra surge",
          say: "Daily chakra changes, positive and negative. Find the best run of consecutive days. If the running total ever goes negative, it's dragging you down — drop it and start fresh.",
          task: "Define `best_surge(changes)` returning the largest sum of any contiguous run of the list (at least one element).",
          hint: "Keep a running sum; if it drops below zero reset it to zero. Track the best seen.",
          check: "assert best_surge([-2, 1, -3, 4, -1, 2, 1, -5, 4]) == 6, 'The run 4, -1, 2, 1 sums to 6.'\nassert best_surge([1]) == 1\nassert best_surge([-3, -1, -2]) == -1, 'All negative: the least bad single day.'\nassert best_surge([5, 4, -1, 7, 8]) == 23",
          solution: "def best_surge(changes):\n    best = changes[0]\n    running = 0\n    for c in changes:\n        running += c\n        if running > best:\n            best = running\n        if running < 0:\n            running = 0\n    return best" },
        { id: "a5", title: "Clear the field",
          say: "Shuriken that missed are recorded as 0. Move every 0 to the end, keep the hits in their original order, and do it in the same list.",
          task: "Define `clear_misses(hits)` that modifies the list in place so all zeros are at the end and the non-zeros keep their order. Return nothing.",
          hint: "Keep a write position. Walk the list; every non-zero gets written at the write position, which then moves forward. Fill the rest with zeros.",
          check: "a = [0, 1, 0, 3, 12]; clear_misses(a); assert a == [1, 3, 12, 0, 0], f'Got {a}'\nb = [0]; clear_misses(b); assert b == [0]\nc = [2, 0, 0, 5, 0, 7]; clear_misses(c); assert c == [2, 5, 7, 0, 0, 0]",
          solution: "def clear_misses(hits):\n    write = 0\n    for i in range(len(hits)):\n        if hits[i] != 0:\n            hits[write] = hits[i]\n            write += 1\n    while write < len(hits):\n        hits[write] = 0\n        write += 1" },
        { id: "a6", title: "Mirror jutsu",
          say: "A code word is a mirror if it reads the same backwards, ignoring case and anything that isn't a letter or digit. Two pointers walking inward is the clean way.",
          task: "Define `is_mirror(text)` returning `True` if `text` is a palindrome ignoring case and non-alphanumeric characters.",
          check: "assert is_mirror('A man, a plan, a canal: Panama') is True\nassert is_mirror('race a car') is False\nassert is_mirror('') is True\nassert is_mirror('Noon') is True",
          solution: "def is_mirror(text):\n    chars = []\n    for ch in text.lower():\n        if ch.isalnum():\n            chars.append(ch)\n    i = 0\n    j = len(chars) - 1\n    while i < j:\n        if chars[i] != chars[j]:\n            return False\n        i += 1\n        j -= 1\n    return True" },
        { id: "a7", title: "Clan vote",
          say: "One clan got more than half of all votes. Find it in a single pass without counting every clan separately. Think of it as a tug of war: keep a candidate and a count.",
          task: "Define `winner(votes)` returning the clan name that appears more than `len(votes) // 2` times. It always exists.",
          hint: "Candidate and counter. Same name: count up. Different: count down. At zero, the next name becomes the candidate.",
          check: "assert winner(['Uchiha', 'Hyuga', 'Uchiha']) == 'Uchiha'\nassert winner(['Nara', 'Nara', 'Uchiha', 'Nara', 'Hyuga', 'Nara', 'Nara']) == 'Nara'\nassert winner(['Senju']) == 'Senju'",
          solution: "def winner(votes):\n    candidate = None\n    count = 0\n    for v in votes:\n        if count == 0:\n            candidate = v\n        if v == candidate:\n            count += 1\n        else:\n            count -= 1\n    return candidate" },
        { id: "a8", title: "Mission streak",
          say: "Mission results as 1 (success) and 0 (failure). What's the longest streak of successes in a row?",
          task: "Define `longest_streak(results)` returning the length of the longest run of consecutive 1s. Return 0 if there are none.",
          check: "assert longest_streak([1, 1, 0, 1, 1, 1]) == 3\nassert longest_streak([0, 0, 0]) == 0\nassert longest_streak([1, 1, 1, 1]) == 4\nassert longest_streak([]) == 0",
          solution: "def longest_streak(results):\n    best = 0\n    run = 0\n    for r in results:\n        if r == 1:\n            run += 1\n            if run > best:\n                best = run\n        else:\n            run = 0\n    return best" },
        { id: "a9", title: "Formation shift",
          say: "Rotate the formation right by k places: the last k members wrap to the front. k can be bigger than the squad.",
          task: "Define `rotate(squad, k)` returning a new list rotated right by `k` positions. Do not modify the input.",
          hint: "Reduce k with k % len. Then the answer is the last k items followed by the rest — slicing does it.",
          check: "assert rotate([1, 2, 3, 4, 5], 2) == [4, 5, 1, 2, 3]\nassert rotate([1, 2, 3], 4) == [3, 1, 2], 'k larger than the list wraps around.'\nassert rotate([1, 2, 3], 0) == [1, 2, 3]\nx = [1, 2, 3]; rotate(x, 1); assert x == [1, 2, 3], 'Do not modify the input.'",
          solution: "def rotate(squad, k):\n    if len(squad) == 0:\n        return []\n    k = k % len(squad)\n    return squad[len(squad) - k:] + squad[:len(squad) - k]" },
        { id: "a10", title: "Merge the squads",
          say: "Two squads already sorted by chakra. Merge them into one sorted list without sorting from scratch — walk both with a pointer each and take the smaller.",
          task: "Define `merge(a, b)` where both lists are sorted ascending; return a single sorted list containing all elements. Do not call `sorted()` or `.sort()`.",
          check: "assert 'sort' not in _src, 'No sorting — merge with two pointers.'\nassert merge([1, 3, 5], [2, 4, 6]) == [1, 2, 3, 4, 5, 6]\nassert merge([], [1, 2]) == [1, 2]\nassert merge([1, 2], []) == [1, 2]\nassert merge([1, 1, 4], [1, 2]) == [1, 1, 1, 2, 4]",
          solution: "def merge(a, b):\n    result = []\n    i = 0\n    j = 0\n    while i < len(a) and j < len(b):\n        if a[i] <= b[j]:\n            result.append(a[i])\n            i += 1\n        else:\n            result.append(b[j])\n            j += 1\n    while i < len(a):\n        result.append(a[i])\n        i += 1\n    while j < len(b):\n        result.append(b[j])\n        j += 1\n    return result" }
      ]}
    ]}
];
