/* Academy curriculum, taught by Iruka-sensei. Four ranks:
     D  Ninja History       — read code and predict its output, then fix broken code
     C  Weapon Handling     — one concept per problem, written from scratch
     B  Chakra Control      — several concepts combined
     A  Tactics & Formation — array problems that need a plan before any code

   Problem fields
     say        what Iruka says when the problem opens
     task       the assignment, in plain English (backticks render as code)
     examples   optional worked examples shown under the task
     starter    optional code already in the editor: only things the problem is NOT testing
                (data for a loop, a parent class to inherit from, a buggy program to repair)
     check      Python run in the student's namespace afterwards; `_out` is what they printed,
                `_src` is their source; raise AssertionError("message") to fail
     solution   a reference answer
     hint       optional, shown on request
   Read-only types: "mc" (choices/answer/explain), "output" (expected/explain). "bug" is a code problem whose starter is broken. */
window.LESSONS = [
  /* ============================ D-RANK ============================ */
  { id: "D", rank: "D", title: "Ninja History", short: "History", kanji: "史",
    intro: "Before you throw a kunai you learn how one flies. Read each snippet and tell me what it prints — reason it out, don't run it. Then we repair some broken scrolls.",
    topics: [
      { id: "d-vars", title: "Variables & arithmetic", problems: [
        { id: "d1", type: "mc", title: "Floor and remainder",
          code: "kunai = 7\nsquads = 2\nprint(kunai // squads, kunai % squads)",
          question: "What does this print?",
          choices: ["3.5 1", "3 1", "3 0", "4 1"], answer: 1,
          explain: "// divides and drops the fraction (7 // 2 is 3). % gives what's left over (7 % 2 is 1). print puts a space between its two values." },
        { id: "d2", type: "output", title: "String arithmetic",
          code: "name = 'Naruto'\nprint(len(name) + 1)\nprint(name * 2)",
          question: "Type exactly what this prints (two lines).",
          expected: "7\nNarutoNaruto",
          explain: "len('Naruto') is 6, so the first line is 7. Multiplying a string by 2 repeats it with nothing in between." },
        { id: "d3", type: "mc", title: "Copy of a number",
          code: "a = 5\nb = a\na = 10\nprint(b)",
          question: "What does this print?",
          choices: ["10", "5", "15", "an error"], answer: 1,
          explain: "b = a copies the value 5 into b at that moment. Changing a afterwards doesn't reach back into b. (Lists behave differently — we'll get there.)" },
        { id: "d4", type: "mc", title: "and / or",
          code: "chakra = 40\nprint(chakra > 30 and chakra < 35)\nprint(chakra > 30 or chakra < 35)",
          question: "What does this print?",
          choices: ["True\nTrue", "False\nFalse", "False\nTrue", "True\nFalse"], answer: 2,
          explain: "40 > 30 is True, 40 < 35 is False. `and` needs both to be True, so the first line is False. `or` needs just one, so the second is True." }
      ]},
      { id: "d-loops", title: "Loops", problems: [
        { id: "d5", type: "output", title: "Range, doubled",
          code: "for i in range(3):\n    print(i * 2)",
          question: "Type exactly what this prints.",
          expected: "0\n2\n4",
          explain: "range(3) counts 0, 1, 2 — it stops before 3. Each is doubled and printed on its own line." },
        { id: "d6", type: "mc", title: "Only the even ones",
          code: "total = 0\nfor n in [1, 2, 3, 4, 5, 6]:\n    if n % 2 == 0:\n        total += n\nprint(total)",
          question: "What does this print?",
          choices: ["21", "9", "12", "6"], answer: 2,
          explain: "n % 2 == 0 is true only for even numbers, so only 2, 4 and 6 are added: 12." },
        { id: "d7", type: "output", title: "Tripling while",
          code: "n = 1\nwhile n < 20:\n    n *= 3\nprint(n)",
          question: "Type exactly what this prints.",
          expected: "27",
          explain: "n goes 1 → 3 → 9 → 27. The check happens before each loop: 9 < 20 so it triples once more to 27; 27 < 20 is false so it stops. The print is after the loop, so only 27 appears." },
        { id: "d8", type: "mc", title: "break",
          code: "for name in ['Kiba', 'Shino', 'Hinata', 'Kurenai']:\n    if name == 'Hinata':\n        break\n    print(name)",
          question: "What does this print?",
          choices: ["Kiba\nShino", "Kiba\nShino\nHinata", "Hinata", "Kiba\nShino\nKurenai"], answer: 0,
          explain: "break leaves the loop immediately. Hinata triggers it before her print runs, and Kurenai is never reached." }
      ]},
      { id: "d-funcs", title: "Functions", problems: [
        { id: "d9", type: "output", title: "A call inside a call",
          code: "def boost(x):\n    return x + 1\n\nprint(boost(boost(2)))",
          question: "Type exactly what this prints.",
          expected: "4",
          explain: "Work from the inside out: boost(2) is 3, then boost(3) is 4." },
        { id: "d10", type: "mc", title: "Default parameter",
          code: "def greet(name='shinobi'):\n    return 'Hi ' + name\n\nprint(greet())\nprint(greet('Iruka'))",
          question: "What does this print?",
          choices: ["Hi\nHi Iruka", "Hi shinobi\nHi Iruka", "Hi name\nHi Iruka", "an error"], answer: 1,
          explain: "Called with nothing, name falls back to its default 'shinobi'. Called with 'Iruka', that replaces the default." },
        { id: "d11", type: "mc", title: "return ends the function",
          code: "def rank(score):\n    if score > 80:\n        return 'Jonin'\n    return 'Genin'\n    print('done')\n\nprint(rank(90))",
          question: "What does this print?",
          choices: ["Jonin\ndone", "Jonin", "Genin", "done"], answer: 1,
          explain: "return hands the value back and the function stops right there. The print('done') line can never run — it's after a return." },
        { id: "d12", type: "output", title: "A list goes into a function",
          code: "def recruit(team):\n    team.append('Sai')\n\nsquad = ['Naruto', 'Sakura']\nrecruit(squad)\nprint(len(squad))",
          question: "Type exactly what this prints.",
          expected: "3",
          explain: "The function gets the same list, not a copy. Appending inside it changes squad, so the length is now 3." }
      ]},
      { id: "d-classes", title: "Classes", problems: [
        { id: "d13", type: "mc", title: "Changing an attribute",
          code: "class Ninja:\n    def __init__(self, rank):\n        self.rank = rank\n\nn = Ninja('Genin')\nn.rank = 'Chunin'\nprint(n.rank)",
          question: "What does this print?",
          choices: ["Genin", "Chunin", "rank", "an error"], answer: 1,
          explain: "An attribute can be reassigned after the object is made. The last value written is the one that prints." },
        { id: "d14", type: "mc", title: "Inherited method",
          code: "class Shinobi:\n    def jutsu(self):\n        return 'Substitution'\n\nclass Uchiha(Shinobi):\n    pass\n\nprint(Uchiha().jutsu())",
          question: "What does this print?",
          choices: ["an error", "None", "Substitution", "pass"], answer: 2,
          explain: "Uchiha adds nothing of its own (pass) but inherits jutsu() from Shinobi, so the call works." },
        { id: "d15", type: "mc", title: "Override with super()",
          code: "class Shinobi:\n    def jutsu(self):\n        return 'Clone'\n\nclass Uchiha(Shinobi):\n    def jutsu(self):\n        return 'Fireball + ' + super().jutsu()\n\nprint(Uchiha().jutsu())",
          question: "What does this print?",
          choices: ["Clone", "Fireball + Clone", "Fireball + ", "an error"], answer: 1,
          explain: "Uchiha replaces jutsu() but reaches the parent's version through super(), then joins the two strings." },
        { id: "d16", type: "output", title: "Two separate objects",
          code: "class Counter:\n    def __init__(self):\n        self.n = 0\n    def hit(self):\n        self.n += 1\n\na = Counter()\nb = Counter()\na.hit()\na.hit()\nb.hit()\nprint(a.n, b.n)",
          question: "Type exactly what this prints.",
          expected: "2 1",
          explain: "Each object has its own self.n. a was hit twice and b once — they don't share a counter." }
      ]},
      { id: "d-bugs", title: "Field repairs", problems: [
        { id: "d17", type: "bug", title: "One student missing",
          say: "This roll call should print all four students, but it keeps skipping one. Find the bug and fix it — change as little as you can.",
          task: "Fix the program so it prints all four names, one per line.",
          starter: "students = ['Naruto', 'Hinata', 'Shikamaru', 'Choji']\nfor i in range(len(students) - 1):\n    print(students[i])\n",
          check: "lines = [l.strip() for l in _out.strip().splitlines()]\nassert lines == ['Naruto','Hinata','Shikamaru','Choji'], f'It printed {lines} — still missing someone. Look at the range.'",
          solution: "students = ['Naruto', 'Hinata', 'Shikamaru', 'Choji']\nfor i in range(len(students)):\n    print(students[i])" },
        { id: "d18", type: "bug", title: "The loop that never ends",
          say: "Careful — as written this runs forever, so read it before you run it. Something inside the loop never changes.",
          task: "Fix the countdown so it prints 3, 2, 1 on separate lines, then `Go!`, and stops.",
          starter: "n = 3\nwhile n > 0:\n    print(n)\nprint('Go!')\n",
          check: "lines = [l.strip() for l in _out.strip().splitlines()]\nassert lines == ['3','2','1','Go!'], f'Expected 3, 2, 1, Go! but got {lines}'",
          solution: "n = 3\nwhile n > 0:\n    print(n)\n    n -= 1\nprint('Go!')" },
        { id: "d19", type: "bug", title: "The silent function",
          say: "This function is supposed to hand the total back to whoever calls it, but the caller keeps getting None. Why?",
          task: "Fix `total_chakra` so that `print(total_chakra([10, 20, 30]))` prints `60`.",
          starter: "def total_chakra(values):\n    total = 0\n    for v in values:\n        total += v\n    print(total)\n\nresult = total_chakra([10, 20, 30])\nprint(result)\n",
          check: "assert total_chakra([10, 20, 30]) == 60, 'total_chakra([10, 20, 30]) should give back 60 — printing is not the same as returning.'\nassert total_chakra([]) == 0, 'With an empty list it should return 0.'",
          solution: "def total_chakra(values):\n    total = 0\n    for v in values:\n        total += v\n    return total\n\nresult = total_chakra([10, 20, 30])\nprint(result)" },
        { id: "d20", type: "bug", title: "Squads that share a list",
          say: "Two squads should be independent, but adding to one adds to both. The list is in the wrong place.",
          task: "Fix the class so that two `Squad` objects each have their own members. After `a.add('Naruto')`, `b.members` must still be empty.",
          starter: "class Squad:\n    members = []\n\n    def add(self, name):\n        self.members.append(name)\n\na = Squad()\nb = Squad()\na.add('Naruto')\nprint(b.members)\n",
          check: "a = Squad(); b = Squad(); a.add('Naruto')\nassert a.members == ['Naruto'], 'a should have Naruto.'\nassert b.members == [], 'b still shares the list. Create the list inside __init__ so each object gets its own.'",
          solution: "class Squad:\n    def __init__(self):\n        self.members = []\n\n    def add(self, name):\n        self.members.append(name)\n\na = Squad()\nb = Squad()\na.add('Naruto')\nprint(b.members)" },
        { id: "d21", type: "bug", title: "Wrong comparison",
          say: "A score of 80 or more should pass, but students who scored exactly 80 are being failed. Read the condition carefully.",
          task: "Fix `grade` so that 80 and above returns `'PASS'` and anything below returns `'FAIL'`.",
          starter: "def grade(score):\n    if score > 80:\n        return 'PASS'\n    else:\n        return 'FAIL'\n\nprint(grade(80))\n",
          check: "assert grade(80) == 'PASS', 'grade(80) should be PASS — 80 counts.'\nassert grade(79) == 'FAIL' and grade(95) == 'PASS', 'Below 80 fails, above passes.'",
          solution: "def grade(score):\n    if score >= 80:\n        return 'PASS'\n    else:\n        return 'FAIL'\n\nprint(grade(80))" }
      ]}
    ]},

  /* ============================ C-RANK ============================ */
  { id: "C", rank: "C", title: "Weapon Handling", short: "Weapons", kanji: "器",
    intro: "One weapon at a time. Each problem practises a single skill, and you write it from a blank editor. When I give you a line, it's only because that part isn't the lesson.",
    topics: [
      { id: "c-vars", title: "Variables & types", problems: [
        { id: "c1", title: "Registration card",
          say: "Every shinobi has a record. Let's write yours.",
          task: "Make four variables: `name` holding any text you like, `age` holding a whole number, `height` holding a decimal number, and `is_genin` holding True or False. Then print `name`.",
          check: "for n in ['name','age','height','is_genin']: assert n in dir(), f'I don\\'t see a variable called {n}.'\nassert type(name) is str, 'name should be text — put it in quotes.'\nassert type(age) is int, 'age should be a whole number like 13.'\nassert type(height) is float, 'height should be a decimal like 1.5.'\nassert type(is_genin) is bool, 'is_genin should be True or False.'\nassert name in _out, 'Finish by printing name.'",
          solution: "name = 'Rock Lee'\nage = 13\nheight = 1.58\nis_genin = True\nprint(name)" },
        { id: "c2", title: "Chakra budget",
          say: "You have 120 chakra and every jutsu costs 35. How many can you cast, and what's left?",
          task: "Store 120 in a variable called `chakra` and 35 in a variable called `cost`. Print how many whole jutsu you can cast, then on the next line print how much chakra is left over.",
          examples: ["It should print:\n3\n15"],
          check: "assert chakra == 120 and cost == 35, 'Use chakra = 120 and cost = 35.'\nlines = [l.strip() for l in _out.strip().splitlines()]\nassert lines[:1] == ['3'], f'First line should be 3 (whole jutsu), got {lines[:1]}. Try // for whole-number division.'\nassert lines[:2] == ['3', '15'], f'Second line should be 15 (left over), got {lines[1:2]}. Try % for the remainder.'",
          solution: "chakra = 120\ncost = 35\nprint(chakra // cost)\nprint(chakra % cost)" },
        { id: "c3", title: "Build a sentence",
          say: "Text joins with +. Build an introduction out of pieces.",
          task: "Store `'Hatake'` in a variable called `first` and `'Kakashi'` in a variable called `last`. Join them, with a space between and `', Jonin'` on the end, into a variable called `intro`, then print it.",
          examples: ["It should print:\nHatake Kakashi, Jonin"],
          check: "assert 'intro' in dir(), 'Put the result in a variable called intro.'\nassert intro == 'Hatake Kakashi, Jonin', f'intro is {intro!r} — check the space and the comma.'\nassert '+' in _src, 'Join the pieces with +.'\nassert 'Hatake Kakashi, Jonin' in _out, 'Print intro at the end.'",
          solution: "first = 'Hatake'\nlast = 'Kakashi'\nintro = first + ' ' + last + ', Jonin'\nprint(intro)" }
      ]},
      { id: "c-lists", title: "Lists", problems: [
        { id: "c4", title: "Kunai pouch",
          say: "A list keeps things in order. Make one and pull out one item — and remember, Python counts from zero.",
          task: "Make a list called `pouch` holding these five words in this order: steel, iron, bronze, silver, gold. Then print the third one.",
          examples: ["It should print:\nbronze"],
          check: "assert 'pouch' in dir() and isinstance(pouch, list), 'Make a list called pouch.'\nassert pouch == ['steel','iron','bronze','silver','gold'], f'pouch is {pouch} — it should be exactly those five words in order.'\nassert _out.strip() == 'bronze', f'You printed {_out.strip()!r}. The third item is at index 2.'",
          solution: "pouch = ['steel', 'iron', 'bronze', 'silver', 'gold']\nprint(pouch[2])" },
        { id: "c5", title: "Growing the squad",
          say: "Lists grow with append. Start Team 7, add two more, and count them with len.",
          task: "Make a list called `squad` with Naruto, Sasuke and Sakura. Use `append` to add Kakashi, then Sai. Print how many names are in the list.",
          examples: ["It should print:\n5"],
          check: "assert 'squad' in dir(), 'Make a list called squad.'\nassert '.append(' in _src, 'Add the new names with append.'\nassert squad == ['Naruto','Sasuke','Sakura','Kakashi','Sai'], f'squad is {squad} — expected the five names in order.'\nassert _out.strip() == '5', 'Print the length with len(squad).'",
          solution: "squad = ['Naruto', 'Sasuke', 'Sakura']\nsquad.append('Kakashi')\nsquad.append('Sai')\nprint(len(squad))" },
        { id: "c6", title: "Last one, and the middle",
          say: "Two tricks: a negative index counts from the end, and a slice takes a range of items.",
          task: "Make a list called `ranks` with Genin, Chunin, Jonin, Anbu, Kage. Print the last item using a negative index. Then print a slice containing just Chunin, Jonin and Anbu.",
          examples: ["It should print:\nKage\n['Chunin', 'Jonin', 'Anbu']"],
          check: "lines = [l.strip() for l in _out.strip().splitlines()]\nassert '[-1]' in _src, 'Use ranks[-1] for the last item.'\nassert lines[:1] == ['Kage'], f'First line should be Kage, got {lines[:1]}'\nassert len(lines) > 1 and lines[1] == \"['Chunin', 'Jonin', 'Anbu']\", f'Second line should be the slice. A slice [1:4] gives items 1, 2 and 3.'",
          solution: "ranks = ['Genin', 'Chunin', 'Jonin', 'Anbu', 'Kage']\nprint(ranks[-1])\nprint(ranks[1:4])" },
        { id: "c6b", title: "Pop the last mission",
          say: "pop() takes the last item off the list and hands it to you. The list gets shorter.",
          task: "Make a list called `missions` with the strings `'escort'`, `'patrol'`, `'rescue'`. Use `pop` to remove the last one and store it in a variable called `done`. Print `done`, then print `missions`.",
          examples: ["It should print:\nrescue\n['escort', 'patrol']"],
          check: "assert '.pop(' in _src, 'Use missions.pop().'\nassert 'done' in dir() and done == 'rescue', f'done should hold the popped item rescue, it is {done!r}.'\nassert missions == ['escort', 'patrol'], f'missions is {missions} — pop should have removed rescue.'\nlines = [l.strip() for l in _out.strip().splitlines()]\nassert lines == ['rescue', \"['escort', 'patrol']\"], f'Got {lines}'",
          solution: "missions = ['escort', 'patrol', 'rescue']\ndone = missions.pop()\nprint(done)\nprint(missions)" },
        { id: "c6c", title: "Insert into the line",
          say: "append always goes on the end. insert lets you choose the position — everything after it shifts along.",
          task: "Make a list called `line` with Naruto, Sakura, Sasuke. Use `insert` to put Kakashi at the front (position 0), and then put Sai between Sakura and Sasuke. Print the list.",
          examples: ["It should print:\n['Kakashi', 'Naruto', 'Sakura', 'Sai', 'Sasuke']"],
          check: "assert '.insert(' in _src, 'Use line.insert(position, name).'\nassert line == ['Kakashi', 'Naruto', 'Sakura', 'Sai', 'Sasuke'], f'line is {line}. After inserting Kakashi at 0, Sai goes at position 3.'\nassert \"['Kakashi', 'Naruto', 'Sakura', 'Sai', 'Sasuke']\" in _out, 'Print the list at the end.'",
          solution: "line = ['Naruto', 'Sakura', 'Sasuke']\nline.insert(0, 'Kakashi')\nline.insert(3, 'Sai')\nprint(line)" },
        { id: "c6d", title: "Remove by name, remove by position",
          say: "Two ways to take something out: remove() finds a value and deletes it; del or pop(i) deletes whatever is at a position.",
          task: "Make a list called `team` with Naruto, Sasuke, Sakura, Kakashi, Sai. Use `remove` to take out `'Sasuke'` by name. Then delete whatever is now at position 2 (with `del team[2]` or `team.pop(2)`). Print the list.",
          examples: ["It should print:\n['Naruto', 'Sakura', 'Sai']"],
          check: "assert '.remove(' in _src, 'Use team.remove(\"Sasuke\") for the first removal.'\nassert 'del ' in _src or '.pop(2)' in _src, 'Delete by position with del team[2] or team.pop(2).'\nassert team == ['Naruto', 'Sakura', 'Sai'], f'team is {team}. After removing Sasuke the list is Naruto, Sakura, Kakashi, Sai — position 2 is Kakashi.'\nassert \"['Naruto', 'Sakura', 'Sai']\" in _out",
          solution: "team = ['Naruto', 'Sasuke', 'Sakura', 'Kakashi', 'Sai']\nteam.remove('Sasuke')\ndel team[2]\nprint(team)" },
        { id: "c6e", title: "Is Sasuke here?",
          say: "The in keyword asks whether a value is in a list. It gives back True or False, so it slots straight into an if.",
          task: "Make a list called `present` with Naruto, Sakura, Shikamaru. Check whether `'Sasuke'` is in the list with `in`: if he is, print `Sasuke reported`; otherwise print `Sasuke is missing`. Then do the same check for `'Sakura'`.",
          examples: ["It should print:\nSasuke is missing\nSakura reported"],
          check: "assert ' in ' in _src and 'if' in _src, 'Use if ... in present.'\nlines = [l.strip() for l in _out.strip().splitlines()]\nassert lines == ['Sasuke is missing', 'Sakura reported'], f'Got {lines}'",
          solution: "present = ['Naruto', 'Sakura', 'Shikamaru']\nif 'Sasuke' in present:\n    print('Sasuke reported')\nelse:\n    print('Sasuke is missing')\nif 'Sakura' in present:\n    print('Sakura reported')\nelse:\n    print('Sakura is missing')" },
        { id: "c6f", title: "Sort the scores",
          say: "sort() rearranges the list in place, smallest first. reverse=True flips it to largest first.",
          task: "Make a list called `scores` with the numbers 72, 95, 58, 88. Sort it from smallest to largest and print it. Then sort it from largest to smallest and print it again.",
          examples: ["It should print:\n[58, 72, 88, 95]\n[95, 88, 72, 58]"],
          check: "assert '.sort(' in _src, 'Use scores.sort().'\nassert 'reverse=True' in _src.replace(' ', ''), 'For largest-first, pass reverse=True to sort.'\nlines = [l.strip() for l in _out.strip().splitlines()]\nassert lines == ['[58, 72, 88, 95]', '[95, 88, 72, 58]'], f'Got {lines}'",
          solution: "scores = [72, 95, 58, 88]\nscores.sort()\nprint(scores)\nscores.sort(reverse=True)\nprint(scores)" },
        { id: "c6g", title: "Where is Kakashi?",
          say: "index() tells you the position of a value. Pair it with len to describe a list.",
          task: "Make a list called `jonin` with Kakashi, Asuma, Kurenai, Guy. Print the position of `'Kurenai'` using `index`, then print how many jonin there are, then print the first and last names on one line separated by a space.",
          examples: ["It should print:\n2\n4\nKakashi Guy"],
          check: "assert '.index(' in _src, 'Use jonin.index(\"Kurenai\").'\nlines = [l.strip() for l in _out.strip().splitlines()]\nassert lines[:1] == ['2'], f'First line should be 2 (the position of Kurenai), got {lines[:1]}'\nassert lines[1:2] == ['4'], f'Second line should be 4 (len), got {lines[1:2]}'\nassert lines[2:3] == ['Kakashi Guy'], f'Third line should be Kakashi Guy, got {lines[2:3]}'",
          solution: "jonin = ['Kakashi', 'Asuma', 'Kurenai', 'Guy']\nprint(jonin.index('Kurenai'))\nprint(len(jonin))\nprint(jonin[0], jonin[-1])" },
        { id: "c6h", title: "Reverse the formation",
          say: "reverse() flips a list end to end. That's different from sorting — it doesn't care about the values, only the order.",
          task: "Make a list called `formation` with the numbers 1, 2, 3, 4, 5. Reverse it in place and print it. Then make a new list called `back` that is `formation` reversed again (using a slice with `[::-1]`), without changing `formation`, and print `back`.",
          examples: ["It should print:\n[5, 4, 3, 2, 1]\n[1, 2, 3, 4, 5]"],
          check: "assert '.reverse(' in _src, 'Use formation.reverse() for the first flip.'\nassert '[::-1]' in _src, 'Use the slice [::-1] to make the reversed copy.'\nassert formation == [5, 4, 3, 2, 1], f'formation is {formation}, expected [5, 4, 3, 2, 1] (the slice must not change it).'\nassert back == [1, 2, 3, 4, 5], f'back is {back}'\nlines = [l.strip() for l in _out.strip().splitlines()]\nassert lines == ['[5, 4, 3, 2, 1]', '[1, 2, 3, 4, 5]'], f'Got {lines}'",
          solution: "formation = [1, 2, 3, 4, 5]\nformation.reverse()\nprint(formation)\nback = formation[::-1]\nprint(back)" },
        { id: "c6i", title: "Biggest, smallest, total",
          say: "Three built-ins that take a whole list: max, min and sum.",
          task: "Make a list called `chakra` with the numbers 40, 95, 60, 25, 80. Print the largest value, then the smallest, then the total of all of them.",
          examples: ["It should print:\n95\n25\n300"],
          check: "assert 'max(' in _src and 'min(' in _src and 'sum(' in _src, 'Use max(), min() and sum().'\nlines = [l.strip() for l in _out.strip().splitlines()]\nassert lines == ['95', '25', '300'], f'Got {lines}'",
          solution: "chakra = [40, 95, 60, 25, 80]\nprint(max(chakra))\nprint(min(chakra))\nprint(sum(chakra))" },
        { id: "c6j", title: "Two squads become one",
          say: "+ joins two lists into a new one; extend adds one list onto the end of another in place. Both are common — know the difference.",
          task: "Make `team7` with Naruto, Sasuke, Sakura and `team10` with Shikamaru, Ino, Choji. Make a new list called `both` by joining them with `+`, and print it. Then use `extend` to add `team10` onto the end of `team7` itself, and print `team7`.",
          examples: ["It should print:\n['Naruto', 'Sasuke', 'Sakura', 'Shikamaru', 'Ino', 'Choji']\n['Naruto', 'Sasuke', 'Sakura', 'Shikamaru', 'Ino', 'Choji']"],
          check: "assert '.extend(' in _src, 'Use team7.extend(team10) for the second part.'\nassert both == ['Naruto', 'Sasuke', 'Sakura', 'Shikamaru', 'Ino', 'Choji'], f'both is {both}'\nassert team7 == ['Naruto', 'Sasuke', 'Sakura', 'Shikamaru', 'Ino', 'Choji'], f'team7 is {team7} — extend should have grown it.'\nassert team10 == ['Shikamaru', 'Ino', 'Choji'], 'team10 should be unchanged.'",
          solution: "team7 = ['Naruto', 'Sasuke', 'Sakura']\nteam10 = ['Shikamaru', 'Ino', 'Choji']\nboth = team7 + team10\nprint(both)\nteam7.extend(team10)\nprint(team7)" }
      ]},
      { id: "c-for", title: "For loops", problems: [
        { id: "c7", title: "Roll call",
          say: "A for loop runs its block once per item. The list is yours; write the loop.",
          task: "Print every name in `students`, one per line, using a for loop.",
          starter: "students = ['Naruto', 'Hinata', 'Shikamaru', 'Choji']\n",
          examples: ["It should print:\nNaruto\nHinata\nShikamaru\nChoji"],
          check: "assert 'for' in _src, 'Use a for loop.'\nlines = [l.strip() for l in _out.strip().splitlines()]\nassert lines == ['Naruto','Hinata','Shikamaru','Choji'], f'Got {lines}'",
          solution: "students = ['Naruto', 'Hinata', 'Shikamaru', 'Choji']\nfor s in students:\n    print(s)" },
        { id: "c8", title: "Lap counter",
          say: "Guy-sensei's warm-up. range makes the numbers for you — just remember it stops before its end value.",
          task: "Print the numbers 1 to 10, one per line, using a for loop with `range`.",
          check: "assert 'range(' in _src, 'Use range to make the numbers.'\nlines = [l.strip() for l in _out.strip().splitlines()]\nassert lines == [str(i) for i in range(1, 11)], f'Got {lines}. Remember range(1, 11) stops before 11.'",
          solution: "for i in range(1, 11):\n    print(i)" },
        { id: "c9", title: "Mission payroll",
          say: "Add up the rewards with a loop and a running total. No sum() — I want to see you accumulate it yourself.",
          task: "Make a variable `total` starting at 0. Loop over `rewards` and add each one to `total`. Then print `total`.",
          starter: "rewards = [5000, 3000, 30000, 150000]\n",
          examples: ["It should print:\n188000"],
          check: "assert 'for' in _src, 'Use a for loop.'\nassert 'sum(' not in _src, 'No sum() — add them up in the loop.'\nassert 'total' in dir(), 'Keep the running total in a variable called total.'\nassert total == 188000, f'total ended up {total}, expected 188000.'\nassert '188000' in _out, 'Print total after the loop.'",
          solution: "rewards = [5000, 3000, 30000, 150000]\ntotal = 0\nfor r in rewards:\n    total += r\nprint(total)" }
      ]},
      { id: "c-while", title: "While loops", problems: [
        { id: "c10", title: "Countdown",
          say: "A while loop keeps going as long as its condition is true. Make sure something changes inside, or it never stops.",
          task: "Using a while loop, print 5, 4, 3, 2, 1 on separate lines, then print `Go!`.",
          check: "assert 'while' in _src, 'Use a while loop.'\nlines = [l.strip() for l in _out.strip().splitlines()]\nassert lines == ['5','4','3','2','1','Go!'], f'Got {lines}'",
          solution: "n = 5\nwhile n > 0:\n    print(n)\n    n -= 1\nprint('Go!')" },
        { id: "c11", title: "Chakra doubling",
          say: "Start with 1 chakra and keep doubling. How many doublings until you have at least 1000?",
          task: "Start a variable at 1 and a counter at 0. While the chakra is below 1000, double it and add one to the counter. When the loop ends, print the counter.",
          examples: ["It should print:\n10"],
          check: "assert 'while' in _src, 'Use a while loop.'\nassert _out.strip().endswith('10'), f'You printed {_out.strip()!r}. 1 doubles to 1024 after 10 doublings.'",
          solution: "chakra = 1\ndoublings = 0\nwhile chakra < 1000:\n    chakra *= 2\n    doublings += 1\nprint(doublings)" },
        { id: "c12", title: "Find the traitor",
          say: "Walk the list with a while loop and stop the moment you find who you're looking for. Print the position you stopped at.",
          task: "Using a while loop and an index variable, find the position of `'Orochimaru'` in `names` and print it. Don't use `.index()`.",
          starter: "names = ['Kabuto', 'Mizuki', 'Orochimaru', 'Danzo']\n",
          examples: ["It should print:\n2"],
          check: "assert 'while' in _src, 'Use a while loop.'\nassert '.index(' not in _src, 'No .index() — walk the list yourself.'\nassert _out.strip() == '2', f'You printed {_out.strip()!r}; Orochimaru is at position 2.'",
          solution: "names = ['Kabuto', 'Mizuki', 'Orochimaru', 'Danzo']\ni = 0\nwhile names[i] != 'Orochimaru':\n    i += 1\nprint(i)" }
      ]},
      { id: "c-funcs", title: "Functions", problems: [
        { id: "c13", title: "Greeting jutsu",
          say: "A function is a named move you can reuse. This one returns a greeting — returns it, doesn't print it.",
          task: "Write a function called `greet` that takes in a name and returns the text `Welcome to the Leaf, <name>!`",
          examples: ["greet('Naruto') → 'Welcome to the Leaf, Naruto!'", "greet('Sakura') → 'Welcome to the Leaf, Sakura!'"],
          check: "assert 'greet' in dir() and callable(greet), 'Define a function called greet.'\nr = greet('Naruto')\nassert r is not None, 'greet returned nothing — use return, not print.'\nassert r == 'Welcome to the Leaf, Naruto!', f'greet(\"Naruto\") returned {r!r}'",
          solution: "def greet(name):\n    return 'Welcome to the Leaf, ' + name + '!'" },
        { id: "c14", title: "Training ground area",
          say: "Two values in, one value out.",
          task: "Write a function called `area` that takes in a width and a height and returns the area (width times height).",
          examples: ["area(3, 4) → 12", "area(2.5, 2) → 5.0"],
          check: "assert 'area' in dir() and callable(area), 'Define a function called area.'\nassert area(3, 4) == 12, f'area(3, 4) returned {area(3, 4)!r}, expected 12.'\nassert area(2.5, 2) == 5.0, 'area(2.5, 2) should be 5.0.'",
          solution: "def area(width, height):\n    return width * height" },
        { id: "c15", title: "Rank up",
          say: "A parameter can have a default value, used when the caller leaves it out.",
          task: "The ranks in order are Academy, Genin, Chunin, Jonin, Kage. Write a function called `rank_up` that takes in a rank and a number of steps, and returns the rank that many steps higher. If the caller doesn't give a number of steps, use 1.",
          examples: ["rank_up('Genin') → 'Chunin'", "rank_up('Genin', 2) → 'Jonin'", "rank_up('Academy', 4) → 'Kage'"],
          hint: "Put the ranks in a list. Find where the given rank is with .index(), then add the steps to that position.",
          check: "assert 'rank_up' in dir() and callable(rank_up), 'Define a function called rank_up.'\nassert rank_up('Genin', 2) == 'Jonin', f'rank_up(\"Genin\", 2) returned {rank_up(\"Genin\", 2)!r}, expected Jonin.'\nassert rank_up('Genin') == 'Chunin', 'rank_up(\"Genin\") with no steps should default to one step: Chunin.'\nassert rank_up('Academy', 4) == 'Kage'",
          solution: "RANKS = ['Academy', 'Genin', 'Chunin', 'Jonin', 'Kage']\n\ndef rank_up(rank, steps=1):\n    position = RANKS.index(rank)\n    return RANKS[position + steps]" }
      ]},
      { id: "c-classes", title: "Classes", problems: [
        { id: "c16", title: "A Shinobi class",
          say: "A class is a blueprint. Its constructor (__init__) runs when you make one; self is the object being built.",
          task: "Make a class called `Shinobi` whose constructor takes in a name and a rank and stores them on the object as `name` and `rank`. Give it a method called `introduce` that returns `<name>, <rank> of the Leaf`.",
          examples: ["s = Shinobi('Iruka', 'Chunin')\ns.name → 'Iruka'\ns.introduce() → 'Iruka, Chunin of the Leaf'"],
          check: "assert 'Shinobi' in dir(), 'Define a class called Shinobi.'\ns = Shinobi('Iruka', 'Chunin')\nassert getattr(s, 'name', None) == 'Iruka' and getattr(s, 'rank', None) == 'Chunin', 'Store the name and rank with self.name = ... and self.rank = ...'\nassert s.introduce() == 'Iruka, Chunin of the Leaf', f'introduce() returned {s.introduce()!r}'",
          solution: "class Shinobi:\n    def __init__(self, name, rank):\n        self.name = name\n        self.rank = rank\n\n    def introduce(self):\n        return self.name + ', ' + self.rank + ' of the Leaf'" },
        { id: "c17", title: "Mission counter",
          say: "Objects remember things between method calls. Count missions on the object itself.",
          task: "Make a class called `Shinobi` whose constructor takes in a name and stores it, and also sets a `missions` count to 0. Give it a method called `complete_mission` that adds one to the count.",
          examples: ["s = Shinobi('Lee')\ns.missions → 0\ns.complete_mission()\ns.complete_mission()\ns.missions → 2"],
          check: "s = Shinobi('Lee')\nassert getattr(s, 'missions', None) == 0, 'missions should start at 0 — set self.missions = 0 in the constructor.'\ns.complete_mission(); s.complete_mission()\nassert s.missions == 2, f'After two calls missions is {s.missions}, expected 2.'",
          solution: "class Shinobi:\n    def __init__(self, name):\n        self.name = name\n        self.missions = 0\n\n    def complete_mission(self):\n        self.missions += 1" }
      ]},
      { id: "c-inherit", title: "Inheritance", problems: [
        { id: "c18", title: "Jonin is a Shinobi",
          say: "A subclass inherits everything from its parent. Here's the parent; write the child, and pass the name up with super().",
          task: "Make a class called `Jonin` that inherits from `Shinobi`. Its constructor takes in only a name, and calls the parent's constructor with that name and the rank `'Jonin'`.",
          starter: "class Shinobi:\n    def __init__(self, name, rank):\n        self.name = name\n        self.rank = rank\n\n    def introduce(self):\n        return self.name + ', ' + self.rank\n\n",
          examples: ["k = Jonin('Kakashi')\nk.rank → 'Jonin'\nk.introduce() → 'Kakashi, Jonin'"],
          check: "assert 'Jonin' in dir(), 'Define a class called Jonin.'\nk = Jonin('Kakashi')\nassert isinstance(k, Shinobi), 'Jonin should inherit from Shinobi: class Jonin(Shinobi).'\nassert k.name == 'Kakashi' and k.rank == 'Jonin', f'name is {k.name!r}, rank is {getattr(k, \"rank\", None)!r}. Call super().__init__(name, \"Jonin\").'\nassert 'super()' in _src, 'Use super().__init__ rather than setting the attributes again.'",
          solution: "class Shinobi:\n    def __init__(self, name, rank):\n        self.name = name\n        self.rank = rank\n\n    def introduce(self):\n        return self.name + ', ' + self.rank\n\nclass Jonin(Shinobi):\n    def __init__(self, name):\n        super().__init__(name, 'Jonin')" },
        { id: "c19", title: "The Hokage introduces differently",
          say: "A child can replace a parent's method completely. The parent is given; write the child.",
          task: "Make a class called `Hokage` that inherits from `Shinobi` and overrides `introduce` so it returns `Lord <name>, Hokage`.",
          starter: "class Shinobi:\n    def __init__(self, name):\n        self.name = name\n\n    def introduce(self):\n        return self.name\n\n",
          examples: ["Hokage('Tsunade').introduce() → 'Lord Tsunade, Hokage'", "Shinobi('Iruka').introduce() → 'Iruka'   (unchanged)"],
          check: "assert 'Hokage' in dir(), 'Define a class called Hokage.'\nh = Hokage('Tsunade')\nassert isinstance(h, Shinobi), 'Hokage should inherit from Shinobi.'\nassert h.introduce() == 'Lord Tsunade, Hokage', f'introduce() returned {h.introduce()!r}'\nassert Shinobi('Iruka').introduce() == 'Iruka', 'Don\\'t change the parent — override the method in Hokage only.'",
          solution: "class Shinobi:\n    def __init__(self, name):\n        self.name = name\n\n    def introduce(self):\n        return self.name\n\nclass Hokage(Shinobi):\n    def introduce(self):\n        return 'Lord ' + self.name + ', Hokage'" }
      ]},
      { id: "c-imports", title: "Imports & libraries", problems: [
        { id: "c20", title: "Square root",
          say: "Python comes with a library of scrolls. import brings one in.",
          task: "Import the `math` module and print the square root of 144 using its `sqrt` function.",
          examples: ["It should print:\n12.0"],
          check: "assert 'import math' in _src, 'Start with: import math'\nassert '12' in _out, 'Print math.sqrt(144).'",
          solution: "import math\nprint(math.sqrt(144))" },
        { id: "c21", title: "Random pick",
          say: "You can pull a single tool out of a scroll with from ... import.",
          task: "Make a list of three names of your choosing. Use `from random import choice` to import just `choice`, then print one name picked at random.",
          check: "assert 'from random import' in _src, 'Use the form: from random import choice'\nlists = [v for v in list(globals().values()) if isinstance(v, list) and len(v) == 3 and all(isinstance(x, str) for x in v)]\nassert lists, 'Make a list of three names (strings).'\nassert any(_out.strip() in L for L in lists), 'Print one name chosen by choice(your_list).'",
          solution: "from random import choice\nnames = ['Naruto', 'Sasuke', 'Sakura']\nprint(choice(names))" }
      ]},
      { id: "c-copies", title: "Copies & references", problems: [
        { id: "c22", title: "Shadow clone",
          say: "Here's the trap: giving a list a second name does not copy it. Watch it happen.",
          task: "Make a list called `original` containing just `'Naruto'`. Make a second variable `clone` equal to `original`. Append `'Sasuke'` to `clone`. Then print `original` and see what happened to it.",
          examples: ["It should print:\n['Naruto', 'Sasuke']"],
          check: "assert 'original' in dir() and 'clone' in dir(), 'Make both original and clone.'\nassert clone is original, 'clone should be the same list: clone = original (no copy).'\nassert original == ['Naruto', 'Sasuke'], f'original is {original}. Append Sasuke through clone.'\nassert \"['Naruto', 'Sasuke']\" in _out, 'Print original at the end.'",
          solution: "original = ['Naruto']\nclone = original\nclone.append('Sasuke')\nprint(original)" },
        { id: "c23", title: "A real copy",
          say: "Now protect the original. list() or .copy() makes a new list with the same contents.",
          task: "Make a list called `original` containing just `'Naruto'`. Make `copy` a real copy of it. Append `'Sasuke'` to `copy`, then print `original` — it should be untouched.",
          examples: ["It should print:\n['Naruto']"],
          check: "assert 'original' in dir() and 'copy' in dir(), 'Make both original and copy.'\nassert copy is not original, 'copy is still the same list. Use list(original) or original.copy().'\nassert copy == ['Naruto', 'Sasuke'], f'copy is {copy}, expected Naruto and Sasuke.'\nassert original == ['Naruto'], f'original is {original} — it should still be just Naruto.'\nassert \"['Naruto']\" in _out, 'Print original at the end.'",
          solution: "original = ['Naruto']\ncopy = original.copy()\ncopy.append('Sasuke')\nprint(original)" }
      ]}
    ]},

  /* ============================ B-RANK ============================ */
  { id: "B", rank: "B", title: "Chakra Control", short: "Chakra", kanji: "制",
    intro: "Now you combine weapons. Each problem needs two or three skills working together. Read the examples, decide what pieces you need, then write them one at a time.",
    topics: [
      { id: "b-all", title: "Combined techniques", problems: [
        { id: "b1", title: "Payout calculator",
          say: "Missions pay by rank. A function, a loop and some if/elif branches will do it.",
          task: "Write a function called `payout` that takes in a list of rank letters and returns the total pay. D-rank pays 5000, C-rank 30000, B-rank 150000 and A-rank 600000.",
          examples: ["payout(['D']) → 5000", "payout(['D', 'C', 'D']) → 40000", "payout([]) → 0"],
          check: "assert 'payout' in dir() and callable(payout), 'Define a function called payout.'\nassert payout([]) == 0, 'An empty list should pay 0.'\nassert payout(['D']) == 5000, f'payout([\"D\"]) returned {payout([\"D\"])!r}, expected 5000.'\nassert payout(['D', 'C', 'D']) == 40000, f'payout([\"D\",\"C\",\"D\"]) returned {payout([\"D\",\"C\",\"D\"])!r}, expected 40000.'\nassert payout(['A', 'B', 'C', 'D']) == 785000, 'One of each should be 785000.'",
          solution: "def payout(ranks):\n    total = 0\n    for r in ranks:\n        if r == 'D':\n            total += 5000\n        elif r == 'C':\n            total += 30000\n        elif r == 'B':\n            total += 150000\n        elif r == 'A':\n            total += 600000\n    return total" },
        { id: "b2", title: "Squad roster",
          say: "A class that keeps a list, and a method that turns it into numbered lines.",
          task: "Make a class called `Squad` that starts with an empty `members` list. Give it an `add` method that takes a name and appends it, and a `roster` method that returns one string with the members numbered from 1, one per line (joined with newlines). An empty squad's roster is an empty string.",
          examples: ["s = Squad()\ns.add('Naruto')\ns.add('Sakura')\ns.roster() → '1. Naruto\\n2. Sakura'"],
          hint: "Build a list of lines like '1. Naruto', then join them with '\\n'.join(lines).",
          check: "s = Squad()\nassert s.members == [], 'members should start as an empty list.'\nassert s.roster() == '', 'An empty squad should give an empty string.'\ns.add('Naruto'); s.add('Sakura'); s.add('Sai')\nassert s.members == ['Naruto', 'Sakura', 'Sai'], 'add should append to members.'\nassert s.roster() == '1. Naruto\\n2. Sakura\\n3. Sai', f'roster() returned {s.roster()!r}'",
          solution: "class Squad:\n    def __init__(self):\n        self.members = []\n\n    def add(self, name):\n        self.members.append(name)\n\n    def roster(self):\n        lines = []\n        for i in range(len(self.members)):\n            lines.append(str(i + 1) + '. ' + self.members[i])\n        return '\\n'.join(lines)" },
        { id: "b3", title: "Strongest on the team",
          say: "Inheritance plus a function that works on a list of objects.",
          task: "Make a `Shinobi` class whose constructor takes in a name and a chakra amount and stores them. Give it a `power` method that returns the shinobi's chakra. Then make a `Jonin` class that inherits from `Shinobi`, whose `power` returns double the chakra. Finally, write a function called `strongest` that takes in a list of shinobi and returns the name of the one with the highest power.",
          examples: ["Jonin('Kakashi', 50).power() → 100", "strongest([Shinobi('Naruto', 90), Jonin('Kakashi', 50)]) → 'Kakashi'   (100 beats 90)"],
          hint: "In strongest, keep track of the best member seen so far and replace it whenever you find a higher power().",
          check: "assert Shinobi('Naruto', 90).power() == 90, 'A Shinobi\\'s power should be its chakra.'\nassert Jonin('Kakashi', 50).power() == 100, 'A Jonin\\'s power should be double the chakra.'\nassert isinstance(Jonin('Asuma', 1), Shinobi), 'Jonin should inherit from Shinobi.'\nteam = [Shinobi('Naruto', 90), Jonin('Kakashi', 50), Shinobi('Sakura', 60)]\nassert strongest(team) == 'Kakashi', f'strongest(team) returned {strongest(team)!r}; Kakashi has 100.'\nassert strongest([Shinobi('Naruto', 90), Jonin('Asuma', 40)]) == 'Naruto', 'Naruto (90) beats Asuma (80).'",
          solution: "class Shinobi:\n    def __init__(self, name, chakra):\n        self.name = name\n        self.chakra = chakra\n\n    def power(self):\n        return self.chakra\n\nclass Jonin(Shinobi):\n    def power(self):\n        return self.chakra * 2\n\ndef strongest(team):\n    best = team[0]\n    for member in team:\n        if member.power() > best.power():\n            best = member\n    return best.name" },
        { id: "b4", title: "Training sessions",
          say: "A function with a while loop inside it. Each session adds 10% to your chakra, rounded down.",
          task: "Write a function called `sessions` that takes in a starting chakra and a target, and returns how many training sessions it takes to reach the target. Each session increases chakra by a tenth of its current value, rounded down (`chakra + chakra // 10`). If the start already meets the target, return 0.",
          examples: ["sessions(100, 100) → 0", "sessions(100, 121) → 2   (100 → 110 → 121)", "sessions(100, 200) → 8"],
          check: "assert 'while' in _src, 'Use a while loop — you don\\'t know in advance how many sessions it takes.'\nassert sessions(100, 100) == 0, 'Already at the target: 0 sessions.'\nassert sessions(100, 121) == 2, f'sessions(100, 121) returned {sessions(100, 121)!r}: 100 → 110 → 121 is 2.'\nassert sessions(100, 200) == 8, f'sessions(100, 200) returned {sessions(100, 200)!r}, expected 8.'",
          solution: "def sessions(start, target):\n    chakra = start\n    count = 0\n    while chakra < target:\n        chakra = chakra + chakra // 10\n        count += 1\n    return count" },
        { id: "b5", title: "Jutsu scroll",
          say: "A class with a list that refuses duplicates, and a method that reports back whether anything changed.",
          task: "Make a class called `Scroll` that starts with an empty `jutsu` list. Give it a `learn` method that takes a jutsu name: if it's new, add it and return True; if it's already on the scroll, leave the list alone and return False. Also give it a `count` method that returns how many jutsu are stored.",
          examples: ["s = Scroll()\ns.learn('Rasengan') → True\ns.learn('Rasengan') → False\ns.learn('Shadow Clone') → True\ns.count() → 2"],
          check: "s = Scroll()\nassert s.learn('Rasengan') is True, 'Learning a new jutsu should return True.'\nassert s.learn('Rasengan') is False, 'Learning the same jutsu again should return False.'\nassert s.learn('Shadow Clone') is True\nassert s.jutsu == ['Rasengan', 'Shadow Clone'], f'jutsu is {s.jutsu} — the duplicate should not be added.'\nassert s.count() == 2, 'count() should be 2.'",
          solution: "class Scroll:\n    def __init__(self):\n        self.jutsu = []\n\n    def learn(self, name):\n        if name in self.jutsu:\n            return False\n        self.jutsu.append(name)\n        return True\n\n    def count(self):\n        return len(self.jutsu)" },
        { id: "b6", title: "Filter by rank",
          say: "Two lists that line up: position 0 in one matches position 0 in the other. Loop by index to use both at once.",
          task: "Write a function called `with_rank` that takes in a list of names, a list of their ranks (same order), and a rank to look for. Return a new list of the names that have that rank, in their original order.",
          examples: ["names = ['Naruto', 'Shikamaru', 'Kakashi', 'Neji']\nranks = ['Genin', 'Chunin', 'Jonin', 'Chunin']\nwith_rank(names, ranks, 'Chunin') → ['Shikamaru', 'Neji']\nwith_rank(names, ranks, 'Kage') → []"],
          hint: "for i in range(len(names)) lets you look at names[i] and ranks[i] together.",
          check: "n = ['Naruto', 'Shikamaru', 'Kakashi', 'Neji']\nr = ['Genin', 'Chunin', 'Jonin', 'Chunin']\nassert with_rank(n, r, 'Chunin') == ['Shikamaru', 'Neji'], f'with_rank(..., \"Chunin\") returned {with_rank(n, r, \"Chunin\")!r}'\nassert with_rank(n, r, 'Kage') == [], 'No Kage: return an empty list.'\nassert with_rank(n, r, 'Genin') == ['Naruto']",
          solution: "def with_rank(names, ranks, want):\n    result = []\n    for i in range(len(names)):\n        if ranks[i] == want:\n            result.append(names[i])\n    return result" },
        { id: "b7", title: "Grade the exam",
          say: "Two functions that share an idea: 80 or more passes. One builds strings, the other does arithmetic.",
          task: "Write a function called `report` that takes in a list of names and a list of scores (same order) and returns a list of strings, one per student, formatted `<name>: PASS` or `<name>: FAIL`. 80 and above passes. Then write `pass_rate`, which takes in a list of scores and returns the fraction that passed as a decimal (0.0 for an empty list).",
          examples: ["report(['Naruto', 'Sakura'], [55, 95]) → ['Naruto: FAIL', 'Sakura: PASS']", "pass_rate([55, 95, 80, 10]) → 0.5", "pass_rate([]) → 0.0"],
          check: "assert report(['Naruto', 'Sakura'], [55, 95]) == ['Naruto: FAIL', 'Sakura: PASS'], f'report returned {report([\"Naruto\", \"Sakura\"], [55, 95])!r}'\nassert report(['Lee'], [80]) == ['Lee: PASS'], 'Exactly 80 passes.'\nassert pass_rate([55, 95, 80, 10]) == 0.5, f'pass_rate([55, 95, 80, 10]) returned {pass_rate([55, 95, 80, 10])!r}, expected 0.5.'\nassert pass_rate([]) == 0.0, 'Empty list: 0.0 (and no dividing by zero).'",
          solution: "def report(names, scores):\n    lines = []\n    for i in range(len(names)):\n        if scores[i] >= 80:\n            lines.append(names[i] + ': PASS')\n        else:\n            lines.append(names[i] + ': FAIL')\n    return lines\n\ndef pass_rate(scores):\n    if len(scores) == 0:\n        return 0.0\n    passed = 0\n    for s in scores:\n        if s >= 80:\n            passed += 1\n    return passed / len(scores)" }
      ]}
    ]},

  /* ============================ A-RANK ============================ */
  { id: "A", rank: "A", title: "Tactics & Formation", short: "Tactics", kanji: "策",
    intro: "A-rank is about the plan, not the typing. Each of these has a slow, obvious way and a clean way. Read the examples until you could solve them by hand, decide what you need to remember as you walk the list, then write it.",
    topics: [
      { id: "a-all", title: "Array tactics", problems: [
        { id: "a1", title: "Chakra pair",
          say: "Two kunai whose weights add up exactly to a target. The slow way tries every pair. The clean way remembers each weight it has passed, and asks: have I already seen the partner I need?",
          task: "Write a function called `find_pair` that takes in a list of weights and a target. Return the positions of the two weights that add up to the target, as a list of two indexes with the smaller index first. You can assume exactly one such pair exists.",
          examples: ["find_pair([2, 7, 11, 15], 9) → [0, 1]   (2 + 7 = 9)", "find_pair([3, 2, 4], 6) → [1, 2]   (2 + 4 = 6)"],
          hint: "For each weight, the partner you need is target - weight. Keep a dictionary of weight → index for everything you've passed, and check it before adding the current one.",
          check: "assert 'find_pair' in dir(), 'Define a function called find_pair.'\nassert find_pair([2, 7, 11, 15], 9) == [0, 1], f'find_pair([2, 7, 11, 15], 9) returned {find_pair([2, 7, 11, 15], 9)!r}, expected [0, 1].'\nassert find_pair([3, 2, 4], 6) == [1, 2], f'find_pair([3, 2, 4], 6) returned {find_pair([3, 2, 4], 6)!r}, expected [1, 2] — not 3 + 3; the same kunai can\\'t be used twice.'\nassert find_pair([5, 1, 9, 4], 13) == [2, 3]",
          solution: "def find_pair(weights, target):\n    seen = {}\n    for i in range(len(weights)):\n        need = target - weights[i]\n        if need in seen:\n            return [seen[need], i]\n        seen[weights[i]] = i" },
        { id: "a2", title: "Ramen trading",
          say: "The ramen stand's price changes every day. You get to buy one bowl on one day and sell it on a later day. What's the most you could make? One pass is enough if you remember the right thing.",
          task: "Write a function called `best_profit` that takes in a list of prices, one per day. Return the biggest profit possible from buying on one day and selling on a later day. If every later day is cheaper, return 0.",
          examples: ["best_profit([7, 1, 5, 3, 6, 4]) → 5   (buy at 1 on day 2, sell at 6 on day 5)", "best_profit([7, 6, 4, 3, 1]) → 0   (prices only fall)", "best_profit([2, 4, 1]) → 2   (buy at 2, sell at 4; the 1 comes too late)"],
          hint: "Walk the days in order, remembering the cheapest price seen so far. Each day, selling now would make today's price minus that cheapest. Keep the best of those.",
          check: "assert 'best_profit' in dir(), 'Define a function called best_profit.'\nassert best_profit([7, 1, 5, 3, 6, 4]) == 5, f'best_profit([7, 1, 5, 3, 6, 4]) returned {best_profit([7, 1, 5, 3, 6, 4])!r}, expected 5.'\nassert best_profit([7, 6, 4, 3, 1]) == 0, 'When prices only fall the answer is 0, not negative.'\nassert best_profit([2, 4, 1]) == 2, 'You must sell after you buy — the 1 at the end can\\'t be used.'\nassert best_profit([5]) == 0, 'One day: no trade possible, 0.'",
          solution: "def best_profit(prices):\n    cheapest = prices[0]\n    best = 0\n    for price in prices:\n        if price < cheapest:\n            cheapest = price\n        elif price - cheapest > best:\n            best = price - cheapest\n    return best" },
        { id: "a3", title: "Shadow clone check",
          say: "Is anyone on the roster listed twice? Checking every name against every other name works but is slow. A set lets you ask 'have I seen this?' instantly.",
          task: "Write a function called `has_duplicate` that takes in a list of names and returns True if any name appears more than once, otherwise False.",
          examples: ["has_duplicate(['Naruto', 'Sasuke', 'Naruto']) → True", "has_duplicate(['Naruto', 'Sasuke', 'Sakura']) → False", "has_duplicate([]) → False"],
          check: "assert has_duplicate(['Naruto', 'Sasuke', 'Naruto']) is True, 'Naruto appears twice: True.'\nassert has_duplicate(['Naruto', 'Sasuke', 'Sakura']) is False, 'All different: False.'\nassert has_duplicate([]) is False, 'Empty list: False.'",
          solution: "def has_duplicate(names):\n    seen = set()\n    for n in names:\n        if n in seen:\n            return True\n        seen.add(n)\n    return False" },
        { id: "a4", title: "Chakra surge",
          say: "Your chakra changes a little every day — sometimes up, sometimes down. Find the run of consecutive days that adds up to the most. The trick: if the days you're carrying have added up to something negative, they're only dragging you down. Drop them and start fresh.",
          task: "Write a function called `best_surge` that takes in a list of daily changes (positive and negative numbers) and returns the largest total of any run of consecutive days. The run must contain at least one day.",
          examples: ["best_surge([-2, 1, -3, 4, -1, 2, 1, -5, 4]) → 6   (the run 4, -1, 2, 1)", "best_surge([5, 4, -1, 7, 8]) → 23   (take everything)", "best_surge([-3, -1, -2]) → -1   (every day is bad; the least bad single day)"],
          hint: "Keep a running total as you go. After adding each day, update the best total seen. If the running total drops below zero, reset it to zero before the next day.",
          check: "assert best_surge([-2, 1, -3, 4, -1, 2, 1, -5, 4]) == 6, f'best_surge([-2, 1, -3, 4, -1, 2, 1, -5, 4]) returned {best_surge([-2, 1, -3, 4, -1, 2, 1, -5, 4])!r}, expected 6.'\nassert best_surge([5, 4, -1, 7, 8]) == 23, 'All together is best here: 23.'\nassert best_surge([1]) == 1\nassert best_surge([-3, -1, -2]) == -1, 'All negative: the answer is the largest single value, -1, not 0.'",
          solution: "def best_surge(changes):\n    best = changes[0]\n    running = 0\n    for c in changes:\n        running += c\n        if running > best:\n            best = running\n        if running < 0:\n            running = 0\n    return best" },
        { id: "a5", title: "Clear the field",
          say: "Shuriken scores, with 0 for every miss. Move all the misses to the end, keep the hits in their original order, and do it inside the same list — no building a new one.",
          task: "Write a function called `clear_misses` that takes in a list of numbers and rearranges it in place so every 0 is at the end and the other numbers keep their order. The function returns nothing.",
          examples: ["hits = [0, 1, 0, 3, 12]\nclear_misses(hits)\nhits → [1, 3, 12, 0, 0]", "hits = [2, 0, 0, 5, 0, 7]\nclear_misses(hits)\nhits → [2, 5, 7, 0, 0, 0]"],
          hint: "Keep a 'write' position starting at 0. Walk the list; each non-zero gets copied to the write position, which then moves forward by one. When you're done, fill everything from the write position to the end with zeros.",
          check: "a = [0, 1, 0, 3, 12]; r = clear_misses(a)\nassert r is None, 'Return nothing — change the list that was passed in.'\nassert a == [1, 3, 12, 0, 0], f'After clear_misses the list is {a}, expected [1, 3, 12, 0, 0].'\nb = [0]; clear_misses(b); assert b == [0]\nc = [2, 0, 0, 5, 0, 7]; clear_misses(c); assert c == [2, 5, 7, 0, 0, 0], f'Got {c}'",
          solution: "def clear_misses(hits):\n    write = 0\n    for i in range(len(hits)):\n        if hits[i] != 0:\n            hits[write] = hits[i]\n            write += 1\n    while write < len(hits):\n        hits[write] = 0\n        write += 1" },
        { id: "a6", title: "Mirror jutsu",
          say: "A code phrase is a mirror if it reads the same backwards — ignoring capitals and anything that isn't a letter or digit. Clean the text first, then compare from both ends inward.",
          task: "Write a function called `is_mirror` that takes in some text and returns True if it reads the same forwards and backwards once you ignore case and skip every character that isn't a letter or a digit. Otherwise return False.",
          examples: ["is_mirror('A man, a plan, a canal: Panama') → True", "is_mirror('race a car') → False", "is_mirror('Noon') → True", "is_mirror('') → True"],
          hint: "ch.isalnum() tells you if a character is a letter or digit; text.lower() handles the capitals. Build the cleaned list, then compare index i from the front with index j from the back while i < j.",
          check: "assert is_mirror('A man, a plan, a canal: Panama') is True, 'Ignoring punctuation and case, this reads the same both ways.'\nassert is_mirror('race a car') is False\nassert is_mirror('Noon') is True, 'Capital N and lowercase n should count as the same.'\nassert is_mirror('') is True, 'Empty text counts as a mirror.'",
          solution: "def is_mirror(text):\n    chars = []\n    for ch in text.lower():\n        if ch.isalnum():\n            chars.append(ch)\n    i = 0\n    j = len(chars) - 1\n    while i < j:\n        if chars[i] != chars[j]:\n            return False\n        i += 1\n        j -= 1\n    return True" },
        { id: "a7", title: "Clan vote",
          say: "One clan got more than half of all the votes. Find it in a single pass, without counting every clan separately. Think of it as a tug of war: hold a candidate and a count. Matching votes pull the count up; other votes pull it down; when it hits zero, whoever comes next becomes the new candidate.",
          task: "Write a function called `winner` that takes in a list of clan names and returns the one that appears more than half the time. You can assume such a clan always exists.",
          examples: ["winner(['Uchiha', 'Hyuga', 'Uchiha']) → 'Uchiha'", "winner(['Nara', 'Nara', 'Uchiha', 'Nara', 'Hyuga', 'Nara', 'Nara']) → 'Nara'", "winner(['Senju']) → 'Senju'"],
          hint: "candidate = None, count = 0. For each vote: if count is 0, make this vote the candidate. Then if the vote matches the candidate add 1 to count, otherwise subtract 1. The candidate at the end is the winner.",
          check: "assert winner(['Uchiha', 'Hyuga', 'Uchiha']) == 'Uchiha'\nassert winner(['Nara', 'Nara', 'Uchiha', 'Nara', 'Hyuga', 'Nara', 'Nara']) == 'Nara', f'Got {winner([\"Nara\", \"Nara\", \"Uchiha\", \"Nara\", \"Hyuga\", \"Nara\", \"Nara\"])!r}, expected Nara.'\nassert winner(['Senju']) == 'Senju'\nassert winner(['A', 'B', 'B', 'A', 'B']) == 'B'",
          solution: "def winner(votes):\n    candidate = None\n    count = 0\n    for v in votes:\n        if count == 0:\n            candidate = v\n        if v == candidate:\n            count += 1\n        else:\n            count -= 1\n    return candidate" },
        { id: "a8", title: "Mission streak",
          say: "Mission results in order: 1 for success, 0 for failure. What's the longest unbroken run of successes?",
          task: "Write a function called `longest_streak` that takes in a list of 1s and 0s and returns the length of the longest run of consecutive 1s. If there are no 1s, return 0.",
          examples: ["longest_streak([1, 1, 0, 1, 1, 1]) → 3", "longest_streak([0, 0, 0]) → 0", "longest_streak([1, 1, 1, 1]) → 4"],
          hint: "Keep the current run length and the best run length. A 1 extends the current run; a 0 resets it to zero. Update the best whenever the current run grows.",
          check: "assert longest_streak([1, 1, 0, 1, 1, 1]) == 3, f'Got {longest_streak([1, 1, 0, 1, 1, 1])!r}, expected 3.'\nassert longest_streak([0, 0, 0]) == 0\nassert longest_streak([1, 1, 1, 1]) == 4, 'A run that reaches the end still counts.'\nassert longest_streak([]) == 0",
          solution: "def longest_streak(results):\n    best = 0\n    run = 0\n    for r in results:\n        if r == 1:\n            run += 1\n            if run > best:\n                best = run\n        else:\n            run = 0\n    return best" },
        { id: "a9", title: "Formation shift",
          say: "Rotate the formation to the right: the last member wraps around to the front, and you do that k times. k might be bigger than the squad, and the original list must not change.",
          task: "Write a function called `rotate` that takes in a list and a number k, and returns a new list that is the original rotated right by k positions. Do not modify the list you were given.",
          examples: ["rotate([1, 2, 3, 4, 5], 2) → [4, 5, 1, 2, 3]", "rotate([1, 2, 3], 4) → [3, 1, 2]   (4 rotations of 3 items is the same as 1)", "rotate([1, 2, 3], 0) → [1, 2, 3]"],
          hint: "First shrink k with k % len(list). Then the answer is the last k items followed by everything before them — two slices joined with +.",
          check: "assert rotate([1, 2, 3, 4, 5], 2) == [4, 5, 1, 2, 3], f'rotate([1, 2, 3, 4, 5], 2) returned {rotate([1, 2, 3, 4, 5], 2)!r}'\nassert rotate([1, 2, 3], 4) == [3, 1, 2], 'k bigger than the list should wrap around (use %).'\nassert rotate([1, 2, 3], 0) == [1, 2, 3]\nx = [1, 2, 3]; rotate(x, 1); assert x == [1, 2, 3], 'The original list was changed — build and return a new one.'",
          solution: "def rotate(squad, k):\n    if len(squad) == 0:\n        return []\n    k = k % len(squad)\n    return squad[len(squad) - k:] + squad[:len(squad) - k]" },
        { id: "a10", title: "Merge the squads",
          say: "Two squads, each already sorted by chakra. Merge them into one sorted list without sorting from scratch: keep a pointer in each list and always take the smaller of the two fronts.",
          task: "Write a function called `merge` that takes in two lists that are each already sorted from smallest to largest, and returns one sorted list containing everything from both. Don't use `sorted()` or `.sort()`.",
          examples: ["merge([1, 3, 5], [2, 4, 6]) → [1, 2, 3, 4, 5, 6]", "merge([1, 1, 4], [1, 2]) → [1, 1, 1, 2, 4]", "merge([], [1, 2]) → [1, 2]"],
          hint: "i points into the first list, j into the second. While both have items left, append the smaller front and move that pointer. When one runs out, append the rest of the other.",
          check: "assert 'sort' not in _src, 'No sorting — merge with two pointers.'\nassert merge([1, 3, 5], [2, 4, 6]) == [1, 2, 3, 4, 5, 6], f'merge([1, 3, 5], [2, 4, 6]) returned {merge([1, 3, 5], [2, 4, 6])!r}'\nassert merge([], [1, 2]) == [1, 2], 'An empty first list: just return the second.'\nassert merge([1, 2], []) == [1, 2]\nassert merge([1, 1, 4], [1, 2]) == [1, 1, 1, 2, 4], 'Equal values must all be kept.'",
          solution: "def merge(a, b):\n    result = []\n    i = 0\n    j = 0\n    while i < len(a) and j < len(b):\n        if a[i] <= b[j]:\n            result.append(a[i])\n            i += 1\n        else:\n            result.append(b[j])\n            j += 1\n    while i < len(a):\n        result.append(a[i])\n        i += 1\n    while j < len(b):\n        result.append(b[j])\n        j += 1\n    return result" }
      ]}
    ]}
];
