services:
  - type: web
    name: hidden-leaf
    runtime: static
    buildCommand: ""
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /
        destination: /index.html
    headers:
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=86400
